export const DAILY_WORDS = [
  { id: 100077, level: "A1", pos: "noun", en: "address", fa: "آدرس" },
  { id: 100103, level: "A1", pos: "noun", en: "advice", fa: "توصیه" },
  { id: 100112, level: "A1", pos: "adjective", en: "afraid", fa: "ترسیده" },
  { id: 100115, level: "A1", pos: "noun", en: "afternoon", fa: "بعد از ظهر" },
  { id: 100119, level: "A1", pos: "noun", en: "age", fa: "سن" },
  { id: 100127, level: "A1", pos: "verb", en: "agree", fa: "موافقت کردن" },
  { id: 100140, level: "A1", pos: "noun", en: "airport", fa: "فرودگاه" },
  { id: 100174, level: "A1", pos: "adverb", en: "always", fa: "همیشه" },
  { id: 100199, level: "A1", pos: "adjective", en: "angry", fa: "عصبانی" },
  { id: 100213, level: "A1", pos: "noun", en: "answer", fa: "پاسخ" },
  { id: 100238, level: "A1", pos: "noun", en: "apple", fa: "سیب" },
  { id: 100265, level: "A1", pos: "noun", en: "arm", fa: "بازو" },
  { id: 100275, level: "A1", pos: "verb", en: "arrive", fa: "رسیدن" },
  { id: 100288, level: "A1", pos: "verb", en: "ask", fa: "پرسیدن" },
  { id: 100348, level: "A1", pos: "noun", en: "autumn", fa: "پاییز" },
  { id: 100360, level: "A1", pos: "noun", en: "baby", fa: "بچه" },
  { id: 100371, level: "A1", pos: "noun", en: "bag", fa: "کیف" },
  { id: 100381, level: "A1", pos: "noun", en: "banana", fa: "موز" },
  { id: 100403, level: "A1", pos: "noun", en: "bathroom", fa: "حمام" },
  { id: 100419, level: "A1", pos: "noun", en: "bed", fa: "تخت" },
  { id: 100420, level: "A1", pos: "noun", en: "bedroom", fa: "اتاق خواب" },
  { id: 100426, level: "A1", pos: "verb", en: "begin", fa: "شروع کردن" },
  { id: 100434, level: "A1", pos: "verb", en: "believe", fa: "باور کردن" },
  { id: 100457, level: "A1", pos: "noun", en: "bicycle", fa: "دوچرخه" },
  { id: 100460, level: "A1", pos: "noun", en: "bike", fa: "دوچرخه" },
  { id: 100461, level: "A1", pos: "noun", en: "bill", fa: "صورتحساب" },
  { id: 100470, level: "A1", pos: "noun", en: "birthday", fa: "تولد" },
  { id: 100477, level: "A1", pos: "adjective", en: "black", fa: "سیاه" },
  { id: 100493, level: "A1", pos: "adjective", en: "blue", fa: "آبی" },
  { id: 100497, level: "A1", pos: "noun", en: "body", fa: "بدن" },
  { id: 100505, level: "A1", pos: "noun", en: "book", fa: "کتاب" },
  { id: 100533, level: "A1", pos: "noun", en: "bread", fa: "نان" },
  { id: 100536, level: "A1", pos: "noun", en: "breakfast", fa: "صبحانه" },
  { id: 100557, level: "A1", pos: "noun", en: "brother", fa: "برادر" },
  { id: 100579, level: "A1", pos: "noun", en: "bus", fa: "اتوبوس" },
  { id: 100587, level: "A1", pos: "verb", en: "buy", fa: "خریدن" },
  { id: 100589, level: "A1", pos: "exclamation", en: "bye", fa: "خداحافظ" },
  { id: 100597, level: "A1", pos: "noun", en: "call", fa: "تماس" },
  { id: 100621, level: "A1", pos: "noun", en: "car", fa: "ماشین" },
  { id: 100623, level: "A1", pos: "noun", en: "card", fa: "کارت" },
  { id: 100671, level: "A1", pos: "noun", en: "chair", fa: "صندلی" },
  { id: 100679, level: "A1", pos: "noun", en: "change", fa: "تغییر" },
  { id: 100694, level: "A1", pos: "adjective", en: "cheap", fa: "ارزان" },
  { id: 100705, level: "A1", pos: "noun", en: "chicken", fa: "مرغ" },
  { id: 100707, level: "A1", pos: "noun", en: "child", fa: "کودک" },
  { id: 100728, level: "A1", pos: "noun", en: "city", fa: "شهر" },
  { id: 100744, level: "A1", pos: "adjective", en: "clean", fa: "تمیز" },
  { id: 100758, level: "A1", pos: "noun", en: "clock", fa: "ساعت" },
  { id: 100759, level: "A1", pos: "verb", en: "close", fa: "بستن" },
  { id: 100764, level: "A1", pos: "noun", en: "clothes", fa: "لباس" },
  { id: 100778, level: "A1", pos: "noun", en: "coffee", fa: "قهوه" },
  { id: 100783, level: "A1", pos: "adjective", en: "cold", fa: "سرد" },
  { id: 100804, level: "A1", pos: "verb", en: "come", fa: "آمدن" },
  { id: 100830, level: "A1", pos: "noun", en: "company", fa: "شرکت" },
  { id: 100987, level: "A1", pos: "verb", en: "cook", fa: "پختن" },
  { id: 100989, level: "A1", pos: "noun", en: "cooking", fa: "آشپزی" },
  { id: 100990, level: "A1", pos: "adjective", en: "cool", fa: "خنک" },
  { id: 101089, level: "A1", pos: "noun", en: "cup", fa: "فنجان" },
  { id: 101110, level: "A1", pos: "noun", en: "dad", fa: "پدر" },
  { id: 101126, level: "A1", pos: "noun", en: "date", fa: "تاریخ" },
  { id: 101127, level: "A1", pos: "noun", en: "daughter", fa: "دختر" },
  { id: 101129, level: "A1", pos: "noun", en: "day", fa: "روز" },
  { id: 101183, level: "A1", pos: "adjective", en: "delicious", fa: "خوشمزه" },
  { id: 101279, level: "A1", pos: "noun", en: "dinner", fa: "شام" },
  { id: 101356, level: "A1", pos: "verb", en: "do", fa: "انجام دادن" },
  { id: 101357, level: "A1", pos: "noun", en: "doctor", fa: "دکتر" },
  { id: 101372, level: "A1", pos: "noun", en: "door", fa: "در" },
  { id: 101392, level: "A1", pos: "noun", en: "dress", fa: "لباس" },
  { id: 101395, level: "A1", pos: "noun", en: "drink", fa: "نوشیدنی" },
  { id: 101396, level: "A1", pos: "verb", en: "drive", fa: "رانندگی کردن" },
  { id: 101421, level: "A1", pos: "noun", en: "ear", fa: "گوش" },
  { id: 101422, level: "A1", pos: "adjective", en: "early", fa: "زود" },
  { id: 101457, level: "A1", pos: "noun", en: "egg", fa: "تخم مرغ" },
  { id: 101485, level: "A1", pos: "noun", en: "email", fa: "ایمیل" },
  { id: 101518, level: "A1", pos: "noun", en: "end", fa: "پایان" },
  { id: 101598, level: "A1", pos: "noun", en: "evening", fa: "عصر" },
  { id: 101631, level: "A1", pos: "adjective", en: "excited", fa: "هیجان زده" },
  { id: 101642, level: "A1", pos: "noun", en: "exercise", fa: "ورزش" },
  { id: 101659, level: "A1", pos: "adjective", en: "expensive", fa: "گران" },
  { id: 101695, level: "A1", pos: "noun", en: "eye", fa: "چشم" },
  { id: 101719, level: "A1", pos: "adjective", en: "family", fa: "خانوادگی" },
  { id: 101738, level: "A1", pos: "noun", en: "father", fa: "پدر" },
  { id: 101752, level: "A1", pos: "verb", en: "feel", fa: "احساس کردن" },
  { id: 101753, level: "A1", pos: "noun", en: "feeling", fa: "احساس" },
  { id: 101784, level: "A1", pos: "verb", en: "finish", fa: "تمام کردن" },
  { id: 101793, level: "A1", pos: "noun", en: "fish", fa: "ماهی" },
  { id: 101813, level: "A1", pos: "noun", en: "flight", fa: "پرواز" },
  { id: 101832, level: "A1", pos: "noun", en: "food", fa: "غذا" },
  { id: 101834, level: "A1", pos: "noun", en: "foot", fa: "پا" },
  { id: 101836, level: "A1", pos: "noun", en: "football", fa: "فوتبال" },
  { id: 101846, level: "A1", pos: "verb", en: "forget", fa: "فراموش کردن" },
  { id: 101889, level: "A1", pos: "noun", en: "Friday", fa: "جمعه" },
  { id: 101891, level: "A1", pos: "noun", en: "friend", fa: "دوست" },
  { id: 101901, level: "A1", pos: "noun", en: "fruit", fa: "میوه" },
  { id: 101931, level: "A1", pos: "noun", en: "game", fa: "بازی" },
  { id: 101969, level: "A1", pos: "verb", en: "give", fa: "دادن" },
  { id: 101972, level: "A1", pos: "noun", en: "glass", fa: "لیوان" },
  { id: 101980, level: "A1", pos: "verb", en: "go", fa: "رفتن" },
  { id: 101987, level: "A1", pos: "exclamation", en: "goodbye", fa: "خداحافظ" },
  { id: 102015, level: "A1", pos: "adjective", en: "green", fa: "سبز" },
  { id: 102048, level: "A1", pos: "noun", en: "hair", fa: "مو" },
  { id: 102053, level: "A1", pos: "noun", en: "hand", fa: "دست" },
  { id: 102062, level: "A1", pos: "adjective", en: "happy", fa: "خوشحال" },
  { id: 102073, level: "A1", pos: "noun", en: "hat", fa: "کلاه" },
  { id: 102074, level: "A1", pos: "verb", en: "hate", fa: "نفرت داشتن" },
  { id: 102081, level: "A1", pos: "noun", en: "head", fa: "سر" },
  { id: 102088, level: "A1", pos: "adjective", en: "healthy", fa: "سالم" },
  { id: 102089, level: "A1", pos: "verb", en: "hear", fa: "شنیدن" },
  { id: 102102, level: "A1", pos: "exclamation", en: "hello", fa: "سلام" },
  { id: 102104, level: "A1", pos: "noun", en: "help", fa: "کمک" },
  { id: 102116, level: "A1", pos: "exclamation", en: "hi", fa: "سلام" },
  { id: 102142, level: "A1", pos: "noun", en: "holiday", fa: "تعطیلات" },
  { id: 102145, level: "A1", pos: "adverb", en: "home", fa: "خانه" },
  { id: 102153, level: "A1", pos: "verb", en: "hope", fa: "امیدوار بودن" },
  { id: 102161, level: "A1", pos: "noun", en: "hospital", fa: "بیمارستان" },
  { id: 102166, level: "A1", pos: "adjective", en: "hot", fa: "گرم" },
  { id: 102167, level: "A1", pos: "noun", en: "hotel", fa: "هتل" },
  { id: 102168, level: "A1", pos: "noun", en: "hour", fa: "ساعت" },
  { id: 102169, level: "A1", pos: "noun", en: "house", fa: "خانه" },
  { id: 102183, level: "A1", pos: "adjective", en: "hungry", fa: "گرسنه" },
  { id: 102189, level: "A1", pos: "noun", en: "husband", fa: "شوهر" },
  { id: 102430, level: "A1", pos: "noun", en: "jacket", fa: "کت" },
  { id: 102438, level: "A1", pos: "noun", en: "job", fa: "کار" },
  { id: 102450, level: "A1", pos: "noun", en: "juice", fa: "آب میوه" },
  { id: 102464, level: "A1", pos: "adjective", en: "key", fa: "کلیدی" },
  { id: 102478, level: "A1", pos: "noun", en: "kitchen", fa: "آشپزخانه" },
  { id: 102482, level: "A1", pos: "verb", en: "know", fa: "دانستن" },
  { id: 102508, level: "A1", pos: "adjective", en: "late", fa: "دیر" },
  { id: 102510, level: "A1", pos: "adverb", en: "later", fa: "بعداً" },
  { id: 102534, level: "A1", pos: "verb", en: "learn", fa: "یاد گرفتن" },
  { id: 102538, level: "A1", pos: "verb", en: "leave", fa: "ترک کردن" },
  { id: 102541, level: "A1", pos: "noun", en: "leg", fa: "پا" },
  { id: 102562, level: "A1", pos: "noun", en: "letter", fa: "نامه" },
  { id: 102571, level: "A1", pos: "verb", en: "lie", fa: "دراز کشیدن" },
  { id: 102579, level: "A1", pos: "preposition", en: "like", fa: "مثل" },
  { id: 102596, level: "A1", pos: "verb", en: "listen", fa: "گوش دادن" },
  { id: 102606, level: "A1", pos: "verb", en: "live", fa: "زندگی کردن" },
  { id: 102627, level: "A1", pos: "verb", en: "look", fa: "نگاه کردن" },
  { id: 102640, level: "A1", pos: "noun", en: "love", fa: "عشق" },
  { id: 102648, level: "A1", pos: "noun", en: "lunch", fa: "ناهار" },
  { id: 102671, level: "A1", pos: "verb", en: "make", fa: "ساختن" },
  { id: 102698, level: "A1", pos: "noun", en: "market", fa: "بازار" },
  { id: 102722, level: "A1", pos: "adverb", en: "maybe", fa: "شاید" },
  { id: 102725, level: "A1", pos: "noun", en: "meal", fa: "وعده غذایی" },
  { id: 102734, level: "A1", pos: "noun", en: "meat", fa: "گوشت" },
  { id: 102747, level: "A1", pos: "noun", en: "meeting", fa: "جلسه" },
  { id: 102760, level: "A1", pos: "noun", en: "menu", fa: "منو" },
  { id: 102769, level: "A1", pos: "noun", en: "message", fa: "پیام" },
  { id: 102785, level: "A1", pos: "noun", en: "milk", fa: "شیر" },
  { id: 102800, level: "A1", pos: "noun", en: "minute", fa: "دقیقه" },
  { id: 102810, level: "A1", pos: "noun", en: "mistake", fa: "اشتباه" },
  { id: 102827, level: "A1", pos: "noun", en: "Monday", fa: "دوشنبه" },
  { id: 102828, level: "A1", pos: "noun", en: "money", fa: "پول" },
  { id: 102834, level: "A1", pos: "noun", en: "month", fa: "ماه" },
  { id: 102843, level: "A1", pos: "noun", en: "morning", fa: "صبح" },
  { id: 102848, level: "A1", pos: "noun", en: "mother", fa: "مادر" },
  { id: 102859, level: "A1", pos: "noun", en: "mouth", fa: "دهان" },
  { id: 102862, level: "A1", pos: "noun", en: "movie", fa: "فیلم" },
  { id: 102873, level: "A1", pos: "noun", en: "music", fa: "موسیقی" },
  { id: 102885, level: "A1", pos: "noun", en: "name", fa: "نام" },
  { id: 102907, level: "A1", pos: "verb", en: "need", fa: "نیاز داشتن" },
  { id: 102923, level: "A1", pos: "adverb", en: "never", fa: "هرگز" },
  { id: 102934, level: "A1", pos: "noun", en: "night", fa: "شب" },
  { id: 102939, level: "A1", pos: "determiner", en: "no", fa: "نه" },
  { id: 102960, level: "A1", pos: "noun", en: "nose", fa: "بینی" },
  { id: 102974, level: "A1", pos: "adverb", en: "now", fa: "اکنون" },
  { id: 103021, level: "A1", pos: "noun", en: "office", fa: "دفتر" },
  { id: 103025, level: "A1", pos: "adverb", en: "often", fa: "اغلب" },
  { id: 103039, level: "A1", pos: "adjective", en: "open", fa: "باز" },
  { id: 103061, level: "A1", pos: "adjective", en: "orange", fa: "نارنجی" },
  { id: 103140, level: "A1", pos: "noun", en: "parent", fa: "والدین" },
  { id: 103143, level: "A1", pos: "noun", en: "park", fa: "پارک" },
  { id: 103159, level: "A1", pos: "noun", en: "party", fa: "حزب" },
  { id: 103181, level: "A1", pos: "verb", en: "pay", fa: "پرداخت کردن" },
  { id: 103195, level: "A1", pos: "noun", en: "pepper", fa: "فلفل" },
  { id: 103228, level: "A1", pos: "noun", en: "phone", fa: "تلفن" },
  { id: 103265, level: "A1", pos: "noun", en: "play", fa: "بازی" },
  { id: 103270, level: "A1", pos: "exclamation", en: "please", fa: "لطفاً" },
  { id: 103366, level: "A1", pos: "adjective", en: "present", fa: "حاضر" },
  { id: 103389, level: "A1", pos: "noun", en: "price", fa: "قیمت" },
  { id: 103520, level: "A1", pos: "noun", en: "question", fa: "سؤال" },
  { id: 103545, level: "A1", pos: "noun", en: "rain", fa: "باران" },
  { id: 103568, level: "A1", pos: "verb", en: "read", fa: "خواندن" },
  { id: 103613, level: "A1", pos: "adjective", en: "red", fa: "قرمز" },
  { id: 103653, level: "A1", pos: "verb", en: "relax", fa: "آرامش" },
  { id: 103675, level: "A1", pos: "verb", en: "remember", fa: "به یاد آوردن" },
  { id: 103733, level: "A1", pos: "noun", en: "restaurant", fa: "رستوران" },
  { id: 103764, level: "A1", pos: "noun", en: "rice", fa: "برنج" },
  { id: 103780, level: "A1", pos: "noun", en: "road", fa: "جاده" },
  { id: 103793, level: "A1", pos: "noun", en: "room", fa: "اتاق" },
  { id: 103803, level: "A1", pos: "noun", en: "routine", fa: "روال" },
  { id: 103815, level: "A1", pos: "verb", en: "run", fa: "دویدن" },
  { id: 103823, level: "A1", pos: "adjective", en: "sad", fa: "غمگین" },
  { id: 103835, level: "A1", pos: "noun", en: "salt", fa: "نمک" },
  { id: 103845, level: "A1", pos: "noun", en: "Saturday", fa: "شنبه" },
  { id: 103849, level: "A1", pos: "verb", en: "say", fa: "گفتن" },
  { id: 103883, level: "A1", pos: "determiner", en: "second", fa: "دوم" },
  { id: 103893, level: "A1", pos: "verb", en: "see", fa: "دیدن" },
  { id: 103906, level: "A1", pos: "verb", en: "sell", fa: "فروختن" },
  { id: 103954, level: "A1", pos: "verb", en: "share", fa: "به اشتراک گذاشتن" },
  { id: 103971, level: "A1", pos: "noun", en: "shirt", fa: "پیراهن" },
  { id: 103975, level: "A1", pos: "noun", en: "shoe", fa: "کفش" },
  { id: 103978, level: "A1", pos: "noun", en: "shop", fa: "فروشگاه" },
  { id: 103979, level: "A1", pos: "noun", en: "shopping", fa: "خرید" },
  { id: 103996, level: "A1", pos: "adjective", en: "sick", fa: "بیمار" },
  { id: 104028, level: "A1", pos: "noun", en: "sister", fa: "خواهر" },
  { id: 104044, level: "A1", pos: "noun", en: "skirt", fa: "دامن" },
  { id: 104052, level: "A1", pos: "verb", en: "sleep", fa: "خوابیدن" },
  { id: 104074, level: "A1", pos: "noun", en: "snow", fa: "برف" },
  { id: 104104, level: "A1", pos: "adverb", en: "sometimes", fa: "گاهی اوقات" },
  { id: 104107, level: "A1", pos: "noun", en: "son", fa: "پسر" },
  { id: 104108, level: "A1", pos: "noun", en: "song", fa: "آهنگ" },
  { id: 104109, level: "A1", pos: "adverb", en: "soon", fa: "به زودی" },
  { id: 104111, level: "A1", pos: "adjective", en: "sorry", fa: "متاسف" },
  { id: 104125, level: "A1", pos: "verb", en: "speak", fa: "صحبت کردن" },
  { id: 104168, level: "A1", pos: "noun", en: "sport", fa: "ورزش" },
  { id: 104174, level: "A1", pos: "noun", en: "spring", fa: "بهار" },
  { id: 104197, level: "A1", pos: "verb", en: "start", fa: "شروع کردن" },
  { id: 104201, level: "A1", pos: "noun", en: "station", fa: "ایستگاه" },
  { id: 104206, level: "A1", pos: "verb", en: "stay", fa: "ماندن" },
  { id: 104227, level: "A1", pos: "noun", en: "stop", fa: "توقف" },
  { id: 104241, level: "A1", pos: "noun", en: "street", fa: "خیابان" },
  { id: 104261, level: "A1", pos: "noun", en: "study", fa: "مطالعه" },
  { id: 104300, level: "A1", pos: "noun", en: "sugar", fa: "شکر" },
  { id: 104310, level: "A1", pos: "noun", en: "summer", fa: "تابستان" },
  { id: 104312, level: "A1", pos: "noun", en: "sun", fa: "خورشید" },
  { id: 104313, level: "A1", pos: "noun", en: "Sunday", fa: "یکشنبه" },
  { id: 104361, level: "A1", pos: "verb", en: "swim", fa: "شنا کردن" },
  { id: 104376, level: "A1", pos: "noun", en: "table", fa: "میز" },
  { id: 104383, level: "A1", pos: "verb", en: "take", fa: "گرفتن" },
  { id: 104387, level: "A1", pos: "verb", en: "talk", fa: "صحبت کردن" },
  { id: 104396, level: "A1", pos: "noun", en: "taxi", fa: "تاکسی" },
  { id: 104398, level: "A1", pos: "noun", en: "tea", fa: "چای" },
  { id: 104399, level: "A1", pos: "verb", en: "teach", fa: "تدریس کردن" },
  { id: 104413, level: "A1", pos: "verb", en: "tell", fa: "گفتن" },
  { id: 104445, level: "A1", pos: "noun", en: "text", fa: "متن" },
  { id: 104449, level: "A1", pos: "verb", en: "thank", fa: "تشکر کردن" },
  { id: 104451, level: "A1", pos: "exclamation", en: "thanks", fa: "متشکرم" },
  { id: 104478, level: "A1", pos: "verb", en: "think", fa: "فکر کردن" },
  { id: 104481, level: "A1", pos: "adjective", en: "thirsty", fa: "تشنه" },
  { id: 104504, level: "A1", pos: "noun", en: "Thursday", fa: "پنجشنبه" },
  { id: 104506, level: "A1", pos: "noun", en: "ticket", fa: "بلیط" },
  { id: 104514, level: "A1", pos: "noun", en: "time", fa: "زمان" },
  { id: 104520, level: "A1", pos: "adjective", en: "tired", fa: "خسته" },
  { id: 104525, level: "A1", pos: "adverb", en: "today", fa: "امروز" },
  { id: 104533, level: "A1", pos: "adverb", en: "tomorrow", fa: "فردا" },
  { id: 104557, level: "A1", pos: "noun", en: "town", fa: "شهر" },
  { id: 104572, level: "A1", pos: "noun", en: "train", fa: "قطار" },
  { id: 104593, level: "A1", pos: "noun", en: "travel", fa: "سفر" },
  { id: 104611, level: "A1", pos: "noun", en: "trip", fa: "سفر" },
  { id: 104625, level: "A1", pos: "verb", en: "try", fa: "تلاش کردن" },
  { id: 104628, level: "A1", pos: "noun", en: "Tuesday", fa: "سه شنبه" },
  { id: 104649, level: "A1", pos: "noun", en: "umbrella", fa: "چتر" },
  { id: 104662, level: "A1", pos: "verb", en: "understand", fa: "فهمیدن" },
  { id: 104718, level: "A1", pos: "adverb", en: "usually", fa: "معمولاً" },
  { id: 104722, level: "A1", pos: "noun", en: "vacation", fa: "تعطیلات" },
  { id: 104739, level: "A1", pos: "noun", en: "vegetable", fa: "سبزیجات" },
  { id: 104765, level: "A1", pos: "noun", en: "village", fa: "روستا" },
  { id: 104777, level: "A1", pos: "noun", en: "visit", fa: "بازدید" },
  { id: 104793, level: "A1", pos: "verb", en: "wait", fa: "منتظر ماندن" },
  { id: 104794, level: "A1", pos: "noun", en: "waiter", fa: "پیشخدمت" },
  { id: 104795, level: "A1", pos: "verb", en: "wake", fa: "بیدار شدن" },
  { id: 104796, level: "A1", pos: "noun", en: "walk", fa: "راه رفتن" },
  { id: 104799, level: "A1", pos: "verb", en: "want", fa: "خواستن" },
  { id: 104804, level: "A1", pos: "adjective", en: "warm", fa: "گرم" },
  { id: 104810, level: "A1", pos: "verb", en: "wash", fa: "شستن" },
  { id: 104813, level: "A1", pos: "noun", en: "watch", fa: "ساعت" },
  { id: 104814, level: "A1", pos: "noun", en: "water", fa: "آب" },
  { id: 104825, level: "A1", pos: "noun", en: "weather", fa: "آب و هوا" },
  { id: 104830, level: "A1", pos: "noun", en: "Wednesday", fa: "چهارشنبه" },
  { id: 104832, level: "A1", pos: "noun", en: "week", fa: "هفته" },
  { id: 104833, level: "A1", pos: "noun", en: "weekend", fa: "آخر هفته" },
  { id: 104838, level: "A1", pos: "adjective", en: "welcome", fa: "خوش آمدید" },
  { id: 104862, level: "A1", pos: "adjective", en: "white", fa: "سفید" },
  { id: 104876, level: "A1", pos: "noun", en: "wife", fa: "همسر" },
  { id: 104884, level: "A1", pos: "noun", en: "window", fa: "پنجره" },
  { id: 104888, level: "A1", pos: "noun", en: "winter", fa: "زمستان" },
  { id: 104908, level: "A1", pos: "noun", en: "work", fa: "کار" },
  { id: 104931, level: "A1", pos: "verb", en: "write", fa: "نوشتن" },
  { id: 104938, level: "A1", pos: "noun", en: "year", fa: "سال" },
  { id: 104940, level: "A1", pos: "adjective", en: "yellow", fa: "زرد" },
  { id: 104941, level: "A1", pos: "exclamation", en: "yes", fa: "بله" },
  { id: 104942, level: "A1", pos: "adverb", en: "yesterday", fa: "دیروز" },
  { id: 100262, level: "A2", pos: "verb", en: "argue", fa: "بحث کردن" },
  { id: 100263, level: "A2", pos: "noun", en: "argument", fa: "بحث" },
  { id: 300003, level: "A2", pos: "idiom", en: "as soon as possible", fa: "هر چه زودتر" },
  { id: 300002, level: "A2", pos: "idiom", en: "at least", fa: "حداقل" },
  { id: 100514, level: "A2", pos: "verb", en: "borrow", fa: "قرض گرفتن" },
  { id: 100515, level: "A2", pos: "noun", en: "boss", fa: "رئیس" },
  { id: 300004, level: "A2", pos: "idiom", en: "by the way", fa: "راستی" },
  { id: 100637, level: "A2", pos: "noun", en: "cash", fa: "پول نقد" },
  { id: 300032, level: "A2", pos: "idiom", en: "catch up", fa: "جبران کردن، به‌روز شدن" },
  { id: 100693, level: "A2", pos: "noun", en: "chat", fa: "گپ" },
  { id: 100717, level: "A2", pos: "noun", en: "church", fa: "کلیسا" },
  { id: 100765, level: "A2", pos: "noun", en: "clothing", fa: "لباس" },
  { id: 100787, level: "A2", pos: "noun", en: "colleague", fa: "همکار" },
  { id: 300024, level: "A2", pos: "idiom", en: "come back", fa: "برگشتن" },
  { id: 300034, level: "A2", pos: "idiom", en: "come up with", fa: "به فکر چیزی رسیدن" },
  { id: 100847, level: "A2", pos: "verb", en: "complain", fa: "شکایت کردن" },
  { id: 101293, level: "A2", pos: "verb", en: "disagree", fa: "مخالفت کردن" },
  { id: 300030, level: "A2", pos: "idiom", en: "drop off", fa: "رساندن کسی به جایی" },
  { id: 300023, level: "A2", pos: "idiom", en: "find out", fa: "فهمیدن" },
  { id: 300005, level: "A2", pos: "idiom", en: "for example", fa: "برای مثال" },
  { id: 101848, level: "A2", pos: "noun", en: "fork", fa: "چنگال" },
  { id: 300031, level: "A2", pos: "idiom", en: "get along", fa: "با کسی کنار اومدن" },
  { id: 300033, level: "A2", pos: "idiom", en: "get over", fa: "بر چیزی غلبه کردن" },
  { id: 300020, level: "A2", pos: "idiom", en: "get ready", fa: "آماده شدن" },
  { id: 101965, level: "A2", pos: "noun", en: "gift", fa: "هدیه" },
  { id: 300022, level: "A2", pos: "idiom", en: "give up", fa: "تسلیم شدن" },
  { id: 300025, level: "A2", pos: "idiom", en: "go ahead", fa: "شروع کن، ادامه بده" },
  { id: 101981, level: "A2", pos: "noun", en: "goal", fa: "هدف" },
  { id: 300014, level: "A2", pos: "idiom", en: "good luck", fa: "موفق باشی" },
  { id: 102034, level: "A2", pos: "noun", en: "guest", fa: "مهمان" },
  { id: 102045, level: "A2", pos: "noun", en: "habit", fa: "عادت" },
  { id: 300026, level: "A2", pos: "idiom", en: "hang out", fa: "وقت گذروندن با کسی" },
  { id: 300011, level: "A2", pos: "idiom", en: "have fun", fa: "خوش گذروندن" },
  { id: 102209, level: "A2", pos: "adjective", en: "ill", fa: "بیمار" },
  { id: 300019, level: "A2", pos: "idiom", en: "in a hurry", fa: "با عجله" },
  { id: 300006, level: "A2", pos: "idiom", en: "in fact", fa: "در واقع" },
  { id: 102269, level: "A2", pos: "adjective", en: "independent", fa: "مستقل" },
  { id: 102411, level: "A2", pos: "verb", en: "invite", fa: "دعوت کردن" },
  { id: 300017, level: "A2", pos: "idiom", en: "keep in touch", fa: "در ارتباط بودن" },
  { id: 102480, level: "A2", pos: "noun", en: "knife", fa: "چاقو" },
  { id: 102552, level: "A2", pos: "verb", en: "lend", fa: "قرض دادن" },
  { id: 300021, level: "A2", pos: "idiom", en: "look forward to", fa: "مشتاقانه منتظر بودن" },
  { id: 300012, level: "A2", pos: "idiom", en: "make sense", fa: "منطقی بودن" },
  { id: 102742, level: "A2", pos: "noun", en: "medicine", fa: "پزشکی" },
  { id: 102802, level: "A2", pos: "noun", en: "mirror", fa: "آینه" },
  { id: 102918, level: "A2", pos: "adjective", en: "nervous", fa: "عصبی" },
  { id: 300015, level: "A2", pos: "idiom", en: "never mind", fa: "بی‌خیال، مهم نیست" },
  { id: 300001, level: "A2", pos: "idiom", en: "no way", fa: "امکان نداره" },
  { id: 3e5, level: "A2", pos: "idiom", en: "of course", fa: "البته" },
  { id: 300018, level: "A2", pos: "idiom", en: "on time", fa: "به موقع" },
  { id: 300009, level: "A2", pos: "idiom", en: "once in a while", fa: "گاهی اوقات" },
  { id: 103134, level: "A2", pos: "noun", en: "pants", fa: "شلوار" },
  { id: 103176, level: "A2", pos: "noun", en: "patient", fa: "بیمار" },
  { id: 300029, level: "A2", pos: "idiom", en: "pick up", fa: "برداشتن، سوار کردن" },
  { id: 103263, level: "A2", pos: "noun", en: "plate", fa: "بشقاب" },
  { id: 103291, level: "A2", pos: "adjective", en: "polite", fa: "مودب" },
  { id: 103447, level: "A2", pos: "noun", en: "promise", fa: "قول" },
  { id: 103597, level: "A2", pos: "noun", en: "recipe", fa: "دستور پخت" },
  { id: 103602, level: "A2", pos: "verb", en: "recommend", fa: "توصیه کردن" },
  { id: 300008, level: "A2", pos: "idiom", en: "right now", fa: "همین الان" },
  { id: 103809, level: "A2", pos: "adjective", en: "rude", fa: "بی ادب" },
  { id: 300035, level: "A2", pos: "idiom", en: "run out of", fa: "چیزی تمام شدن" },
  { id: 103833, level: "A2", pos: "noun", en: "salary", fa: "حقوق" },
  { id: 103854, level: "A2", pos: "adjective", en: "scared", fa: "ترسیده" },
  { id: 103881, level: "A2", pos: "noun", en: "season", fa: "فصل" },
  { id: 103918, level: "A2", pos: "adjective", en: "separate", fa: "جدا" },
  { id: 300007, level: "A2", pos: "idiom", en: "so far", fa: "تا الان" },
  { id: 104078, level: "A2", pos: "noun", en: "soap", fa: "صابون" },
  { id: 104167, level: "A2", pos: "noun", en: "spoon", fa: "قاشق" },
  { id: 104229, level: "A2", pos: "noun", en: "store", fa: "فروشگاه" },
  { id: 104301, level: "A2", pos: "verb", en: "suggest", fa: "پیشنهاد کردن" },
  { id: 104302, level: "A2", pos: "noun", en: "suggestion", fa: "پیشنهاد" },
  { id: 300010, level: "A2", pos: "idiom", en: "take a break", fa: "استراحت کردن" },
  { id: 300013, level: "A2", pos: "idiom", en: "take care", fa: "مراقب خودت باش" },
  { id: 104555, level: "A2", pos: "noun", en: "towel", fa: "حوله" },
  { id: 104565, level: "A2", pos: "noun", en: "tradition", fa: "سنت" },
  { id: 104566, level: "A2", pos: "adjective", en: "traditional", fa: "سنتی" },
  { id: 104589, level: "A2", pos: "noun", en: "transport", fa: "حمل و نقل" },
  { id: 300028, level: "A2", pos: "idiom", en: "turn off", fa: "خاموش کردن" },
  { id: 300027, level: "A2", pos: "idiom", en: "turn on", fa: "روشن کردن" },
  { id: 104829, level: "A2", pos: "noun", en: "wedding", fa: "عروسی" },
  { id: 300016, level: "A2", pos: "idiom", en: "what's up", fa: "چه خبر" },
  { id: 104893, level: "A2", pos: "noun", en: "wish", fa: "آرزو" },
  { id: 104918, level: "A2", pos: "adjective", en: "worried", fa: "نگران" },
  { id: 300067, level: "B1", pos: "idiom", en: "a blessing in disguise", fa: "نعمتی در پوشش مصیبت" },
  { id: 100050, level: "B1", pos: "noun", en: "achievement", fa: "دستاورد" },
  { id: 300068, level: "B1", pos: "idiom", en: "actions speak louder than words", fa: "عمل مهم‌تر از حرف است" },
  { id: 100104, level: "B1", pos: "verb", en: "advise", fa: "توصیه کردن" },
  { id: 100141, level: "B1", pos: "noun", en: "alarm", fa: "زنگ خطر" },
  { id: 100179, level: "B1", pos: "noun", en: "ambition", fa: "جاه طلبی" },
  { id: 100180, level: "B1", pos: "adjective", en: "ambitious", fa: "جاه طلب" },
  { id: 100207, level: "B1", pos: "adjective", en: "annoyed", fa: "آزرده" },
  { id: 100208, level: "B1", pos: "adjective", en: "annoying", fa: "آزار دهنده" },
  { id: 100226, level: "B1", pos: "verb", en: "apologize", fa: "عذرخواهی کردن" },
  { id: 100244, level: "B1", pos: "noun", en: "appointment", fa: "قرار ملاقات" },
  { id: 100245, level: "B1", pos: "verb", en: "appreciate", fa: "قدردانی کردن" },
  { id: 400006, level: "B1", pos: "slang", en: "bestie", fa: "بهترین دوست" },
  { id: 400003, level: "B1", pos: "slang", en: "bet", fa: "قبوله، باشه" },
  { id: 300069, level: "B1", pos: "idiom", en: "better late than never", fa: "دیر رسیدن بهتر از هرگز نرسیدن است" },
  { id: 300053, level: "B1", pos: "idiom", en: "bite the bullet", fa: "دندان روی جگر گذاشتن" },
  { id: 300054, level: "B1", pos: "idiom", en: "break a leg", fa: "موفق باشی (پیش از اجرا)" },
  { id: 300036, level: "B1", pos: "idiom", en: "break the ice", fa: "یخ را باز کردن (شروع صمیمانه‌ی گفتگو)" },
  { id: 300052, level: "B1", pos: "idiom", en: "call it a day", fa: "کار را برای امروز تمام کردن" },
  { id: 100848, level: "B1", pos: "noun", en: "complaint", fa: "شکایت" },
  { id: 100892, level: "B1", pos: "adjective", en: "confident", fa: "مطمئن" },
  { id: 100984, level: "B1", pos: "verb", en: "convince", fa: "متقاعد کردن" },
  { id: 300040, level: "B1", pos: "idiom", en: "cost an arm and a leg", fa: "خیلی گران بودن" },
  { id: 101103, level: "B1", pos: "noun", en: "custom", fa: "رسوم" },
  { id: 101247, level: "B1", pos: "adjective", en: "determined", fa: "مصمم" },
  { id: 101297, level: "B1", pos: "adjective", en: "disappointed", fa: "ناامید" },
  { id: 101487, level: "B1", pos: "adjective", en: "embarrassed", fa: "خجالت زده" },
  { id: 101488, level: "B1", pos: "adjective", en: "embarrassing", fa: "خجالت آور" },
  { id: 101515, level: "B1", pos: "verb", en: "encourage", fa: "تشویق کردن" },
  { id: 101530, level: "B1", pos: "adjective", en: "engaged", fa: "نامزد" },
  { id: 101740, level: "B1", pos: "noun", en: "favour", fa: "لطف" },
  { id: 400009, level: "B1", pos: "slang", en: "FOMO", fa: "ترس از جاماندن از یک تجربه یا خبر" },
  { id: 101949, level: "B1", pos: "noun", en: "generation", fa: "نسل" },
  { id: 101951, level: "B1", pos: "adjective", en: "generous", fa: "سخاوتمند" },
  { id: 300050, level: "B1", pos: "idiom", en: "get cold feet", fa: "از ترس جا زدن" },
  { id: 300055, level: "B1", pos: "idiom", en: "get out of hand", fa: "از کنترل خارج شدن" },
  { id: 300048, level: "B1", pos: "idiom", en: "give someone a hand", fa: "به کسی کمک کردن" },
  { id: 102010, level: "B1", pos: "adjective", en: "grateful", fa: "سپاسگزار" },
  { id: 300047, level: "B1", pos: "idiom", en: "hang in there", fa: "دوام بیاور، تسلیم نشو" },
  { id: 400005, level: "B1", pos: "slang", en: "hard pass", fa: "قاطعانه نه" },
  { id: 400002, level: "B1", pos: "slang", en: "highkey", fa: "کاملاً و آشکارا" },
  { id: 300041, level: "B1", pos: "idiom", en: "hit the sack", fa: "به رختخواب رفتن" },
  { id: 102149, level: "B1", pos: "adjective", en: "honest", fa: "صادق" },
  { id: 300056, level: "B1", pos: "idiom", en: "in the same boat", fa: "در شرایط مشابه بودن" },
  { id: 300045, level: "B1", pos: "idiom", en: "keep an eye on", fa: "مراقب چیزی یا کسی بودن" },
  { id: 300057, level: "B1", pos: "idiom", en: "keep your fingers crossed", fa: "برای موفقیت کسی آرزو کردن" },
  { id: 300051, level: "B1", pos: "idiom", en: "kill two birds with one stone", fa: "با یک تیر دو نشان زدن" },
  { id: 300058, level: "B1", pos: "idiom", en: "last but not least", fa: "آخر ولی نه کم‌اهمیت‌تر" },
  { id: 300046, level: "B1", pos: "idiom", en: "let the cat out of the bag", fa: "رازی را فاش کردن" },
  { id: 102622, level: "B1", pos: "adjective", en: "lonely", fa: "تنها" },
  { id: 400001, level: "B1", pos: "slang", en: "lowkey", fa: "تا حدی، بدون سروصدا" },
  { id: 300049, level: "B1", pos: "idiom", en: "make up your mind", fa: "تصمیم گرفتن" },
  { id: 102701, level: "B1", pos: "noun", en: "marriage", fa: "ازدواج" },
  { id: 4e5, level: "B1", pos: "slang", en: "no cap", fa: "جدی میگم، دروغ نیست" },
  { id: 300059, level: "B1", pos: "idiom", en: "on the fence", fa: "مردد و بی‌تصمیم" },
  { id: 300044, level: "B1", pos: "idiom", en: "on the same page", fa: "هم‌فکر بودن" },
  { id: 300039, level: "B1", pos: "idiom", en: "once in a blue moon", fa: "خیلی به‌ندرت" },
  { id: 103219, level: "B1", pos: "verb", en: "persuade", fa: "متقاعد کردن" },
  { id: 300037, level: "B1", pos: "idiom", en: "piece of cake", fa: "کار آسان" },
  { id: 300070, level: "B1", pos: "idiom", en: "practice makes perfect", fa: "تمرین باعث تسلط می‌شود" },
  { id: 103476, level: "B1", pos: "adjective", en: "proud", fa: "مغرور" },
  { id: 300060, level: "B1", pos: "idiom", en: "pull yourself together", fa: "خودت را جمع‌وجور کن" },
  { id: 103497, level: "B1", pos: "verb", en: "punish", fa: "تنبیه کردن" },
  { id: 103498, level: "B1", pos: "noun", en: "punishment", fa: "تنبیه" },
  { id: 103603, level: "B1", pos: "noun", en: "recommendation", fa: "توصیه" },
  { id: 103651, level: "B1", pos: "adjective", en: "relative", fa: "نسبی" },
  { id: 103655, level: "B1", pos: "adjective", en: "relaxing", fa: "آرام بخش" },
  { id: 103676, level: "B1", pos: "verb", en: "remind", fa: "یادآوری کردن" },
  { id: 103710, level: "B1", pos: "noun", en: "reservation", fa: "رزرو" },
  { id: 103725, level: "B1", pos: "noun", en: "respect", fa: "احترام" },
  { id: 103743, level: "B1", pos: "verb", en: "retire", fa: "بازنشسته شدن" },
  { id: 103791, level: "B1", pos: "adjective", en: "romantic", fa: "عاشقانه" },
  { id: 400004, level: "B1", pos: "slang", en: "say less", fa: "قبوله، بیشتر توضیح نده" },
  { id: 300043, level: "B1", pos: "idiom", en: "see eye to eye", fa: "هم‌نظر بودن" },
  { id: 103994, level: "B1", pos: "adjective", en: "shy", fa: "خجالتی" },
  { id: 400007, level: "B1", pos: "slang", en: "slay", fa: "عالی انجام دادن کاری" },
  { id: 300042, level: "B1", pos: "idiom", en: "speak of the devil", fa: "حلال‌زاده" },
  { id: 300061, level: "B1", pos: "idiom", en: "speak your mind", fa: "نظرت را رک بگو" },
  { id: 300062, level: "B1", pos: "idiom", en: "take it easy", fa: "سخت نگیر، آرام باش" },
  { id: 300063, level: "B1", pos: "idiom", en: "the ball is in your court", fa: "نوبت تصمیم‌گیری با توست" },
  { id: 300064, level: "B1", pos: "idiom", en: "time flies", fa: "زمان زود می‌گذرد" },
  { id: 300065, level: "B1", pos: "idiom", en: "under the table", fa: "زیرمیزی، غیرقانونی" },
  { id: 300038, level: "B1", pos: "idiom", en: "under the weather", fa: "کسل و بی‌حال" },
  { id: 400008, level: "B1", pos: "slang", en: "vibe", fa: "حس و حال کلی" },
  { id: 104806, level: "B1", pos: "verb", en: "warn", fa: "هشدار دادن" },
  { id: 104807, level: "B1", pos: "noun", en: "warning", fa: "هشدار" },
  { id: 300066, level: "B1", pos: "idiom", en: "word of mouth", fa: "شهرت دهان‌به‌دهان" },
  { id: 300089, level: "B2", pos: "idiom", en: "against the clock", fa: "در رقابت با زمان" },
  { id: 100192, level: "B2", pos: "noun", en: "ancestor", fa: "جد" },
  { id: 100227, level: "B2", pos: "noun", en: "apology", fa: "عذرخواهی" },
  { id: 100286, level: "B2", pos: "adjective", en: "ashamed", fa: "شرمنده" },
  { id: 100359, level: "B2", pos: "adjective", en: "awkward", fa: "ناخوشایند" },
  { id: 300090, level: "B2", pos: "idiom", en: "back to square one", fa: "برگشتن به نقطه‌ی شروع" },
  { id: 400026, level: "B2", pos: "slang", en: "basic", fa: "معمولی و بدون خلاقیت" },
  { id: 300091, level: "B2", pos: "idiom", en: "beat around the bush", fa: "به‌جای رک گفتن حاشیه رفتن" },
  { id: 300092, level: "B2", pos: "idiom", en: "behind the scenes", fa: "پشت‌صحنه" },
  { id: 300071, level: "B2", pos: "idiom", en: "bite off more than you can chew", fa: "لقمه بزرگ‌تر از دهان برداشتن" },
  { id: 100479, level: "B2", pos: "noun", en: "blame", fa: "سرزنش" },
  { id: 100502, level: "B2", pos: "noun", en: "bond", fa: "پیوند" },
  { id: 300072, level: "B2", pos: "idiom", en: "burn the midnight oil", fa: "تا نیمه‌شب کار یا درس خواندن" },
  { id: 300093, level: "B2", pos: "idiom", en: "by all means", fa: "حتماً، با کمال میل" },
  { id: 100606, level: "B2", pos: "verb", en: "cancel", fa: "لغو کردن" },
  { id: 400019, level: "B2", pos: "slang", en: "cap", fa: "دروغ" },
  { id: 400017, level: "B2", pos: "slang", en: "catch feelings", fa: "ناخواسته احساسات عاشقانه پیدا کردن" },
  { id: 300094, level: "B2", pos: "idiom", en: "come to terms with", fa: "با چیزی کنار آمدن" },
  { id: 100806, level: "B2", pos: "noun", en: "comfort", fa: "آسایش" },
  { id: 100891, level: "B2", pos: "noun", en: "confidence", fa: "اعتماد به نفس" },
  { id: 300073, level: "B2", pos: "idiom", en: "cut corners", fa: "کیفیت کار را فدای سرعت کردن" },
  { id: 400010, level: "B2", pos: "slang", en: "deadass", fa: "جدی جدی، بدون شوخی" },
  { id: 101185, level: "B2", pos: "adjective", en: "delighted", fa: "خوشحال" },
  { id: 101205, level: "B2", pos: "adjective", en: "dependent", fa: "وابسته" },
  { id: 101245, level: "B2", pos: "noun", en: "determination", fa: "عزم" },
  { id: 101294, level: "B2", pos: "noun", en: "disagreement", fa: "اختلاف نظر" },
  { id: 101299, level: "B2", pos: "noun", en: "disappointment", fa: "ناامیدی" },
  { id: 101305, level: "B2", pos: "noun", en: "discipline", fa: "انضباط" },
  { id: 101309, level: "B2", pos: "verb", en: "discourage", fa: "دلسرد کردن" },
  { id: 101319, level: "B2", pos: "adjective", en: "dishonest", fa: "دوروغ" },
  { id: 101354, level: "B2", pos: "noun", en: "divorce", fa: "طلاق" },
  { id: 300095, level: "B2", pos: "idiom", en: "draw the line", fa: "حد و مرز تعیین کردن" },
  { id: 101465, level: "B2", pos: "adjective", en: "elderly", fa: "سالمند" },
  { id: 101638, level: "B2", pos: "noun", en: "excuse", fa: "بهانه" },
  { id: 400011, level: "B2", pos: "slang", en: "extra", fa: "اغراق‌آمیز و پرسروصدا" },
  { id: 400012, level: "B2", pos: "slang", en: "flex", fa: "به رخ کشیدن، فخرفروشی" },
  { id: 101847, level: "B2", pos: "verb", en: "forgive", fa: "بخشیدن" },
  { id: 400028, level: "B2", pos: "slang", en: "get a W", fa: "برنده شدن" },
  { id: 300074, level: "B2", pos: "idiom", en: "get the ball rolling", fa: "کاری را شروع کردن" },
  { id: 300096, level: "B2", pos: "idiom", en: "get the hang of", fa: "دستگیرت شدن، یاد گرفتن" },
  { id: 400014, level: "B2", pos: "slang", en: "ghost someone", fa: "بدون خداحافظی ارتباط را قطع کردن" },
  { id: 400015, level: "B2", pos: "slang", en: "ghosted", fa: "کسی که بی‌خبر رهایش کرده‌اند" },
  { id: 400013, level: "B2", pos: "slang", en: "glow up", fa: "تغییر ظاهری مثبت و چشمگیر" },
  { id: 300097, level: "B2", pos: "idiom", en: "go back on your word", fa: "زیر قول‌ات زدن" },
  { id: 300075, level: "B2", pos: "idiom", en: "go the extra mile", fa: "فراتر از انتظار تلاش کردن" },
  { id: 400024, level: "B2", pos: "slang", en: "go viral", fa: "به‌سرعت در فضای مجازی پخش شدن" },
  { id: 102024, level: "B2", pos: "noun", en: "grocery", fa: "خواربار" },
  { id: 102114, level: "B2", pos: "verb", en: "hesitate", fa: "تردید کردن" },
  { id: 300076, level: "B2", pos: "idiom", en: "hit the nail on the head", fa: "دقیقاً درست گفتن" },
  { id: 102150, level: "B2", pos: "noun", en: "honesty", fa: "صداقت" },
  { id: 400025, level: "B2", pos: "slang", en: "iconic", fa: "فراموش‌نشدنی و خاص" },
  { id: 102228, level: "B2", pos: "adjective", en: "impatient", fa: "بی صبر" },
  { id: 300098, level: "B2", pos: "idiom", en: "in the long run", fa: "در درازمدت" },
  { id: 102268, level: "B2", pos: "noun", en: "independence", fa: "استقلال" },
  { id: 102330, level: "B2", pos: "verb", en: "insist", fa: "اصرار کردن" },
  { id: 300077, level: "B2", pos: "idiom", en: "jump on the bandwagon", fa: "دنباله‌روِ یک روند شدن" },
  { id: 300099, level: "B2", pos: "idiom", en: "keep your chin up", fa: "روحیه‌ات را حفظ کن" },
  { id: 300078, level: "B2", pos: "idiom", en: "learn the ropes", fa: "کار را یاد گرفتن" },
  { id: 400016, level: "B2", pos: "slang", en: "left on read", fa: "پیامی که خوانده شده ولی بی‌جواب مانده" },
  { id: 300100, level: "B2", pos: "idiom", en: "make ends meet", fa: "دخل و خرج را جور کردن" },
  { id: 300079, level: "B2", pos: "idiom", en: "miss the boat", fa: "فرصت را از دست دادن" },
  { id: 102845, level: "B2", pos: "noun", en: "mosque", fa: "مسجد" },
  { id: 102850, level: "B2", pos: "verb", en: "motivate", fa: "انگیزه دادن" },
  { id: 102851, level: "B2", pos: "noun", en: "motivation", fa: "انگیزه" },
  { id: 300101, level: "B2", pos: "idiom", en: "off the top of my head", fa: "همین‌طور از ذهنم، بدون فکر دقیق" },
  { id: 300080, level: "B2", pos: "idiom", en: "on thin ice", fa: "در موقعیت خطرناک بودن" },
  { id: 300102, level: "B2", pos: "idiom", en: "out of the blue", fa: "کاملاً غیرمنتظره" },
  { id: 103111, level: "B2", pos: "verb", en: "owe", fa: "بدهکار بودن" },
  { id: 103175, level: "B2", pos: "noun", en: "patience", fa: "صبر" },
  { id: 103193, level: "B2", pos: "noun", en: "pension", fa: "بازنشستگی" },
  { id: 103390, level: "B2", pos: "noun", en: "pride", fa: "افتخار" },
  { id: 103460, level: "B2", pos: "noun", en: "proposal", fa: "پیشنهاد" },
  { id: 103461, level: "B2", pos: "verb", en: "propose", fa: "پیشنهاد کردن" },
  { id: 300081, level: "B2", pos: "idiom", en: "put all your eggs in one basket", fa: "همه‌چیز را روی یک گزینه شرط بستن" },
  { id: 300103, level: "B2", pos: "idiom", en: "read between the lines", fa: "منظور پنهان را فهمیدن" },
  { id: 103635, level: "B2", pos: "noun", en: "regret", fa: "پشیمانی" },
  { id: 103661, level: "B2", pos: "noun", en: "relief", fa: "آسودگی" },
  { id: 103663, level: "B2", pos: "adjective", en: "relieved", fa: "آسوده" },
  { id: 103745, level: "B2", pos: "noun", en: "retirement", fa: "بازنشستگی" },
  { id: 103761, level: "B2", pos: "noun", en: "reward", fa: "پاداش" },
  { id: 300082, level: "B2", pos: "idiom", en: "rock the boat", fa: "اوضاع آرام را به‌هم زدن" },
  { id: 103790, level: "B2", pos: "noun", en: "romance", fa: "عاشقانه" },
  { id: 400020, level: "B2", pos: "slang", en: "salty", fa: "از دست کسی دلخور و کینه‌ای" },
  { id: 300083, level: "B2", pos: "idiom", en: "see the light at the end of the tunnel", fa: "امید به پایان مشکلات داشتن" },
  { id: 103951, level: "B2", pos: "noun", en: "shame", fa: "شرم" },
  { id: 103995, level: "B2", pos: "noun", en: "sibling", fa: "خواهر یا برادر" },
  { id: 300084, level: "B2", pos: "idiom", en: "spill the beans", fa: "رازی را لو دادن" },
  { id: 400022, level: "B2", pos: "slang", en: "spill the tea", fa: "آخرین خبرها یا شایعات را گفتن" },
  { id: 104160, level: "B2", pos: "verb", en: "spoil", fa: "خراب کردن" },
  { id: 300104, level: "B2", pos: "idiom", en: "stick to your guns", fa: "روی حرفت پافشاری کردن" },
  { id: 104246, level: "B2", pos: "adjective", en: "strict", fa: "سختگیرانه" },
  { id: 400018, level: "B2", pos: "slang", en: "sus", fa: "مشکوک" },
  { id: 104368, level: "B2", pos: "adjective", en: "sympathetic", fa: "همدل" },
  { id: 104369, level: "B2", pos: "noun", en: "sympathy", fa: "همدردی" },
  { id: 400027, level: "B2", pos: "slang", en: "take an L", fa: "شکست خوردن" },
  { id: 300105, level: "B2", pos: "idiom", en: "take something with a grain of salt", fa: "با احتیاط باور کردن" },
  { id: 300085, level: "B2", pos: "idiom", en: "the tip of the iceberg", fa: "بخش کوچکی از یک مشکل بزرگ" },
  { id: 300086, level: "B2", pos: "idiom", en: "throw in the towel", fa: "تسلیم شدن" },
  { id: 400021, level: "B2", pos: "slang", en: "throw shade", fa: "پشت سر کسی حرف زدن، تحقیر ظریف" },
  { id: 104622, level: "B2", pos: "noun", en: "trust", fa: "اعتماد" },
  { id: 300087, level: "B2", pos: "idiom", en: "turn a blind eye", fa: "تعمداً چشم‌پوشی کردن" },
  { id: 400023, level: "B2", pos: "slang", en: "vibe check", fa: "بررسی حس‌وحال یا انرژی یک موقعیت" },
  { id: 300088, level: "B2", pos: "idiom", en: "weather the storm", fa: "از یک بحران سربلند بیرون آمدن" },
  { id: 300106, level: "C1", pos: "idiom", en: "a drop in the ocean", fa: "قطره‌ای در دریا، ناچیز" },
  { id: 100033, level: "C1", pos: "noun", en: "accomplishment", fa: "دستاورد" },
  { id: 300107, level: "C1", pos: "idiom", en: "add insult to injury", fa: "نمک روی زخم پاشیدن" },
  { id: 100091, level: "C1", pos: "noun", en: "adolescent", fa: "نوجوان" },
  { id: 300108, level: "C1", pos: "idiom", en: "bark up the wrong tree", fa: "دنبال سرنخ اشتباه بودن" },
  { id: 300109, level: "C1", pos: "idiom", en: "beat a dead horse", fa: "وقت تلف کردن روی چیز تمام‌شده" },
  { id: 100452, level: "C1", pos: "verb", en: "betray", fa: "خیانت کردن" },
  { id: 400044, level: "C1", pos: "slang", en: "big yikes", fa: "وای چه ضایع" },
  { id: 300110, level: "C1", pos: "idiom", en: "burn bridges", fa: "پل‌های پشت سر را خراب کردن" },
  { id: 400038, level: "C1", pos: "slang", en: "cancel culture", fa: "فرهنگ طرد عمومی افراد به‌خاطر اشتباهاتشان" },
  { id: 400039, level: "C1", pos: "slang", en: "canceled", fa: "طردشده به‌خاطر یک جنجال" },
  { id: 400043, level: "C1", pos: "slang", en: "clickbait", fa: "عنوان فریبنده برای جذب کلیک" },
  { id: 300111, level: "C1", pos: "idiom", en: "close but no cigar", fa: "نزدیک بود ولی نشد" },
  { id: 400040, level: "C1", pos: "slang", en: "clout", fa: "محبوبیت و نفوذ اجتماعی" },
  { id: 400041, level: "C1", pos: "slang", en: "clout chasing", fa: "دنبال محبوبیت و توجه بودن" },
  { id: 100866, level: "C1", pos: "noun", en: "compromise", fa: "سازش" },
  { id: 101039, level: "C1", pos: "noun", en: "courtesy", fa: "ادب" },
  { id: 101081, level: "C1", pos: "verb", en: "crush", fa: "خرد کردن" },
  { id: 101102, level: "C1", pos: "noun", en: "custody", fa: "بازداشت" },
  { id: 300112, level: "C1", pos: "idiom", en: "cut to the chase", fa: "برو سر اصل مطلب" },
  { id: 300113, level: "C1", pos: "idiom", en: "devil's advocate", fa: "مدافع عمدیِ نظر مخالف" },
  { id: 101516, level: "C1", pos: "noun", en: "encouragement", fa: "تشویق" },
  { id: 101531, level: "C1", pos: "noun", en: "engagement", fa: "نامزدی" },
  { id: 300140, level: "C1", pos: "idiom", en: "food for thought", fa: "چیزی که به فکر کردن وامی‌دارد" },
  { id: 101902, level: "C1", pos: "adjective", en: "frustrated", fa: "ناامید" },
  { id: 101903, level: "C1", pos: "adjective", en: "frustrating", fa: "ناامید کننده" },
  { id: 400037, level: "C1", pos: "slang", en: "gaslight", fa: "با دروغ، کسی را نسبت به واقعیت خودش دچار شک کردن" },
  { id: 300114, level: "C1", pos: "idiom", en: "get a taste of your own medicine", fa: "تاوان کار خودت را پس دادن" },
  { id: 300115, level: "C1", pos: "idiom", en: "go down in flames", fa: "با شکست فاحش تمام شدن" },
  { id: 102110, level: "C1", pos: "noun", en: "heritage", fa: "میراث" },
  { id: 300116, level: "C1", pos: "idiom", en: "hit close to home", fa: "به دل نشستن، شخصی بودن موضوع" },
  { id: 400034, level: "C1", pos: "slang", en: "hits different", fa: "حس متفاوت و خاصی دارد" },
  { id: 300117, level: "C1", pos: "idiom", en: "in the heat of the moment", fa: "در اوج هیجان لحظه" },
  { id: 102394, level: "C1", pos: "adjective", en: "intimate", fa: "صمیمی" },
  { id: 400031, level: "C1", pos: "slang", en: "it's giving", fa: "حس یا فضای ... را دارد" },
  { id: 300118, level: "C1", pos: "idiom", en: "jump the gun", fa: "زودتر از موقع اقدام کردن" },
  { id: 300119, level: "C1", pos: "idiom", en: "keep something at bay", fa: "چیزی را دور نگه داشتن" },
  { id: 300120, level: "C1", pos: "idiom", en: "know the ropes", fa: "کاملاً به کاری مسلط بودن" },
  { id: 400033, level: "C1", pos: "slang", en: "living rent free", fa: "فکر کردن مداوم و ناخواسته به یک چیز" },
  { id: 400032, level: "C1", pos: "slang", en: "main character energy", fa: "رفتار مثل شخصیت اصلی داستان زندگی خود" },
  { id: 300121, level: "C1", pos: "idiom", en: "make a mountain out of a molehill", fa: "از کاه کوه ساختن" },
  { id: 102718, level: "C1", pos: "adjective", en: "mature", fa: "بالغ" },
  { id: 300122, level: "C1", pos: "idiom", en: "on the ball", fa: "هوشیار و آماده" },
  { id: 300123, level: "C1", pos: "idiom", en: "par for the course", fa: "چیزی که انتظارش می‌رفت" },
  { id: 103320, level: "C1", pos: "verb", en: "postpone", fa: "به تعویق انداختن" },
  { id: 103355, level: "C1", pos: "noun", en: "prejudice", fa: "پیش داوری" },
  { id: 300124, level: "C1", pos: "idiom", en: "push the envelope", fa: "فراتر از حد معمول رفتن" },
  { id: 300125, level: "C1", pos: "idiom", en: "rain check", fa: "به‌تعویق‌انداختن دعوت" },
  { id: 400042, level: "C1", pos: "slang", en: "ratio", fa: "وقتی واکنش به یک پست بیشتر از خود پست توجه می‌گیرد" },
  { id: 300126, level: "C1", pos: "idiom", en: "read the room", fa: "حس‌وحال جمع را درک کردن" },
  { id: 103585, level: "C1", pos: "verb", en: "reassure", fa: "اطمینان دادن" },
  { id: 400030, level: "C1", pos: "slang", en: "receipts", fa: "مدرک یا سند برای اثبات حرف" },
  { id: 103666, level: "C1", pos: "adjective", en: "reluctant", fa: "متردد" },
  { id: 103677, level: "C1", pos: "noun", en: "reminder", fa: "یادآوری" },
  { id: 400036, level: "C1", pos: "slang", en: "rizz", fa: "جذابیت و مهارت در فلرت کردن" },
  { id: 300127, level: "C1", pos: "idiom", en: "rule of thumb", fa: "قاعده‌ی کلی و تقریبی" },
  { id: 103919, level: "C1", pos: "noun", en: "separation", fa: "جدایی" },
  { id: 300128, level: "C1", pos: "idiom", en: "shot in the dark", fa: "حدس کورکورانه" },
  { id: 400029, level: "C1", pos: "slang", en: "simp", fa: "کسی که بیش‌ازحد برای جلب توجه کسی تلاش می‌کند" },
  { id: 300129, level: "C1", pos: "idiom", en: "sit tight", fa: "صبر کن و کاری نکن" },
  { id: 104216, level: "C1", pos: "noun", en: "stereotype", fa: "کلیشه" },
  { id: 300130, level: "C1", pos: "idiom", en: "take the bull by the horns", fa: "با شجاعت با مشکل روبه‌رو شدن" },
  { id: 300131, level: "C1", pos: "idiom", en: "the elephant in the room", fa: "مشکل واضحی که کسی درباره‌اش حرف نمی‌زند" },
  { id: 104497, level: "C1", pos: "adjective", en: "thrilled", fa: "هیجان زده" },
  { id: 300132, level: "C1", pos: "idiom", en: "throw someone under the bus", fa: "کسی را قربانی کردن برای فرار از تقصیر" },
  { id: 300133, level: "C1", pos: "idiom", en: "to each their own", fa: "هر کس سلیقه‌ی خودش را دارد" },
  { id: 104529, level: "C1", pos: "noun", en: "tolerance", fa: "تحمل" },
  { id: 400035, level: "C1", pos: "slang", en: "touch grass", fa: "از دنیای مجازی بیرون آمدن، به واقعیت برگشتن" },
  { id: 300134, level: "C1", pos: "idiom", en: "turn the tables", fa: "ورق را برگرداندن" },
  { id: 300135, level: "C1", pos: "idiom", en: "up in the air", fa: "نامشخص و تصمیم‌نگرفته" },
  { id: 300136, level: "C1", pos: "idiom", en: "water under the bridge", fa: "گذشته‌ها گذشته" },
  { id: 300137, level: "C1", pos: "idiom", en: "when pigs fly", fa: "هرگز، وقت گل نی" },
  { id: 300138, level: "C1", pos: "idiom", en: "with flying colors", fa: "با موفقیت کامل" },
  { id: 300139, level: "C1", pos: "idiom", en: "your guess is as good as mine", fa: "من هم به‌اندازه‌ی تو نمی‌دانم" },
  { id: 300169, level: "C2", pos: "idiom", en: "add fuel to the fire", fa: "آتش را شعله‌ورتر کردن" },
  { id: 300141, level: "C2", pos: "idiom", en: "an axe to grind", fa: "منافع شخصی پنهان داشتن" },
  { id: 300142, level: "C2", pos: "idiom", en: "as luck would have it", fa: "از قضای روزگار" },
  { id: 300143, level: "C2", pos: "idiom", en: "at loggerheads", fa: "در تضاد شدید بودن" },
  { id: 300170, level: "C2", pos: "idiom", en: "be at someone's beck and call", fa: "همیشه در خدمت کسی بودن" },
  { id: 300171, level: "C2", pos: "idiom", en: "be in someone's good books", fa: "مورد لطف کسی بودن" },
  { id: 300144, level: "C2", pos: "idiom", en: "bite the hand that feeds you", fa: "نمک‌نشناسی کردن" },
  { id: 300172, level: "C2", pos: "idiom", en: "bite your tongue", fa: "جلوی زبانت را گرفتن، سکوت کردن" },
  { id: 300173, level: "C2", pos: "idiom", en: "break new ground", fa: "کار نوآورانه و تازه انجام دادن" },
  { id: 300145, level: "C2", pos: "idiom", en: "burn the candle at both ends", fa: "بیش از حد و بدون استراحت کار کردن" },
  { id: 300146, level: "C2", pos: "idiom", en: "come rain or shine", fa: "در هر شرایطی" },
  { id: 300174, level: "C2", pos: "idiom", en: "come to a head", fa: "به نقطه‌ی بحرانی رسیدن" },
  { id: 300147, level: "C2", pos: "idiom", en: "cross that bridge when you come to it", fa: "به‌موقعش به مشکل فکر می‌کنیم" },
  { id: 300175, level: "C2", pos: "idiom", en: "cut someone some slack", fa: "به کسی سخت نگرفتن" },
  { id: 400045, level: "C2", pos: "slang", en: "delulu", fa: "خیالاتی، در توهم به سر بردن" },
  { id: 400048, level: "C2", pos: "slang", en: "doomscrolling", fa: "بی‌وقفه اسکرول‌کردن اخبار بد" },
  { id: 400050, level: "C2", pos: "slang", en: "extra af", fa: "بیش از حد اغراق‌آمیز" },
  { id: 300148, level: "C2", pos: "idiom", en: "fall by the wayside", fa: "به فراموشی سپرده شدن" },
  { id: 400049, level: "C2", pos: "slang", en: "flex on someone", fa: "به کسی فخر فروختن" },
  { id: 300176, level: "C2", pos: "idiom", en: "get the short end of the stick", fa: "سهم ناعادلانه و کمتری گرفتن" },
  { id: 300149, level: "C2", pos: "idiom", en: "get your ducks in a row", fa: "همه‌چیز را منظم و آماده کردن" },
  { id: 300150, level: "C2", pos: "idiom", en: "give someone the benefit of the doubt", fa: "به کسی حسن ظن داشتن" },
  { id: 300177, level: "C2", pos: "idiom", en: "go down a rabbit hole", fa: "غرق شدن در موضوعی پیچیده و بی‌پایان" },
  { id: 300178, level: "C2", pos: "idiom", en: "have a chip on your shoulder", fa: "کینه یا رنجش قدیمی داشتن" },
  { id: 300151, level: "C2", pos: "idiom", en: "hedge your bets", fa: "با چند گزینه ریسک را کم کردن" },
  { id: 300152, level: "C2", pos: "idiom", en: "hold your horses", fa: "عجله نکن" },
  { id: 400046, level: "C2", pos: "slang", en: "ick", fa: "حس ناگهانی بی‌میلی نسبت به کسی" },
  { id: 300153, level: "C2", pos: "idiom", en: "ignorance is bliss", fa: "ندانستن گاهی نعمت است" },
  { id: 300154, level: "C2", pos: "idiom", en: "in the same breath", fa: "همزمان و بدون فاصله در صحبت" },
  { id: 400047, level: "C2", pos: "slang", en: "JOMO", fa: "لذت بردن از جاماندن، برخلاف FOMO" },
  { id: 300179, level: "C2", pos: "idiom", en: "keep something under wraps", fa: "چیزی را مخفی نگه داشتن" },
  { id: 300155, level: "C2", pos: "idiom", en: "leave no stone unturned", fa: "تمام تلاش خود را کردن" },
  { id: 300156, level: "C2", pos: "idiom", en: "let sleeping dogs lie", fa: "دنبال دردسر نگرد" },
  { id: 300180, level: "C2", pos: "idiom", en: "make a scene", fa: "جنجال و سروصدا راه انداختن" },
  { id: 300157, level: "C2", pos: "idiom", en: "move the goalposts", fa: "قوانین بازی را وسط کار عوض کردن" },
  { id: 300158, level: "C2", pos: "idiom", en: "once bitten, twice shy", fa: "مارگزیده از ریسمان سیاه و سفید می‌ترسد" },
  { id: 300159, level: "C2", pos: "idiom", en: "pass the buck", fa: "مسئولیت را گردن دیگری انداختن" },
  { id: 300181, level: "C2", pos: "idiom", en: "play it by ear", fa: "بدون برنامه‌ی از پیش، بداهه عمل کردن" },
  { id: 300160, level: "C2", pos: "idiom", en: "pull strings", fa: "از نفوذ خود استفاده کردن" },
  { id: 300161, level: "C2", pos: "idiom", en: "put the cart before the horse", fa: "کارها را نامرتب و برعکس انجام دادن" },
  { id: 300182, level: "C2", pos: "idiom", en: "put your foot in your mouth", fa: "سوتی دادن، حرف نامناسب زدن" },
  { id: 300183, level: "C2", pos: "idiom", en: "read someone like a book", fa: "کاملاً کسی را شناختن" },
  { id: 300162, level: "C2", pos: "idiom", en: "see the writing on the wall", fa: "نشانه‌های واضح یک اتفاق بد را دیدن" },
  { id: 300163, level: "C2", pos: "idiom", en: "separate the wheat from the chaff", fa: "خوب را از بد تشخیص دادن" },
  { id: 300164, level: "C2", pos: "idiom", en: "steal someone's thunder", fa: "افتخار زحمت کسی دیگر را بردن" },
  { id: 300165, level: "C2", pos: "idiom", en: "take something at face value", fa: "چیزی را همان‌طور که هست پذیرفتن" },
  { id: 300166, level: "C2", pos: "idiom", en: "the best of both worlds", fa: "داشتن مزایای هر دو طرف" },
  { id: 300167, level: "C2", pos: "idiom", en: "the last straw", fa: "آخرین ضربه‌ای که صبر را لبریز می‌کند" },
  { id: 300168, level: "C2", pos: "idiom", en: "through thick and thin", fa: "در خوشی و ناخوشی، همیشه" }
];
