export const NEWS_WORDS = [
  { id: 100062, level: "C1", pos: "noun", en: "activist", fa: "فعال" },
  { id: 100128, level: "B1", pos: "noun", en: "agreement", fa: "توافق" },
  { id: 100133, level: "B2", pos: "noun", en: "aid", fa: "کمک" },
  { id: 100157, level: "C1", pos: "noun", en: "alliance", fa: "اتحاد" },
  { id: 100178, level: "C1", pos: "noun", en: "ambassador", fa: "سفیر" },
  { id: 100183, level: "C1", pos: "noun", en: "amendment", fa: "اصلاحیه" },
  { id: 100204, level: "B1", pos: "verb", en: "announce", fa: "اعلام کردن" },
  { id: 100205, level: "B1", pos: "noun", en: "announcement", fa: "اعلامیه" },
  { id: 100268, level: "A2", pos: "noun", en: "army", fa: "ارتش" },
  { id: 100273, level: "B1", pos: "noun", en: "arrest", fa: "دستگیری" },
  { id: 100322, level: "A2", pos: "noun", en: "attack", fa: "حمله" },
  { id: 100342, level: "B1", pos: "noun", en: "authority", fa: "مرجع" },
  { id: 100383, level: "A1", pos: "noun", en: "bank", fa: "بانک" },
  { id: 100405, level: "B1", pos: "noun", en: "battle", fa: "نبرد" },
  { id: 100461, level: "A1", pos: "noun", en: "bill", fa: "صورتحساب" },
  { id: 100500, level: "B1", pos: "noun", en: "bomb", fa: "بمب" },
  { id: 100510, level: "B1", pos: "noun", en: "border", fa: "مرز" },
  { id: 100565, level: "B2", pos: "noun", en: "budget", fa: "بودجه" },
  { id: 100581, level: "A1", pos: "noun", en: "business", fa: "کسب و کار" },
  { id: 100601, level: "B1", pos: "noun", en: "campaign", fa: "کارزار" },
  { id: 100608, level: "B1", pos: "noun", en: "candidate", fa: "نامزد" },
  { id: 100616, level: "A1", pos: "adjective", en: "capital", fa: "سرمایه" },
  { id: 100622, level: "B2", pos: "noun", en: "carbon", fa: "کربن" },
  { id: 100642, level: "C1", pos: "noun", en: "casualty", fa: "تلفات" },
  { id: 100687, level: "A2", pos: "noun", en: "charity", fa: "خیریه" },
  { id: 100717, level: "A2", pos: "noun", en: "church", fa: "کلیسا" },
  { id: 100728, level: "A1", pos: "noun", en: "city", fa: "شهر" },
  { id: 100752, level: "A2", pos: "noun", en: "climate", fa: "آب و هوا" },
  { id: 100772, level: "C1", pos: "noun", en: "coalition", fa: "ائتلاف" },
  { id: 100821, level: "B2", pos: "noun", en: "committee", fa: "کمیته" },
  { id: 100828, level: "A2", pos: "noun", en: "community", fa: "جامعه" },
  { id: 100830, level: "A1", pos: "noun", en: "company", fa: "شرکت" },
  { id: 100897, level: "B2", pos: "noun", en: "conflict", fa: "درگیری" },
  { id: 100919, level: "B2", pos: "noun", en: "conservation", fa: "حفاظت" },
  { id: 100936, level: "C1", pos: "noun", en: "constitution", fa: "قانون اساسی" },
  { id: 100945, level: "B1", pos: "noun", en: "consumer", fa: "مصرف کننده" },
  { id: 101004, level: "B2", pos: "noun", en: "corporation", fa: "شرکت" },
  { id: 101016, level: "C1", pos: "noun", en: "corruption", fa: "فساد" },
  { id: 101017, level: "A1", pos: "noun", en: "cost", fa: "هزینه" },
  { id: 101023, level: "B2", pos: "noun", en: "council", fa: "شورا" },
  { id: 101031, level: "A1", pos: "noun", en: "country", fa: "کشور" },
  { id: 101034, level: "C1", pos: "noun", en: "coup", fa: "کودتا" },
  { id: 101038, level: "B1", pos: "noun", en: "court", fa: "دادگاه" },
  { id: 101062, level: "A2", pos: "noun", en: "crime", fa: "جرم" },
  { id: 101063, level: "A2", pos: "noun", en: "criminal", fa: "مجرم" },
  { id: 101064, level: "B2", pos: "noun", en: "crisis", fa: "بحران" },
  { id: 101088, level: "A1", pos: "noun", en: "culture", fa: "فرهنگ" },
  { id: 101095, level: "B1", pos: "noun", en: "currency", fa: "واحد پول" },
  { id: 101119, level: "A2", pos: "noun", en: "danger", fa: "خطر" },
  { id: 101124, level: "A2", pos: "noun", en: "data", fa: "داده" },
  { id: 101139, level: "B2", pos: "noun", en: "debt", fa: "بدهی" },
  { id: 101149, level: "C1", pos: "noun", en: "declaration", fa: "اعلامیه" },
  { id: 101150, level: "B2", pos: "verb", en: "declare", fa: "اعلام کردن" },
  { id: 101164, level: "B2", pos: "noun", en: "defence", fa: "دفاع" },
  { id: 101188, level: "B2", pos: "noun", en: "demand", fa: "تقاضا" },
  { id: 101189, level: "B2", pos: "noun", en: "democracy", fa: "دموکراسی" },
  { id: 101190, level: "B2", pos: "adjective", en: "democratic", fa: "دموکراتیک" },
  { id: 101193, level: "B2", pos: "noun", en: "demonstration", fa: "تظاهرات" },
  { id: 101250, level: "B1", pos: "noun", en: "development", fa: "توسعه" },
  { id: 101262, level: "C1", pos: "noun", en: "dictator", fa: "دیکتاتور" },
  { id: 101281, level: "C1", pos: "noun", en: "diplomat", fa: "دیپلمات" },
  { id: 101282, level: "C1", pos: "adjective", en: "diplomatic", fa: "دیپلماتیک" },
  { id: 101300, level: "A2", pos: "noun", en: "disaster", fa: "فاجعه" },
  { id: 101314, level: "C1", pos: "noun", en: "discrimination", fa: "تبعیض" },
  { id: 101317, level: "A2", pos: "noun", en: "disease", fa: "بیماری" },
  { id: 101357, level: "A1", pos: "noun", en: "doctor", fa: "دکتر" },
  { id: 101370, level: "B2", pos: "noun", en: "donation", fa: "کمک مالی" },
  { id: 101400, level: "B2", pos: "noun", en: "drought", fa: "خشکسالی" },
  { id: 101426, level: "B1", pos: "noun", en: "earthquake", fa: "زلزله" },
  { id: 101435, level: "B1", pos: "adjective", en: "economic", fa: "اقتصادی" },
  { id: 101437, level: "B2", pos: "noun", en: "economist", fa: "اقتصاددان" },
  { id: 101438, level: "B1", pos: "noun", en: "economy", fa: "اقتصاد" },
  { id: 101446, level: "A2", pos: "noun", en: "education", fa: "آموزش" },
  { id: 101466, level: "B2", pos: "verb", en: "elect", fa: "انتخاب کردن" },
  { id: 101467, level: "B1", pos: "noun", en: "election", fa: "انتخابات" },
  { id: 101490, level: "C1", pos: "noun", en: "embassy", fa: "سفارت" },
  { id: 101496, level: "B1", pos: "noun", en: "emergency", fa: "اضطراری" },
  { id: 101497, level: "B2", pos: "noun", en: "emission", fa: "انتشار" },
  { id: 101508, level: "B1", pos: "noun", en: "employment", fa: "اشتغال" },
  { id: 101526, level: "A2", pos: "noun", en: "energy", fa: "انرژی" },
  { id: 101563, level: "A2", pos: "noun", en: "environment", fa: "محیط زیست" },
  { id: 101564, level: "B1", pos: "adjective", en: "environmental", fa: "محیط زیستی" },
  { id: 101565, level: "C1", pos: "noun", en: "epidemic", fa: "همه گیری" },
  { id: 101568, level: "C1", pos: "noun", en: "equality", fa: "برابری" },
  { id: 101594, level: "C1", pos: "verb", en: "evacuate", fa: "تخلیه کردن" },
  { id: 101678, level: "B1", pos: "noun", en: "export", fa: "صادرات" },
  { id: 101704, level: "A2", pos: "noun", en: "factory", fa: "کارخانه" },
  { id: 101778, level: "B2", pos: "noun", en: "finance", fa: "مالی" },
  { id: 101779, level: "B1", pos: "adjective", en: "financial", fa: "مالی" },
  { id: 101785, level: "A1", pos: "noun", en: "fire", fa: "آتش" },
  { id: 101815, level: "B1", pos: "noun", en: "flood", fa: "سیل" },
  { id: 101832, level: "A1", pos: "noun", en: "food", fa: "غذا" },
  { id: 101882, level: "B2", pos: "noun", en: "freedom", fa: "آزادی" },
  { id: 101937, level: "A2", pos: "noun", en: "gas", fa: "گاز" },
  { id: 101944, level: "B2", pos: "noun", en: "gender", fa: "جنسیت" },
  { id: 101974, level: "B1", pos: "adjective", en: "global", fa: "جهانی" },
  { id: 101993, level: "A2", pos: "noun", en: "government", fa: "دولت" },
  { id: 101994, level: "B2", pos: "noun", en: "governor", fa: "فرماندار" },
  { id: 102029, level: "B1", pos: "noun", en: "growth", fa: "رشد" },
  { id: 102041, level: "A2", pos: "noun", en: "gun", fa: "تفنگ" },
  { id: 102086, level: "A1", pos: "noun", en: "health", fa: "سلامت" },
  { id: 102147, level: "B2", pos: "adjective", en: "homeless", fa: "بی خانمان" },
  { id: 102161, level: "A1", pos: "noun", en: "hospital", fa: "بیمارستان" },
  { id: 102171, level: "B2", pos: "noun", en: "housing", fa: "مسکن" },
  { id: 102176, level: "C1", pos: "adjective", en: "humanitarian", fa: "بشردوستانه" },
  { id: 102182, level: "B2", pos: "noun", en: "hunger", fa: "گرسنگی" },
  { id: 102186, level: "B1", pos: "noun", en: "hurricane", fa: "طوفان" },
  { id: 102210, level: "B1", pos: "adjective", en: "illegal", fa: "غیرقانونی" },
  { id: 102223, level: "B1", pos: "noun", en: "immigrant", fa: "مهاجر" },
  { id: 102224, level: "B2", pos: "noun", en: "immigration", fa: "مهاجرت" },
  { id: 102233, level: "B1", pos: "noun", en: "import", fa: "واردات" },
  { id: 102268, level: "B2", pos: "noun", en: "independence", fa: "استقلال" },
  { id: 102283, level: "A2", pos: "noun", en: "industry", fa: "صنعت" },
  { id: 102284, level: "C1", pos: "noun", en: "inequality", fa: "نابرابری" },
  { id: 102292, level: "B2", pos: "noun", en: "inflation", fa: "تورم" },
  { id: 102313, level: "B1", pos: "adjective", en: "injured", fa: "مجروح" },
  { id: 102385, level: "A2", pos: "adjective", en: "international", fa: "بین المللی" },
  { id: 102386, level: "A1", pos: "noun", en: "internet", fa: "اینترنت" },
  { id: 102393, level: "A1", pos: "noun", en: "interview", fa: "مصاحبه" },
  { id: 102405, level: "B2", pos: "noun", en: "investigation", fa: "تحقیق" },
  { id: 102407, level: "B2", pos: "noun", en: "investment", fa: "سرمایه گذاری" },
  { id: 102408, level: "B2", pos: "noun", en: "investor", fa: "سرمایه گذار" },
  { id: 102444, level: "A2", pos: "noun", en: "journalist", fa: "روزنامه نگار" },
  { id: 102447, level: "B1", pos: "noun", en: "judge", fa: "قاضی" },
  { id: 102459, level: "B2", pos: "noun", en: "justice", fa: "عدالت" },
  { id: 102487, level: "B2", pos: "noun", en: "labour", fa: "کار" },
  { id: 102516, level: "A2", pos: "noun", en: "law", fa: "قانون" },
  { id: 102525, level: "A2", pos: "noun", en: "leader", fa: "رهبر" },
  { id: 102526, level: "B2", pos: "noun", en: "leadership", fa: "رهبری" },
  { id: 102543, level: "B1", pos: "adjective", en: "legal", fa: "قانونی" },
  { id: 102546, level: "C1", pos: "noun", en: "legislation", fa: "قانون گذاری" },
  { id: 102687, level: "B2", pos: "noun", en: "manufacturing", fa: "تولید" },
  { id: 102698, level: "A1", pos: "noun", en: "market", fa: "بازار" },
  { id: 102723, level: "B2", pos: "noun", en: "mayor", fa: "شهردار" },
  { id: 102739, level: "A2", pos: "noun", en: "media", fa: "رسانه" },
  { id: 102740, level: "A2", pos: "adjective", en: "medical", fa: "پزشکی" },
  { id: 102742, level: "A2", pos: "noun", en: "medicine", fa: "پزشکی" },
  { id: 102766, level: "C1", pos: "noun", en: "merger", fa: "ادغام" },
  { id: 102779, level: "C1", pos: "noun", en: "migration", fa: "مهاجرت" },
  { id: 102783, level: "B2", pos: "adjective", en: "military", fa: "نظامی" },
  { id: 102796, level: "B2", pos: "noun", en: "minister", fa: "وزیر" },
  { id: 102799, level: "B2", pos: "noun", en: "minority", fa: "اقلیت" },
  { id: 102861, level: "A2", pos: "noun", en: "movement", fa: "حرکت" },
  { id: 102890, level: "B1", pos: "noun", en: "nation", fa: "ملت" },
  { id: 102891, level: "A2", pos: "adjective", en: "national", fa: "ملی" },
  { id: 102911, level: "B2", pos: "verb", en: "negotiate", fa: "مذاکره کردن" },
  { id: 102912, level: "B2", pos: "noun", en: "negotiation", fa: "مذاکره" },
  { id: 102927, level: "A1", pos: "noun", en: "news", fa: "اخبار" },
  { id: 102929, level: "A1", pos: "noun", en: "newspaper", fa: "روزنامه" },
  { id: 102977, level: "B1", pos: "adjective", en: "nuclear", fa: "هسته ای" },
  { id: 103023, level: "B1", pos: "adjective", en: "official", fa: "رسمی" },
  { id: 103027, level: "A2", pos: "noun", en: "oil", fa: "نفت" },
  { id: 103053, level: "B2", pos: "noun", en: "opposition", fa: "مخالفت" },
  { id: 103145, level: "B2", pos: "noun", en: "parliament", fa: "مجلس" },
  { id: 103176, level: "A2", pos: "noun", en: "patient", fa: "بیمار" },
  { id: 103183, level: "A2", pos: "noun", en: "peace", fa: "صلح" },
  { id: 103288, level: "A1", pos: "noun", en: "police", fa: "پلیس" },
  { id: 103290, level: "B1", pos: "noun", en: "policy", fa: "سیاست" },
  { id: 103292, level: "B1", pos: "adjective", en: "political", fa: "سیاسی" },
  { id: 103293, level: "B1", pos: "noun", en: "politician", fa: "سیاستمدار" },
  { id: 103294, level: "B1", pos: "noun", en: "politics", fa: "سیاست" },
  { id: 103296, level: "A2", pos: "noun", en: "pollution", fa: "آلودگی" },
  { id: 103303, level: "A2", pos: "noun", en: "population", fa: "جمعیت" },
  { id: 103327, level: "B1", pos: "noun", en: "poverty", fa: "فقر" },
  { id: 103373, level: "A2", pos: "noun", en: "president", fa: "رئیس جمهور" },
  { id: 103375, level: "B1", pos: "noun", en: "press", fa: "مطبوعات" },
  { id: 103389, level: "A1", pos: "noun", en: "price", fa: "قیمت" },
  { id: 103404, level: "A2", pos: "noun", en: "prison", fa: "زندان" },
  { id: 103455, level: "C1", pos: "noun", en: "propaganda", fa: "تبلیغات" },
  { id: 103473, level: "B1", pos: "noun", en: "protest", fa: "اعتراض" },
  { id: 103535, level: "B2", pos: "noun", en: "racism", fa: "نژادپرستی" },
  { id: 103596, level: "B2", pos: "noun", en: "recession", fa: "رکود" },
  { id: 103622, level: "C1", pos: "noun", en: "reform", fa: "اصلاحات" },
  { id: 103624, level: "B2", pos: "noun", en: "refugee", fa: "پناهنده" },
  { id: 103630, level: "C1", pos: "noun", en: "regime", fa: "رژیم" },
  { id: 103631, level: "A2", pos: "noun", en: "region", fa: "منطقه" },
  { id: 103632, level: "B2", pos: "adjective", en: "regional", fa: "منطقه ای" },
  { id: 103639, level: "B2", pos: "noun", en: "regulation", fa: "مقررات" },
  { id: 103664, level: "B1", pos: "noun", en: "religion", fa: "مذهب" },
  { id: 103665, level: "B1", pos: "adjective", en: "religious", fa: "مذهبی" },
  { id: 103692, level: "A1", pos: "noun", en: "report", fa: "گزارش" },
  { id: 103694, level: "A2", pos: "noun", en: "reporter", fa: "گزارشگر" },
  { id: 103706, level: "B2", pos: "noun", en: "rescue", fa: "نجات" },
  { id: 103707, level: "A2", pos: "noun", en: "research", fa: "تحقیق" },
  { id: 103724, level: "B1", pos: "noun", en: "resource", fa: "منبع" },
  { id: 103759, level: "B2", pos: "noun", en: "revolution", fa: "انقلاب" },
  { id: 103775, level: "B1", pos: "noun", en: "risk", fa: "خطر" },
  { id: 103833, level: "A2", pos: "noun", en: "salary", fa: "حقوق" },
  { id: 103852, level: "B2", pos: "noun", en: "scandal", fa: "رسوایی" },
  { id: 103864, level: "A1", pos: "noun", en: "school", fa: "مدرسه" },
  { id: 103865, level: "A1", pos: "noun", en: "science", fa: "علم" },
  { id: 103867, level: "A1", pos: "noun", en: "scientist", fa: "دانشمند" },
  { id: 103892, level: "B1", pos: "noun", en: "security", fa: "امنیت" },
  { id: 103908, level: "C1", pos: "noun", en: "senator", fa: "سناتور" },
  { id: 103983, level: "B2", pos: "noun", en: "shortage", fa: "کمبود" },
  { id: 104081, level: "A2", pos: "adjective", en: "social", fa: "اجتماعی" },
  { id: 104083, level: "A2", pos: "noun", en: "society", fa: "جامعه" },
  { id: 104089, level: "A2", pos: "noun", en: "soldier", fa: "سرباز" },
  { id: 104119, level: "C1", pos: "noun", en: "sovereignty", fa: "حاکمیت" },
  { id: 104131, level: "B2", pos: "noun", en: "species", fa: "گونه" },
  { id: 104163, level: "B2", pos: "noun", en: "spokesperson", fa: "سخنگو" },
  { id: 104200, level: "A1", pos: "noun", en: "statement", fa: "بیانیه" },
  { id: 104224, level: "B2", pos: "noun", en: "stock", fa: "سهام" },
  { id: 104230, level: "A2", pos: "noun", en: "storm", fa: "طوفان" },
  { id: 104248, level: "B2", pos: "noun", en: "strike", fa: "اعتصاب" },
  { id: 104259, level: "A1", pos: "noun", en: "student", fa: "دانشجو" },
  { id: 104311, level: "C1", pos: "noun", en: "summit", fa: "قله" },
  { id: 104322, level: "B1", pos: "noun", en: "supply", fa: "تأمین" },
  { id: 104395, level: "B1", pos: "noun", en: "tax", fa: "مالیات" },
  { id: 104400, level: "A1", pos: "noun", en: "teacher", fa: "معلم" },
  { id: 104407, level: "A2", pos: "noun", en: "technology", fa: "فناوری" },
  { id: 104412, level: "A1", pos: "noun", en: "television", fa: "تلویزیون" },
  { id: 104437, level: "B2", pos: "noun", en: "territory", fa: "قلمرو" },
  { id: 104439, level: "B2", pos: "noun", en: "terrorism", fa: "تروریسم" },
  { id: 104440, level: "B2", pos: "noun", en: "terrorist", fa: "تروریست" },
  { id: 104493, level: "B2", pos: "noun", en: "threat", fa: "تهدید" },
  { id: 104562, level: "B1", pos: "noun", en: "trade", fa: "تجارت" },
  { id: 104597, level: "B1", pos: "noun", en: "treatment", fa: "درمان" },
  { id: 104598, level: "C1", pos: "noun", en: "treaty", fa: "معاهده" },
  { id: 104602, level: "B2", pos: "noun", en: "trial", fa: "محاکمه" },
  { id: 104668, level: "B1", pos: "noun", en: "unemployment", fa: "بیکاری" },
  { id: 104677, level: "B1", pos: "noun", en: "union", fa: "اتحادیه" },
  { id: 104685, level: "A1", pos: "noun", en: "university", fa: "دانشگاه" },
  { id: 104759, level: "B1", pos: "noun", en: "victim", fa: "قربانی" },
  { id: 104769, level: "B2", pos: "noun", en: "violence", fa: "خشونت" },
  { id: 104773, level: "A2", pos: "noun", en: "virus", fa: "ویروس" },
  { id: 104787, level: "B1", pos: "noun", en: "vote", fa: "رأی" },
  { id: 104792, level: "B2", pos: "noun", en: "wage", fa: "دستمزد" },
  { id: 104800, level: "A2", pos: "noun", en: "war", fa: "جنگ" },
  { id: 104805, level: "B2", pos: "noun", en: "warming", fa: "گرمایش" },
  { id: 104814, level: "A1", pos: "noun", en: "water", fa: "آب" },
  { id: 104821, level: "B2", pos: "noun", en: "wealth", fa: "ثروت" },
  { id: 104823, level: "B1", pos: "noun", en: "weapon", fa: "سلاح" },
  { id: 104878, level: "B2", pos: "noun", en: "wildlife", fa: "حیات وحش" },
  { id: 104909, level: "A1", pos: "noun", en: "worker", fa: "کارگر" },
  { id: 104915, level: "A1", pos: "noun", en: "world", fa: "جهان" },
  { id: 200000, level: "C1", pos: "noun", en: "pandemic", fa: "همه‌گیری" },
  { id: 200001, level: "B2", pos: "noun", en: "vaccine", fa: "واکسن" },
  { id: 200002, level: "B2", pos: "noun", en: "vaccination", fa: "واکسیناسیون" },
  { id: 200003, level: "C1", pos: "noun", en: "quarantine", fa: "قرنطینه" },
  { id: 200004, level: "C1", pos: "noun", en: "lockdown", fa: "قرنطینه عمومی" },
  { id: 200005, level: "B2", pos: "noun", en: "outbreak", fa: "شیوع" },
  { id: 200006, level: "C1", pos: "noun", en: "mutation", fa: "جهش" },
  { id: 200007, level: "C1", pos: "noun", en: "variant", fa: "گونه (ویروس)" },
  { id: 200008, level: "B2", pos: "noun", en: "immunity", fa: "ایمنی" },
  { id: 200009, level: "C1", pos: "noun", en: "ventilator", fa: "دستگاه تنفس مصنوعی" },
  { id: 200010, level: "C1", pos: "verb", en: "sanitize", fa: "ضدعفونی کردن" },
  { id: 200011, level: "C1", pos: "noun", en: "telehealth", fa: "پزشکی از راه دور" },
  { id: 200012, level: "C1", pos: "noun", en: "cryptocurrency", fa: "ارز دیجیتال" },
  { id: 200013, level: "C1", pos: "noun", en: "blockchain", fa: "بلاک‌چین" },
  { id: 200014, level: "C1", pos: "noun", en: "stimulus", fa: "محرک اقتصادی" },
  { id: 200015, level: "C1", pos: "noun", en: "bailout", fa: "نجات مالی" },
  { id: 200016, level: "B2", pos: "noun", en: "tariff", fa: "تعرفه" },
  { id: 200017, level: "B2", pos: "noun", en: "subsidy", fa: "یارانه" },
  { id: 200018, level: "B2", pos: "noun", en: "deficit", fa: "کسری بودجه" },
  { id: 200019, level: "B2", pos: "noun", en: "surplus", fa: "مازاد" },
  { id: 200020, level: "B2", pos: "adjective", en: "renewable", fa: "تجدیدپذیر" },
  { id: 200021, level: "B2", pos: "adjective", en: "sustainable", fa: "پایدار" },
  { id: 200022, level: "C1", pos: "noun", en: "fossil fuel", fa: "سوخت فسیلی" },
  { id: 200023, level: "C1", pos: "noun", en: "deforestation", fa: "جنگل‌زدایی" },
  { id: 200024, level: "C1", pos: "noun", en: "biodiversity", fa: "تنوع زیستی" },
  { id: 200025, level: "B2", pos: "noun", en: "ecosystem", fa: "اکوسیستم" },
  { id: 200026, level: "C1", pos: "noun", en: "greenhouse gas", fa: "گاز گلخانه‌ای" },
  { id: 200027, level: "C1", pos: "noun", en: "carbon footprint", fa: "ردپای کربن" },
  { id: 200028, level: "B1", pos: "verb", en: "recycle", fa: "بازیافت" },
  { id: 200029, level: "C1", pos: "noun", en: "artificial intelligence", fa: "هوش مصنوعی" },
  { id: 200030, level: "B2", pos: "noun", en: "algorithm", fa: "الگوریتم" },
  { id: 200031, level: "B2", pos: "noun", en: "drone", fa: "پهپاد" },
  { id: 200032, level: "C1", pos: "noun", en: "cyberattack", fa: "حمله سایبری" },
  { id: 200033, level: "C1", pos: "noun", en: "cybersecurity", fa: "امنیت سایبری" },
  { id: 200034, level: "B1", pos: "adjective", en: "digital", fa: "دیجیتال" },
  { id: 200035, level: "B1", pos: "noun", en: "software", fa: "نرم‌افزار" },
  { id: 200036, level: "B1", pos: "noun", en: "hardware", fa: "سخت‌افزار" },
  { id: 200037, level: "B2", pos: "noun", en: "innovation", fa: "نوآوری" },
  { id: 200038, level: "B2", pos: "noun", en: "sanction", fa: "تحریم" },
  { id: 200039, level: "C1", pos: "noun", en: "ceasefire", fa: "آتش‌بس" },
  { id: 200040, level: "C1", pos: "noun", en: "diplomacy", fa: "دیپلماسی" },
  { id: 200041, level: "C1", pos: "noun", en: "impeachment", fa: "استیضاح" },
  { id: 200042, level: "C1", pos: "noun", en: "referendum", fa: "همه‌پرسی" },
  { id: 200043, level: "B2", pos: "noun", en: "ally", fa: "متحد" },
  { id: 200044, level: "C1", pos: "noun", en: "pact", fa: "پیمان" },
  { id: 200045, level: "C1", pos: "adjective", en: "multilateral", fa: "چندجانبه" },
  { id: 200046, level: "C1", pos: "adjective", en: "bilateral", fa: "دوجانبه" },
  { id: 200047, level: "B2", pos: "noun", en: "riot", fa: "شورش" },
  { id: 200048, level: "B2", pos: "noun", en: "curfew", fa: "منع رفت و آمد" },
  { id: 200049, level: "B2", pos: "noun", en: "wildfire", fa: "آتش‌سوزی جنگل" },
  { id: 200050, level: "B2", pos: "noun", en: "avalanche", fa: "بهمن" },
  { id: 200051, level: "B2", pos: "noun", en: "tornado", fa: "گردباد" },
  { id: 200052, level: "B2", pos: "noun", en: "cyclone", fa: "طوفان حاره‌ای" },
  { id: 200053, level: "B2", pos: "noun", en: "famine", fa: "قحطی" },
  { id: 200054, level: "B2", pos: "noun", en: "lawsuit", fa: "دعوی قضایی" },
  { id: 200055, level: "C1", pos: "noun", en: "verdict", fa: "رأی دادگاه" },
  { id: 200056, level: "B2", pos: "noun", en: "appeal", fa: "تجدیدنظر" },
  { id: 200057, level: "C1", pos: "verb", en: "acquit", fa: "تبرئه کردن" },
  { id: 200058, level: "B2", pos: "noun", en: "custody", fa: "بازداشت موقت" },
  { id: 200059, level: "B2", pos: "noun", en: "mental health", fa: "سلامت روان" },
  { id: 200060, level: "B2", pos: "noun", en: "obesity", fa: "چاقی" },
  { id: 200061, level: "B2", pos: "noun", en: "diabetes", fa: "دیابت" },
  { id: 200062, level: "B1", pos: "noun", en: "cancer", fa: "سرطان" },
  { id: 200063, level: "B2", pos: "noun", en: "heart disease", fa: "بیماری قلبی" },
  { id: 200064, level: "B2", pos: "noun", en: "stroke", fa: "سکته" },
  { id: 200065, level: "A2", pos: "noun", en: "vehicle", fa: "وسیله نقلیه" },
  { id: 200066, level: "A2", pos: "noun", en: "driver", fa: "راننده" },
  { id: 200067, level: "B1", pos: "noun", en: "accident", fa: "تصادف" },
  { id: 200068, level: "B1", pos: "noun", en: "airport", fa: "فرودگاه" },
  { id: 200069, level: "B1", pos: "noun", en: "flight", fa: "پرواز" },
  { id: 200070, level: "B1", pos: "noun", en: "railway", fa: "راه آهن" },
  { id: 200071, level: "B2", pos: "noun", en: "cargo", fa: "بار" },
  { id: 200072, level: "B2", pos: "noun", en: "infrastructure", fa: "زیرساخت" },
  { id: 200073, level: "C1", pos: "noun", en: "congestion", fa: "ازدحام" },
  { id: 200074, level: "C1", pos: "noun", en: "commute", fa: "رفت و آمد روزانه" },
  { id: 200075, level: "B2", pos: "adjective", en: "autonomous", fa: "خودمختار" },
  { id: 200076, level: "B2", pos: "noun", en: "fraud", fa: "کلاهبرداری" },
  { id: 200077, level: "B2", pos: "noun", en: "theft", fa: "سرقت" },
  { id: 200078, level: "B2", pos: "noun", en: "robbery", fa: "دزدی" },
  { id: 200080, level: "C1", pos: "noun", en: "bribery", fa: "رشوه" },
  { id: 200081, level: "B2", pos: "noun", en: "sentence", fa: "حکم" },
  { id: 200082, level: "C1", pos: "noun", en: "convict", fa: "محکوم" },
  { id: 200083, level: "B2", pos: "noun", en: "witness", fa: "شاهد" },
  { id: 200084, level: "B2", pos: "noun", en: "evidence", fa: "مدرک" },
  { id: 200085, level: "C1", pos: "verb", en: "indict", fa: "متهم کردن" },
  { id: 200087, level: "C1", pos: "noun", en: "embargo", fa: "تحریم" },
  { id: 200088, level: "C1", pos: "noun", en: "consul", fa: "کنسول" },
  { id: 200089, level: "C1", pos: "noun", en: "delegation", fa: "هیئت نمایندگی" },
  { id: 200090, level: "B2", pos: "noun", en: "foreign aid", fa: "کمک خارجی" },
  { id: 200091, level: "B2", pos: "noun", en: "visa", fa: "ویزا" },
  { id: 200092, level: "B2", pos: "noun", en: "border control", fa: "کنترل مرزی" },
  { id: 200093, level: "C1", pos: "noun", en: "asylum", fa: "پناهندگی" },
  { id: 200094, level: "C1", pos: "noun", en: "annexation", fa: "ضمیمه کردن" },
  { id: 200095, level: "B1", pos: "noun", en: "solar", fa: "خورشیدی" },
  { id: 200096, level: "B1", pos: "noun", en: "wind", fa: "باد" },
  { id: 200097, level: "B2", pos: "noun", en: "hydroelectric", fa: "برق آبی" },
  { id: 200098, level: "B2", pos: "noun", en: "geothermal", fa: "زمین گرمایی" },
  { id: 200099, level: "C1", pos: "noun", en: "fuel", fa: "سوخت" },
  { id: 200100, level: "B2", pos: "noun", en: "grid", fa: "شبکه برق" },
  { id: 200101, level: "C1", pos: "noun", en: "power plant", fa: "نیروگاه" },
  { id: 200102, level: "B2", pos: "verb", en: "consume", fa: "مصرف کردن" },
  { id: 200104, level: "B2", pos: "noun", en: "rent", fa: "اجاره" },
  { id: 200105, level: "B2", pos: "noun", en: "mortgage", fa: "رهن" },
  { id: 200106, level: "B1", pos: "noun", en: "neighborhood", fa: "محله" },
  { id: 200107, level: "B2", pos: "noun", en: "construction", fa: "ساخت و ساز" },
  { id: 200108, level: "C1", pos: "noun", en: "gentrification", fa: "نوسازی شهری" },
  { id: 200109, level: "B1", pos: "noun", en: "facility", fa: "امکانات" },
  { id: 200110, level: "A2", pos: "noun", en: "museum", fa: "موزه" },
  { id: 200111, level: "B1", pos: "noun", en: "festival", fa: "جشنواره" },
  { id: 200112, level: "B1", pos: "noun", en: "exhibition", fa: "نمایشگاه" },
  { id: 200113, level: "A2", pos: "noun", en: "music", fa: "موسیقی" },
  { id: 200114, level: "B1", pos: "noun", en: "film", fa: "فیلم" },
  { id: 200115, level: "B2", pos: "noun", en: "heritage", fa: "میراث" },
  { id: 200116, level: "B2", pos: "noun", en: "tradition", fa: "سنت" },
  { id: 200117, level: "B1", pos: "adjective", en: "contemporary", fa: "معاصر" },
  { id: 200118, level: "B2", pos: "noun", en: "profit", fa: "سود" },
  { id: 200119, level: "B2", pos: "noun", en: "loss", fa: "زیان" },
  { id: 200120, level: "B1", pos: "noun", en: "contract", fa: "قرارداد" },
  { id: 200121, level: "B2", pos: "noun", en: "retail", fa: "خرده فروشی" },
  { id: 200122, level: "B2", pos: "noun", en: "wholesale", fa: "عمده فروشی" },
  { id: 200123, level: "B1", pos: "noun", en: "customer", fa: "مشتری" },
  { id: 200124, level: "B2", pos: "noun", en: "shareholder", fa: "سهامدار" },
  { id: 200125, level: "C1", pos: "noun", en: "takeover", fa: "تصاحب" },
  { id: 200126, level: "C1", pos: "noun", en: "bankruptcy", fa: "ورشکستگی" },
  { id: 200127, level: "B2", pos: "noun", en: "startup", fa: "شرکت نوپا" },
  { id: 200128, level: "A1", pos: "noun", en: "rain", fa: "باران" },
  { id: 200129, level: "A1", pos: "noun", en: "snow", fa: "برف" },
  { id: 200131, level: "A2", pos: "noun", en: "temperature", fa: "دما" },
  { id: 200132, level: "B1", pos: "noun", en: "forecast", fa: "پیش‌بینی" },
  { id: 200133, level: "B2", pos: "noun", en: "humidity", fa: "رطوبت" },
  { id: 200134, level: "B2", pos: "noun", en: "atmosphere", fa: "جو" },
  { id: 200200, level: "A2", pos: "noun", en: "athlete", fa: "ورزشکار" },
  { id: 200201, level: "B1", pos: "noun", en: "coach", fa: "مربی" },
  { id: 200202, level: "A2", pos: "noun", en: "stadium", fa: "ورزشگاه" },
  { id: 200203, level: "B2", pos: "noun", en: "championship", fa: "قهرمانی" },
  { id: 200204, level: "B2", pos: "noun", en: "tournament", fa: "مسابقات" },
  { id: 200205, level: "B2", pos: "noun", en: "referee", fa: "داور" },
  { id: 200206, level: "B2", pos: "noun", en: "spectator", fa: "تماشاگر" },
  { id: 200207, level: "B2", pos: "noun", en: "medal", fa: "مدال" },
  { id: 200208, level: "B2", pos: "noun", en: "defeat", fa: "شکست" },
  { id: 200209, level: "B2", pos: "noun", en: "victory", fa: "پیروزی" },
  { id: 200210, level: "B1", pos: "noun", en: "score", fa: "امتیاز" },
  { id: 200211, level: "A2", pos: "noun", en: "match", fa: "مسابقه" },
  { id: 200212, level: "A2", pos: "noun", en: "team", fa: "تیم" },
  { id: 200213, level: "A2", pos: "noun", en: "player", fa: "بازیکن" },
  { id: 200214, level: "B2", pos: "noun", en: "olympics", fa: "المپیک" },
  { id: 200215, level: "B2", pos: "noun", en: "world cup", fa: "جام جهانی" },
  { id: 200216, level: "B2", pos: "noun", en: "astronaut", fa: "فضانورد" },
  { id: 200217, level: "B2", pos: "noun", en: "satellite", fa: "ماهواره" },
  { id: 200218, level: "B2", pos: "noun", en: "telescope", fa: "تلسکوپ" },
  { id: 200219, level: "C1", pos: "noun", en: "orbit", fa: "مدار" },
  { id: 200220, level: "B2", pos: "noun", en: "rocket", fa: "موشک" },
  { id: 200221, level: "A2", pos: "noun", en: "planet", fa: "سیاره" },
  { id: 200222, level: "A2", pos: "noun", en: "star", fa: "ستاره" },
  { id: 200223, level: "C1", pos: "noun", en: "galaxy", fa: "کهکشان" },
  { id: 200224, level: "C1", pos: "noun", en: "universe", fa: "جهان" },
  { id: 200225, level: "B2", pos: "noun", en: "exploration", fa: "اکتشاف" },
  { id: 200226, level: "B2", pos: "noun", en: "launch", fa: "پرتاب" },
  { id: 200227, level: "C1", pos: "noun", en: "spacecraft", fa: "فضاپیما" },
  { id: 200228, level: "C1", pos: "noun", en: "asteroid", fa: "سیارک" },
  { id: 200229, level: "C1", pos: "noun", en: "comet", fa: "دنباله‌دار" },
  { id: 200230, level: "B2", pos: "noun", en: "alien", fa: "بیگانه" },
  { id: 200231, level: "B2", pos: "noun", en: "nasa", fa: "ناسا" },
  { id: 200232, level: "B2", pos: "noun", en: "robot", fa: "ربات" },
  { id: 200233, level: "C1", pos: "noun", en: "automation", fa: "اتوماسیون" },
  { id: 200234, level: "B2", pos: "adjective", en: "virtual", fa: "مجازی" },
  { id: 200235, level: "B2", pos: "noun", en: "reality", fa: "واقعیت" },
  { id: 200236, level: "C1", pos: "noun", en: "metaverse", fa: "متاورس" },
  { id: 200237, level: "C1", pos: "noun", en: "quantum", fa: "کوانتوم" },
  { id: 200238, level: "C1", pos: "noun", en: "computing", fa: "محاسبات" },
  { id: 200239, level: "C1", pos: "noun", en: "semiconductor", fa: "نیمه‌رسانا" },
  { id: 200240, level: "B2", pos: "noun", en: "chip", fa: "تراشه" },
  { id: 200241, level: "B2", pos: "noun", en: "broadband", fa: "پهنای باند" },
  { id: 200242, level: "C1", pos: "noun", en: "fiber", fa: "فیبر" },
  { id: 200243, level: "B2", pos: "noun", en: "cable", fa: "کابل" },
  { id: 200244, level: "B2", pos: "noun", en: "server", fa: "سرور" },
  { id: 200245, level: "B2", pos: "noun", en: "cloud", fa: "ابر" },
  { id: 200246, level: "B2", pos: "noun", en: "database", fa: "پایگاه داده" },
  { id: 200247, level: "C1", pos: "noun", en: "encryption", fa: "رمزنگاری" },
  { id: 200248, level: "B2", pos: "noun", en: "surgery", fa: "جراحی" },
  { id: 200249, level: "B2", pos: "noun", en: "therapy", fa: "درمان" },
  { id: 200250, level: "C1", pos: "adjective", en: "clinical", fa: "بالینی" },
  { id: 200251, level: "B2", pos: "noun", en: "trial", fa: "آزمایش بالینی" },
  { id: 200252, level: "B2", pos: "noun", en: "cure", fa: "درمان قطعی" },
  { id: 200253, level: "B2", pos: "noun", en: "symptom", fa: "نشانه" },
  { id: 200254, level: "C1", pos: "noun", en: "diagnosis", fa: "تشخیص" },
  { id: 200255, level: "B2", pos: "noun", en: "prescription", fa: "نسخه" },
  { id: 200256, level: "B1", pos: "noun", en: "pharmacy", fa: "داروخانه" },
  { id: 200257, level: "A2", pos: "noun", en: "nurse", fa: "پرستار" },
  { id: 200258, level: "B1", pos: "noun", en: "paramedic", fa: "بهیار" },
  { id: 200259, level: "B1", pos: "noun", en: "ambulance", fa: "آمبولانس" },
  { id: 200260, level: "C1", pos: "adjective", en: "endemic", fa: "بومی (محلی)" },
  { id: 200261, level: "C1", pos: "noun", en: "cabinet", fa: "هیئت وزیران" },
  { id: 200262, level: "B2", pos: "noun", en: "ministry", fa: "وزارتخانه" },
  { id: 200263, level: "B2", pos: "noun", en: "administration", fa: "دولت (اداره)" },
  { id: 200264, level: "C1", pos: "noun", en: "legislature", fa: "قوه مقننه" },
  { id: 200265, level: "C1", pos: "noun", en: "judiciary", fa: "قوه قضائیه" },
  { id: 200266, level: "C1", pos: "noun", en: "executive", fa: "قوه مجریه" },
  { id: 200267, level: "B2", pos: "noun", en: "republic", fa: "جمهوری" },
  { id: 200268, level: "C1", pos: "noun", en: "monarchy", fa: "سلطنت" },
  { id: 200269, level: "C1", pos: "noun", en: "chancellor", fa: "صدراعظم" },
  { id: 200270, level: "C1", pos: "noun", en: "austerity", fa: "ریاضت اقتصادی" },
  { id: 200271, level: "C1", pos: "noun", en: "devaluation", fa: "کاهش ارزش پول" },
  { id: 200272, level: "C1", pos: "noun", en: "liquidation", fa: "تصفیه" },
  { id: 200273, level: "B2", pos: "noun", en: "portfolio", fa: "پرتفوی" },
  { id: 200274, level: "C1", pos: "noun", en: "dividend", fa: "سود سهام" },
  { id: 200275, level: "B2", pos: "noun", en: "bond", fa: "اوراق قرضه" },
  { id: 200276, level: "C1", pos: "noun", en: "equity", fa: "حقوق صاحبان سهام" },
  { id: 200278, level: "B2", pos: "noun", en: "loan", fa: "وام" },
  { id: 200279, level: "B2", pos: "adjective", en: "endangered", fa: "در خطر انقراض" },
  { id: 200280, level: "B2", pos: "noun", en: "extinction", fa: "انقراض" },
  { id: 200281, level: "B2", pos: "noun", en: "habitat", fa: "زیستگاه" },
  { id: 200282, level: "C1", pos: "noun", en: "pollutant", fa: "آلاینده" },
  { id: 200283, level: "B1", pos: "noun", en: "waste", fa: "پسماند" },
  { id: 200284, level: "C1", pos: "noun", en: "landfill", fa: "محل دفن زباله" },
  { id: 200285, level: "C1", pos: "noun", en: "sewage", fa: "فاضلاب" },
  { id: 200286, level: "C1", pos: "noun", en: "drainage", fa: "زهکشی" },
  { id: 200287, level: "C1", pos: "noun", en: "controversy", fa: "جنجال" },
  { id: 200288, level: "C1", pos: "noun", en: "suspicion", fa: "ظن" },
  { id: 200289, level: "C1", pos: "noun", en: "allegation", fa: "ادعا" },
  { id: 200290, level: "C1", pos: "noun", en: "testimony", fa: "شهادت" },
  { id: 200291, level: "C1", pos: "noun", en: "pardon", fa: "عفو" },
  { id: 200292, level: "C1", pos: "noun", en: "parole", fa: "آزادی مشروط" },
  { id: 200293, level: "C1", pos: "noun", en: "abortion", fa: "سقط جنین" },
  { id: 200294, level: "A2", pos: "noun", en: "marriage", fa: "ازدواج" },
  { id: 200295, level: "B2", pos: "noun", en: "divorce", fa: "طلاق" },
  { id: 200296, level: "C1", pos: "noun", en: "adoption", fa: "فرزندخواندگی" },
  { id: 200297, level: "C1", pos: "adjective", en: "foster", fa: "سرپرستی" },
  { id: 200298, level: "B2", pos: "noun", en: "veteran", fa: "کهنه سرباز" },
  { id: 200299, level: "B2", pos: "noun", en: "pension", fa: "بازنشستگی" },
  { id: 200300, level: "B2", pos: "noun", en: "welfare", fa: "رفاه" },
  { id: 200301, level: "B2", pos: "noun", en: "benefit", fa: "مزایا" },
  { id: 200302, level: "C1", pos: "noun", en: "smuggling", fa: "قاچاق" },
  { id: 200303, level: "C1", pos: "noun", en: "trafficking", fa: "قاچاق انسان" },
  { id: 200304, level: "C1", pos: "noun", en: "homicide", fa: "قتل" },
  { id: 200305, level: "C1", pos: "noun", en: "arson", fa: "آتش‌سوزی عمدی" },
  { id: 200306, level: "B2", pos: "noun", en: "vandalism", fa: "خرابکاری" },
  { id: 200307, level: "C1", pos: "noun", en: "piracy", fa: "دزدی دریایی" },
  { id: 200308, level: "B2", pos: "noun", en: "empire", fa: "امپراتوری" },
  { id: 200309, level: "B2", pos: "noun", en: "civilization", fa: "تمدن" },
  { id: 200310, level: "B2", pos: "noun", en: "medieval", fa: "قرون وسطی" },
  { id: 200311, level: "C1", pos: "noun", en: "renaissance", fa: "رنسانس" },
  { id: 200312, level: "C1", pos: "noun", en: "uprising", fa: "قیام" },
  { id: 200313, level: "B2", pos: "noun", en: "dynasty", fa: "سلسله" },
  { id: 200314, level: "C1", pos: "noun", en: "colonialism", fa: "استعمار" },
  { id: 200315, level: "C1", pos: "noun", en: "imperialism", fa: "امپریالیسم" },
  { id: 200316, level: "B2", pos: "noun", en: "archaeology", fa: "باستان‌شناسی" },
  { id: 200317, level: "B2", pos: "noun", en: "artifact", fa: "اثر باستانی" },
  { id: 200318, level: "C1", pos: "noun", en: "excavation", fa: "حفاری" },
  { id: 200319, level: "B2", pos: "noun", en: "ancestor", fa: "نیاکان" },
  { id: 200320, level: "B2", pos: "adjective", en: "ancient", fa: "باستانی" },
  { id: 200321, level: "A2", pos: "noun", en: "century", fa: "قرن" },
  { id: 200322, level: "B1", pos: "noun", en: "decade", fa: "دهه" },
  { id: 200323, level: "C1", pos: "noun", en: "feudalism", fa: "فئودالیسم" },
  { id: 200324, level: "C1", pos: "noun", en: "reign", fa: "حکومت (سلطنت)" },
  { id: 200325, level: "B2", pos: "noun", en: "tribe", fa: "قبیله" },
  { id: 200326, level: "C1", pos: "noun", en: "nomad", fa: "کوچ‌نشین" },
  { id: 200327, level: "B2", pos: "noun", en: "settlement", fa: "سکونت‌گاه" },
  { id: 200328, level: "B2", pos: "noun", en: "invasion", fa: "تهاجم" },
  { id: 200329, level: "C1", pos: "noun", en: "siege", fa: "محاصره" },
  { id: 200330, level: "C1", pos: "noun", en: "armistice", fa: "آتش‌بس (متارکه)" },
  { id: 200331, level: "C1", pos: "noun", en: "confederation", fa: "کنفدراسیون" },
  { id: 200332, level: "B2", pos: "noun", en: "kingdom", fa: "پادشاهی" },
  { id: 200333, level: "B1", pos: "noun", en: "palace", fa: "کاخ" },
  { id: 200334, level: "A2", pos: "noun", en: "castle", fa: "قلعه" },
  { id: 200335, level: "B2", pos: "noun", en: "cathedral", fa: "کلیسای جامع" },
  { id: 200336, level: "B2", pos: "noun", en: "temple", fa: "معبد" },
  { id: 200337, level: "B1", pos: "noun", en: "pyramid", fa: "هرم" },
  { id: 200338, level: "C1", pos: "noun", en: "pharaoh", fa: "فرعون" },
  { id: 200339, level: "C1", pos: "noun", en: "sultan", fa: "سلطان" },
  { id: 200340, level: "B2", pos: "noun", en: "emperor", fa: "امپراتور" },
  { id: 200341, level: "B2", pos: "noun", en: "conquest", fa: "فتح" },
  { id: 200342, level: "C1", pos: "noun", en: "dissolution", fa: "انحلال" },
  { id: 200343, level: "C1", pos: "noun", en: "partition", fa: "تقسیم (کشور)" },
  { id: 200344, level: "B2", pos: "noun", en: "autonomy", fa: "خودمختاری" },
  { id: 200345, level: "C1", pos: "noun", en: "hegemony", fa: "سلطه" },
  { id: 200346, level: "C1", pos: "noun", en: "indoctrination", fa: "تلقین" },
  { id: 200347, level: "C1", pos: "noun", en: "crusade", fa: "جنگ صلیبی" },
  { id: 200348, level: "C1", pos: "noun", en: "genocide", fa: "نسل‌کشی" },
  { id: 200349, level: "C1", pos: "noun", en: "holocaust", fa: "هولوکاست" },
  { id: 200350, level: "B2", pos: "noun", en: "exile", fa: "تبعید" },
  { id: 200351, level: "B2", pos: "noun", en: "migrant", fa: "مهاجر (فصلی)" },
  { id: 200352, level: "C1", pos: "adjective", en: "feudal", fa: "فئودالی" },
  { id: 200353, level: "B2", pos: "noun", en: "noble", fa: "نجیب‌زاده" },
  { id: 200354, level: "B2", pos: "noun", en: "peasant", fa: "دهقان" },
  { id: 200355, level: "B2", pos: "noun", en: "slave", fa: "برده" },
  { id: 200356, level: "B2", pos: "noun", en: "serf", fa: "رعیت" },
  { id: 200357, level: "C1", pos: "noun", en: "bourgeoisie", fa: "بورژوازی" },
  { id: 200358, level: "C1", pos: "noun", en: "proletariat", fa: "پرولتاریا" },
  { id: 200359, level: "B2", pos: "adjective", en: "colonial", fa: "استعماری" },
  { id: 200360, level: "C1", pos: "noun", en: "decolonization", fa: "استعمارزدایی" },
  { id: 200361, level: "B2", pos: "noun", en: "historian", fa: "مورخ" },
  { id: 200362, level: "B1", pos: "noun", en: "archive", fa: "بایگانی" },
  { id: 200363, level: "B2", pos: "noun", en: "manuscript", fa: "نسخه خطی" },
  { id: 200364, level: "B2", pos: "noun", en: "inscription", fa: "کتیبه" },
  { id: 200365, level: "C1", pos: "noun", en: "chronology", fa: "گاه‌شماری" },
  { id: 200366, level: "B2", pos: "adjective", en: "medieval", fa: "قرون وسطایی" },
  { id: 200367, level: "C1", pos: "adjective", en: "renaissance", fa: "رنسانسی" },
  { id: 200368, level: "C1", pos: "adjective", en: "enlightenment", fa: "عصر روشنگری" },
  { id: 200369, level: "C1", pos: "noun", en: "reformation", fa: "رفرماسیون" },
  { id: 200370, level: "C1", pos: "noun", en: "humanism", fa: "اومانیسم" },
  { id: 200371, level: "B2", pos: "noun", en: "pope", fa: "پاپ" },
  { id: 200372, level: "B2", pos: "noun", en: "caliph", fa: "خلیفه" },
  { id: 200373, level: "B2", pos: "noun", en: "prophet", fa: "پیامبر" },
  { id: 200374, level: "B1", pos: "noun", en: "myth", fa: "اسطوره" },
  { id: 200375, level: "B2", pos: "noun", en: "legend", fa: "افسانه" },
  { id: 200376, level: "B2", pos: "noun", en: "folklore", fa: "فولکلور" },
  { id: 200377, level: "C1", pos: "noun", en: "archaic", fa: "کهن" },
  { id: 200378, level: "B2", pos: "noun", en: "prehistoric", fa: "پیش از تاریخ" },
  { id: 200379, level: "B2", pos: "noun", en: "antiquity", fa: "دوران باستان" },
  { id: 200380, level: "C1", pos: "noun", en: "patriarchy", fa: "پدرسالاری" },
  { id: 200381, level: "C1", pos: "noun", en: "matriarchy", fa: "مادرسالاری" },
  { id: 200382, level: "B2", pos: "noun", en: "lineage", fa: "نسب" },
  { id: 200383, level: "B2", pos: "noun", en: "legacy", fa: "میراث (باقی‌مانده)" },
  { id: 200384, level: "C1", pos: "noun", en: "guerrilla", fa: "چریک" },
  { id: 200385, level: "C1", pos: "noun", en: "partisan", fa: "پارتیزان" },
  { id: 200386, level: "B2", pos: "noun", en: "martyr", fa: "شهید" },
  { id: 200387, level: "B2", pos: "noun", en: "combatant", fa: "جنگجو" },
  { id: 200388, level: "C1", pos: "noun", en: "armada", fa: "ناوگان" },
  { id: 200389, level: "B2", pos: "noun", en: "cavalry", fa: "سواره نظام" },
  { id: 200390, level: "B2", pos: "noun", en: "infantry", fa: "پیاده نظام" },
  { id: 200391, level: "C1", pos: "noun", en: "artillery", fa: "توپخانه" },
  { id: 200392, level: "C1", pos: "noun", en: "arsenal", fa: "اسلحه‌خانه" },
  { id: 200393, level: "B2", pos: "noun", en: "fortress", fa: "دژ" },
  { id: 200394, level: "B2", pos: "noun", en: "rampart", fa: "بارو" },
  { id: 200395, level: "C1", pos: "noun", en: "moat", fa: "خندق" },
  { id: 200396, level: "B2", pos: "noun", en: "chariot", fa: "ارابه" },
  { id: 200397, level: "C1", pos: "noun", en: "pike", fa: "نیزه" },
  { id: 200398, level: "C1", pos: "noun", en: "crossbow", fa: "کمان زنبورکی" },
  { id: 200399, level: "B2", pos: "noun", en: "longbow", fa: "کمان بلند" },
  { id: 200400, level: "C1", pos: "noun", en: "coat of arms", fa: "نشان خانوادگی" },
  { id: 200401, level: "B2", pos: "noun", en: "heraldry", fa: "نشان‌شناسی" },
  { id: 200402, level: "B2", pos: "noun", en: "census", fa: "سرشماری" },
  { id: 200403, level: "B2", pos: "noun", en: "guild", fa: "صنف" },
  { id: 200404, level: "C1", pos: "noun", en: "mercantilism", fa: "مرکانتیلیسم" },
  { id: 200405, level: "C1", pos: "noun", en: "industrialization", fa: "صنعتی‌سازی" },
  { id: 200406, level: "C1", pos: "noun", en: "urbanization", fa: "شهرنشینی" },
  { id: 200407, level: "B2", pos: "noun", en: "chronicle", fa: "وقایع‌نامه" },
  { id: 200408, level: "B2", pos: "noun", en: "depression", fa: "افسردگی" },
  { id: 200409, level: "B2", pos: "noun", en: "anxiety", fa: "اضطراب" },
  { id: 200410, level: "C1", pos: "noun", en: "stress", fa: "استرس" },
  { id: 200411, level: "C1", pos: "noun", en: "trauma", fa: "تروما" },
  { id: 200412, level: "B2", pos: "noun", en: "phobia", fa: "فوبیا" },
  { id: 200413, level: "C1", pos: "noun", en: "panic", fa: "وحشت" },
  { id: 200414, level: "B2", pos: "noun", en: "obsession", fa: "وسواس" },
  { id: 200415, level: "B2", pos: "noun", en: "compulsion", fa: "اجبار (ذهنی)" },
  { id: 200416, level: "C1", pos: "noun", en: "addiction", fa: "اعتیاد" },
  { id: 200417, level: "B2", pos: "noun", en: "withdrawal", fa: "سندرم ترک" },
  { id: 200418, level: "C1", pos: "noun", en: "hallucination", fa: "توهم" },
  { id: 200419, level: "C1", pos: "noun", en: "delusion", fa: "هذیان" },
  { id: 200420, level: "B2", pos: "noun", en: "psychosis", fa: "روان‌پریشی" },
  { id: 200421, level: "B2", pos: "noun", en: "neurosis", fa: "نوروز" },
  { id: 200422, level: "C1", pos: "noun", en: "paranoia", fa: "پارانویا" },
  { id: 200423, level: "B2", pos: "noun", en: "schizophrenia", fa: "اسکیزوفرنی" },
  { id: 200424, level: "C1", pos: "noun", en: "bipolar", fa: "دوقطبی" },
  { id: 200425, level: "B2", pos: "noun", en: "autism", fa: "اوتیسم" },
  { id: 200426, level: "B2", pos: "noun", en: "dementia", fa: "زوال عقل" },
  { id: 200427, level: "B2", pos: "noun", en: "memory", fa: "حافظه" },
  { id: 200428, level: "B2", pos: "noun", en: "cognition", fa: "شناخت" },
  { id: 200429, level: "C1", pos: "noun", en: "perception", fa: "ادراک" },
  { id: 200430, level: "C1", pos: "noun", en: "attention", fa: "توجه" },
  { id: 200431, level: "B2", pos: "noun", en: "consciousness", fa: "هوشیاری" },
  { id: 200432, level: "C1", pos: "noun", en: "subconscious", fa: "ناخودآگاه" },
  { id: 200433, level: "C1", pos: "noun", en: "unconscious", fa: "ضمیر ناخودآگاه" },
  { id: 200434, level: "B2", pos: "noun", en: "instinct", fa: "غریزه" },
  { id: 200435, level: "B2", pos: "noun", en: "intuition", fa: "بینش" },
  { id: 200436, level: "C1", pos: "noun", en: "empathy", fa: "همدلی" },
  { id: 200437, level: "B2", pos: "noun", en: "sympathy", fa: "همدردی" },
  { id: 200438, level: "B2", pos: "noun", en: "apathy", fa: "بی‌تفاوتی" },
  { id: 200439, level: "C1", pos: "noun", en: "compassion", fa: "دلسوزی" },
  { id: 200440, level: "B2", pos: "adjective", en: "empathic", fa: "همدل" },
  { id: 200441, level: "B2", pos: "noun", en: "emotion", fa: "هیجان" },
  { id: 200442, level: "B2", pos: "noun", en: "feeling", fa: "احساس" },
  { id: 200443, level: "C1", pos: "noun", en: "affection", fa: "محبت" },
  { id: 200444, level: "B2", pos: "noun", en: "aggression", fa: "پرخاشگری" },
  { id: 200445, level: "B2", pos: "noun", en: "frustration", fa: "سرخوردگی" },
  { id: 200446, level: "C1", pos: "noun", en: "resentment", fa: "کینه" },
  { id: 200447, level: "C1", pos: "noun", en: "guilt", fa: "احساس گناه" },
  { id: 200448, level: "B2", pos: "noun", en: "shame", fa: "شرم" },
  { id: 200449, level: "B2", pos: "noun", en: "pride", fa: "غرور" },
  { id: 200450, level: "B2", pos: "noun", en: "self-esteem", fa: "احساس ارزشمندی" },
  { id: 200451, level: "B2", pos: "noun", en: "identity", fa: "هویت" },
  { id: 200452, level: "C1", pos: "noun", en: "personality", fa: "شخصیت" },
  { id: 200453, level: "B2", pos: "noun", en: "temperament", fa: "خلق و خو" },
  { id: 200454, level: "C1", pos: "noun", en: "psychology", fa: "روان‌شناسی" },
  { id: 200455, level: "B2", pos: "noun", en: "psychiatrist", fa: "روانپزشک" },
  { id: 200456, level: "B2", pos: "noun", en: "psychologist", fa: "روانشناس" },
  { id: 200457, level: "B2", pos: "noun", en: "counseling", fa: "مشاوره" },
  { id: 200458, level: "C1", pos: "noun", en: "psychoanalysis", fa: "روان‌کاوی" },
  { id: 200459, level: "B2", pos: "adjective", en: "cognitive", fa: "شناختی" },
  { id: 200460, level: "C1", pos: "adjective", en: "behavioral", fa: "رفتاری" },
  { id: 200461, level: "B2", pos: "noun", en: "stimulus", fa: "محرک" },
  { id: 200462, level: "B2", pos: "noun", en: "response", fa: "پاسخ" },
  { id: 200463, level: "C1", pos: "noun", en: "reinforcement", fa: "تقویت" },
  { id: 200464, level: "B2", pos: "noun", en: "punishment", fa: "تنبیه" },
  { id: 200465, level: "C1", pos: "noun", en: "neurotransmitter", fa: "انتقال‌دهنده عصبی" },
  { id: 200466, level: "C1", pos: "noun", en: "dopamine", fa: "دوپامین" },
  { id: 200467, level: "C1", pos: "noun", en: "serotonin", fa: "سروتونین" },
  { id: 200468, level: "C1", pos: "noun", en: "oxytocin", fa: "اکسی‌توسین" },
  { id: 200469, level: "B2", pos: "noun", en: "hormone", fa: "هورمون" },
  { id: 200470, level: "B2", pos: "noun", en: "adrenaline", fa: "آدرنالین" },
  { id: 200471, level: "B2", pos: "noun", en: "mindset", fa: "طرز فکر" },
  { id: 200472, level: "B2", pos: "noun", en: "attitude", fa: "نگرش" },
  { id: 200473, level: "B2", pos: "noun", en: "belief", fa: "باور" },
  { id: 200474, level: "B2", pos: "noun", en: "perspective", fa: "چشم‌انداز (ذهنی)" },
  { id: 200475, level: "B2", pos: "adjective", en: "mental", fa: "ذهنی" },
  { id: 200476, level: "B2", pos: "noun", en: "psychosomatic", fa: "روان‌تنی" },
  { id: 200477, level: "C1", pos: "noun", en: "dissociation", fa: "گسستگی" },
  { id: 200478, level: "C1", pos: "noun", en: "projection", fa: "فرافکنی" },
  { id: 200479, level: "C1", pos: "noun", en: "denial", fa: "انکار" },
  { id: 200480, level: "C1", pos: "noun", en: "repression", fa: "سرکوب" },
  { id: 200481, level: "C1", pos: "noun", en: "sublimation", fa: "تصعید" },
  { id: 200482, level: "B2", pos: "noun", en: "coping", fa: "مقابله" },
  { id: 200483, level: "B2", pos: "noun", en: "resilience", fa: "تاب‌آوری" },
  { id: 200484, level: "C1", pos: "noun", en: "optimism", fa: "خوش‌بینی" },
  { id: 200485, level: "B2", pos: "noun", en: "pessimism", fa: "بدبینی" },
  { id: 200486, level: "B2", pos: "noun", en: "motivation", fa: "انگیزه" },
  { id: 200487, level: "B2", pos: "noun", en: "drive", fa: "انگیزه درونی" },
  { id: 200488, level: "B2", pos: "noun", en: "ambition", fa: "جاه‌طلبی" },
  { id: 200489, level: "C1", pos: "noun", en: "procrastination", fa: "تنبلی" },
  { id: 200490, level: "B2", pos: "noun", en: "burnout", fa: "فرسودگی شغلی" },
  { id: 200491, level: "B2", pos: "noun", en: "fatigue", fa: "خستگی" },
  { id: 200492, level: "B2", pos: "noun", en: "insomnia", fa: "بی‌خوابی" },
  { id: 200493, level: "B2", pos: "noun", en: "nightmare", fa: "کابوس" },
  { id: 200494, level: "B2", pos: "noun", en: "daydream", fa: "رویاپردازی" },
  { id: 200495, level: "B2", pos: "adjective", en: "conscious", fa: "هشیار" },
  { id: 200496, level: "B2", pos: "adjective", en: "unaware", fa: "ناآگاه" },
  { id: 200497, level: "C1", pos: "noun", en: "mindfulness", fa: "ذهن‌آگاهی" },
  { id: 200498, level: "B2", pos: "noun", en: "meditation", fa: "مراقبه" },
  { id: 200499, level: "B2", pos: "noun", en: "hypnosis", fa: "هیپنوتیزم" },
  { id: 200500, level: "C1", pos: "noun", en: "suggestion", fa: "تلقین" },
  { id: 200501, level: "B2", pos: "noun", en: "stereotype", fa: "کلیشه" },
  { id: 200502, level: "B2", pos: "noun", en: "prejudice", fa: "پیش‌داوری" },
  { id: 200503, level: "C1", pos: "noun", en: "bias", fa: "سوگیری" },
  { id: 200504, level: "B2", pos: "noun", en: "conformity", fa: "همنوایی" },
  { id: 200505, level: "B2", pos: "noun", en: "obedience", fa: "اطاعت" },
  { id: 200506, level: "C1", pos: "noun", en: "peer pressure", fa: "فشار همسالان" },
  { id: 200507, level: "B2", pos: "noun", en: "self-awareness", fa: "خودآگاهی" },
  { id: 200508, level: "B1", pos: "noun", en: "passport", fa: "پاسپورت" },
  { id: 200509, level: "B2", pos: "noun", en: "itinerary", fa: "برنامه سفر" },
  { id: 200510, level: "A2", pos: "noun", en: "tourist", fa: "گردشگر" },
  { id: 200511, level: "B1", pos: "noun", en: "hotel", fa: "هتل" },
  { id: 200512, level: "B1", pos: "noun", en: "resort", fa: "اقامتگاه تفریحی" },
  { id: 200513, level: "B2", pos: "noun", en: "lodge", fa: "کلبه (اقامتگاه)" },
  { id: 200514, level: "B1", pos: "noun", en: "hostel", fa: "خوابگاه" },
  { id: 200515, level: "B1", pos: "noun", en: "motel", fa: "متل" },
  { id: 200516, level: "B2", pos: "noun", en: "vacation", fa: "تعطیلات" },
  { id: 200517, level: "B1", pos: "noun", en: "holiday", fa: "تعطیلات" },
  { id: 200518, level: "B2", pos: "noun", en: "sightseeing", fa: "گشت‌وگذار" },
  { id: 200519, level: "B2", pos: "noun", en: "landmark", fa: "نقطه عطف (جاذبه)" },
  { id: 200520, level: "B2", pos: "noun", en: "monument", fa: "بنای تاریخی" },
  { id: 200521, level: "B2", pos: "noun", en: "basilica", fa: "بازیلیکا" },
  { id: 200522, level: "B1", pos: "noun", en: "gallery", fa: "گالری" },
  { id: 200523, level: "B2", pos: "noun", en: "zoo", fa: "باغ وحش" },
  { id: 200524, level: "B1", pos: "noun", en: "park", fa: "پارک" },
  { id: 200525, level: "B2", pos: "noun", en: "waterfall", fa: "آبشار" },
  { id: 200526, level: "B2", pos: "noun", en: "canyon", fa: "دره" },
  { id: 200527, level: "B2", pos: "noun", en: "beach", fa: "ساحل" },
  { id: 200528, level: "B1", pos: "noun", en: "mountain", fa: "کوهستان" },
  { id: 200529, level: "B2", pos: "noun", en: "valley", fa: "دره (میان کوه)" },
  { id: 200530, level: "A2", pos: "noun", en: "lake", fa: "دریاچه" },
  { id: 200531, level: "A2", pos: "noun", en: "river", fa: "رودخانه" },
  { id: 200532, level: "B1", pos: "noun", en: "island", fa: "جزیره" },
  { id: 200533, level: "B1", pos: "noun", en: "coast", fa: "ساحل (خط ساحلی)" },
  { id: 200534, level: "B2", pos: "noun", en: "port", fa: "بندر" },
  { id: 200535, level: "B2", pos: "noun", en: "harbor", fa: "اسکله" },
  { id: 200536, level: "B2", pos: "noun", en: "ferry", fa: "کشتی (مسافری)" },
  { id: 200537, level: "B2", pos: "noun", en: "cruise", fa: "سفر دریایی" },
  { id: 200538, level: "B1", pos: "noun", en: "journey", fa: "سفر" },
  { id: 200539, level: "B1", pos: "noun", en: "trip", fa: "مسافرت" },
  { id: 200540, level: "B1", pos: "noun", en: "departure", fa: "اعزام (پرواز)" },
  { id: 200541, level: "B1", pos: "noun", en: "arrival", fa: "ورود" },
  { id: 200542, level: "B1", pos: "noun", en: "gate", fa: "گیت" },
  { id: 200543, level: "B1", pos: "noun", en: "terminal", fa: "ترمینال" },
  { id: 200544, level: "A2", pos: "noun", en: "luggage", fa: "چمدان" },
  { id: 200545, level: "B1", pos: "noun", en: "baggage", fa: "بار (مسافر)" },
  { id: 200546, level: "B1", pos: "verb", en: "board", fa: "سوار شدن" },
  { id: 200547, level: "B1", pos: "verb", en: "disembark", fa: "پیاده شدن" },
  { id: 200548, level: "B2", pos: "noun", en: "layover", fa: "ترانزیت" },
  { id: 200549, level: "B2", pos: "noun", en: "stopover", fa: "توقف بین راه" },
  { id: 200550, level: "B2", pos: "noun", en: "destination", fa: "مقصد" },
  { id: 200551, level: "B1", pos: "noun", en: "traveler", fa: "مسافر" },
  { id: 200552, level: "B1", pos: "noun", en: "guide", fa: "راهنما" },
  { id: 200553, level: "B2", pos: "noun", en: "tour", fa: "تور" },
  { id: 200554, level: "B2", pos: "verb", en: "escort", fa: "همراهی کردن" },
  { id: 200555, level: "B2", pos: "noun", en: "customs", fa: "رسوم (و گمرک)" },
  { id: 200556, level: "B1", pos: "noun", en: "exchange rate", fa: "نرخ ارز" },
  { id: 200557, level: "B1", pos: "noun", en: "souvenir", fa: "سوغات" },
  { id: 200558, level: "B2", pos: "noun", en: "handicraft", fa: "صنایع دستی" },
  { id: 200559, level: "B1", pos: "noun", en: "cuisine", fa: "آشپزی (محلی)" },
  { id: 200560, level: "B2", pos: "noun", en: "delicacy", fa: "خوراک لذیذ" },
  { id: 200561, level: "B2", pos: "noun", en: "hospitality", fa: "میهمان‌نوازی" },
  { id: 200562, level: "B2", pos: "adjective", en: "picturesque", fa: "چشم‌انداز زیبا" },
  { id: 200563, level: "B2", pos: "adjective", en: "scenic", fa: "سرسبز (منظره)" },
  { id: 200564, level: "B2", pos: "adjective", en: "touristy", fa: "پر از گردشگر" },
  { id: 200565, level: "B2", pos: "noun", en: "off-season", fa: "فصل کم‌گردشگر" },
  { id: 200566, level: "B1", pos: "noun", en: "peak season", fa: "فصل اوج" },
  { id: 200567, level: "B1", pos: "noun", en: "booking", fa: "رزرو" },
  { id: 200568, level: "B1", pos: "verb", en: "reserve", fa: "رزرو کردن" },
  { id: 200569, level: "B2", pos: "noun", en: "cancellation", fa: "لغو" },
  { id: 200570, level: "B2", pos: "noun", en: "refund", fa: "استرداد پول" },
  { id: 200571, level: "B2", pos: "noun", en: "deposit", fa: "بیعانه" },
  { id: 200572, level: "A2", pos: "noun", en: "map", fa: "نقشه" },
  { id: 200573, level: "B1", pos: "noun", en: "compass", fa: "قطب نما" },
  { id: 200574, level: "B2", pos: "noun", en: "backpack", fa: "کوله پشتی" },
  { id: 200575, level: "B2", pos: "noun", en: "hiking", fa: "پیاده‌روی در طبیعت" },
  { id: 200576, level: "B2", pos: "noun", en: "camping", fa: "کمپینگ" },
  { id: 200577, level: "B2", pos: "noun", en: "trekking", fa: "ترکینگ" },
  { id: 200578, level: "B2", pos: "noun", en: "safari", fa: "سافاری" },
  { id: 200579, level: "B2", pos: "noun", en: "shuttle", fa: "اتوبوس (رفت و برگشت)" },
  { id: 200580, level: "B2", pos: "noun", en: "cab", fa: "تاکسی" },
  { id: 200581, level: "B1", pos: "noun", en: "rental", fa: "اجاره (ماشین)" },
  { id: 200582, level: "B2", pos: "noun", en: "milestone", fa: "نقطه عطف (جاده)" },
  { id: 200583, level: "B2", pos: "noun", en: "viewpoint", fa: "چشم‌انداز" },
  { id: 200584, level: "B2", pos: "noun", en: "sunset", fa: "غروب آفتاب" },
  { id: 200585, level: "B2", pos: "noun", en: "sunrise", fa: "طلوع آفتاب" },
  { id: 200586, level: "B1", pos: "noun", en: "oasis", fa: "واحه" },
  { id: 200587, level: "B2", pos: "noun", en: "desert", fa: "بیابان" },
  { id: 200588, level: "B2", pos: "noun", en: "rainforest", fa: "جنگل بارانی" },
  { id: 200589, level: "B2", pos: "noun", en: "glacier", fa: "یخچال طبیعی" },
  { id: 200590, level: "B2", pos: "noun", en: "fjord", fa: "فیورد" },
  { id: 200591, level: "B2", pos: "noun", en: "archipelago", fa: "مجمع‌الجزایر" },
  { id: 200592, level: "B2", pos: "noun", en: "peninsula", fa: "شبه‌جزیره" },
  { id: 200593, level: "B2", pos: "noun", en: "cape", fa: "دماغه" },
  { id: 200594, level: "B2", pos: "noun", en: "jungle", fa: "جنگل (گرمسیری)" },
  { id: 200595, level: "B2", pos: "noun", en: "savanna", fa: "ساوانا" },
  { id: 200596, level: "B2", pos: "noun", en: "shrine", fa: "زیارتگاه" },
  { id: 200597, level: "B2", pos: "noun", en: "monastery", fa: "صومعه" },
  { id: 200598, level: "B2", pos: "noun", en: "pilgrimage", fa: "زیارت" },
  { id: 200599, level: "B2", pos: "adjective", en: "exotic", fa: "عجیب و غریب (خارجی)" },
  { id: 200600, level: "B2", pos: "noun", en: "adventure", fa: "ماجراجویی" },
  { id: 200601, level: "B2", pos: "noun", en: "glamping", fa: "کمپینگ لوکس" },
  { id: 200602, level: "B2", pos: "noun", en: "all-inclusive", fa: "همه‌شامل" },
  { id: 200603, level: "B2", pos: "noun", en: "boutique hotel", fa: "هتل بوتیک" },
  { id: 200604, level: "B2", pos: "noun", en: "guesthouse", fa: "مهمان‌خانه" },
  { id: 200605, level: "B1", pos: "noun", en: "homestay", fa: "اقامت در خانه" },
  { id: 200606, level: "B1", pos: "noun", en: "travel agency", fa: "آژانس مسافرتی" },
  { id: 200607, level: "B2", pos: "noun", en: "bucket list", fa: "لیست آرزوها (سفر)" },
  { id: 200608, level: "A2", pos: "noun", en: "death", fa: "مرگ" },
  { id: 200609, level: "A2", pos: "verb", en: "die", fa: "مردن" },
  { id: 200610, level: "B1", pos: "noun", en: "funeral", fa: "مراسم خاکسپاری" },
  { id: 200611, level: "B1", pos: "noun", en: "coffin", fa: "تابوت" },
  { id: 200612, level: "B2", pos: "noun", en: "grave", fa: "قبر" },
  { id: 200613, level: "B1", pos: "noun", en: "cemetery", fa: "قبرستان" },
  { id: 200614, level: "B1", pos: "noun", en: "graveyard", fa: "گورستان" },
  { id: 200615, level: "B2", pos: "noun", en: "tomb", fa: "آرامگاه" },
  { id: 200616, level: "B2", pos: "noun", en: "mausoleum", fa: "مقبره" },
  { id: 200617, level: "B1", pos: "noun", en: "casket", fa: "تابوت (آمریکایی)" },
  { id: 200618, level: "B2", pos: "noun", en: "urn", fa: "خاکستردان" },
  { id: 200619, level: "B2", pos: "noun", en: "ashes", fa: "خاکستر" },
  { id: 200620, level: "B1", pos: "verb", en: "bury", fa: "دفن کردن" },
  { id: 200621, level: "B2", pos: "verb", en: "cremate", fa: "سوزاندن (جسد)" },
  { id: 200622, level: "B2", pos: "noun", en: "cremation", fa: "سوزاندن (مراسم)" },
  { id: 200623, level: "C1", pos: "noun", en: "embalm", fa: "مومیایی کردن" },
  { id: 200624, level: "C1", pos: "noun", en: "mummification", fa: "مومیایی" },
  { id: 200625, level: "B2", pos: "noun", en: "wake", fa: "بیداری (مراسم قبل از خاکسپاری)" },
  { id: 200626, level: "B2", pos: "noun", en: "vigil", fa: "شب‌زنده‌داری" },
  { id: 200627, level: "B1", pos: "noun", en: "mourning", fa: "سوگواری" },
  { id: 200628, level: "B1", pos: "verb", en: "mourn", fa: "سوگواری کردن" },
  { id: 200629, level: "B2", pos: "noun", en: "grief", fa: "اندوه" },
  { id: 200630, level: "B2", pos: "adjective", en: "grieving", fa: "داغ‌دار" },
  { id: 200631, level: "C1", pos: "noun", en: "bereavement", fa: "سوگ (از دست دادن عزیز)" },
  { id: 200632, level: "C1", pos: "adjective", en: "bereaved", fa: "داغ‌دیده" },
  { id: 200633, level: "B2", pos: "noun", en: "sorrow", fa: "غم" },
  { id: 200634, level: "B2", pos: "noun", en: "lament", fa: "مرثیه" },
  { id: 200635, level: "C1", pos: "noun", en: "elegy", fa: "سوگ‌سروده" },
  { id: 200636, level: "C1", pos: "noun", en: "epitaph", fa: "کتیبه روی قبر" },
  { id: 200637, level: "B2", pos: "noun", en: "headstone", fa: "سنگ قبر" },
  { id: 200638, level: "B2", pos: "noun", en: "tombstone", fa: "سنگ مزار" },
  { id: 200639, level: "C1", pos: "noun", en: "morgue", fa: "سردخانه" },
  { id: 200640, level: "C1", pos: "noun", en: "autopsy", fa: "کالبدشکافی" },
  { id: 200641, level: "C1", pos: "noun", en: "postmortem", fa: "پس از مرگ" },
  { id: 200642, level: "B2", pos: "adjective", en: "mortal", fa: "فانی" },
  { id: 200643, level: "C1", pos: "adjective", en: "immortal", fa: "جاودان" },
  { id: 200644, level: "C1", pos: "noun", en: "mortality", fa: "مرگ‌و‌میر" },
  { id: 200645, level: "B2", pos: "noun", en: "fatality", fa: "تلفات (مرگبار)" },
  { id: 200646, level: "B2", pos: "adjective", en: "fatal", fa: "کشنده" },
  { id: 200647, level: "B2", pos: "adjective", en: "lethal", fa: "مهلك" },
  { id: 200648, level: "C1", pos: "adjective", en: "morbid", fa: "مرگ‌آلود (غیرطبیعی)" },
  { id: 200649, level: "C1", pos: "noun", en: "necrology", fa: "درگذشتگان" },
  { id: 200650, level: "C1", pos: "noun", en: "obituary", fa: "آگهی ترحیم" },
  { id: 200651, level: "B2", pos: "noun", en: "eulogy", fa: "سخنرانی در مدح متوفی" },
  { id: 200652, level: "B2", pos: "noun", en: "pallbearer", fa: "حامل تابوت" },
  { id: 200653, level: "C1", pos: "noun", en: "hearse", fa: "ماشین نعش‌کشی" },
  { id: 200654, level: "C1", pos: "noun", en: "shroud", fa: "کفن" },
  { id: 200655, level: "C1", pos: "noun", en: "wreath", fa: "تاج گل (مراسم)" },
  { id: 200656, level: "B2", pos: "noun", en: "condolence", fa: "تسلیت" },
  { id: 200657, level: "B1", pos: "verb", en: "condole", fa: "تسلیت گفتن" },
  { id: 200658, level: "B2", pos: "noun", en: "consolation", fa: "تسلی" },
  { id: 200659, level: "C1", pos: "noun", en: "afterlife", fa: "زندگی پس از مرگ" },
  { id: 200660, level: "C1", pos: "noun", en: "reincarnation", fa: "تناسخ" },
  { id: 200661, level: "C1", pos: "noun", en: "soul", fa: "روح" },
  { id: 200662, level: "B2", pos: "noun", en: "spirit", fa: "روح (نامرئی)" },
  { id: 200663, level: "B2", pos: "noun", en: "ghost", fa: "شبح" },
  { id: 200664, level: "C1", pos: "noun", en: "phantom", fa: "خیال" },
  { id: 200665, level: "C1", pos: "verb", en: "perish", fa: "هلاک شدن" },
  { id: 200666, level: "C1", pos: "verb", en: "succumb", fa: "تسلیم شدن (در برابر مرگ)" },
  { id: 200667, level: "B2", pos: "verb", en: "expire", fa: "درگذشتن" },
  { id: 200668, level: "B1", pos: "verb", en: "pass away", fa: "فوت کردن" },
  { id: 200669, level: "B1", pos: "verb", en: "depart", fa: "درگذشتن (ادبی)" },
  { id: 200670, level: "C1", pos: "noun", en: "demise", fa: "مرگ (رسمی)" },
  { id: 200671, level: "C1", pos: "noun", en: "decease", fa: "وفات" },
  { id: 200672, level: "B2", pos: "noun", en: "lifespan", fa: "طول عمر" },
  { id: 200673, level: "B2", pos: "noun", en: "life expectancy", fa: "امید به زندگی" },
  { id: 200674, level: "B2", pos: "adjective", en: "stillborn", fa: "مرده‌زاد" },
  { id: 200675, level: "C1", pos: "noun", en: "stillbirth", fa: "مرده‌زایی" },
  { id: 200676, level: "B2", pos: "noun", en: "miscarriage", fa: "سقط خودبه‌خودی" },
  { id: 200677, level: "C1", pos: "noun", en: "euthanasia", fa: "مرگ خودخواسته" },
  { id: 200678, level: "C1", pos: "noun", en: "assisted suicide", fa: "خودکشی کمکی" },
  { id: 200679, level: "C1", pos: "noun", en: "capital punishment", fa: "اعدام" },
  { id: 200680, level: "B2", pos: "noun", en: "execution", fa: "اعدام (اجرای حکم)" },
  { id: 200681, level: "C1", pos: "noun", en: "martyrdom", fa: "شهادت" },
  { id: 200682, level: "B2", pos: "noun", en: "sacrifice", fa: "فداکاری" },
  { id: 200683, level: "C1", pos: "adjective", en: "macabre", fa: "وحشت‌انگیز (مرگ)" },
  { id: 200684, level: "C1", pos: "adjective", en: "grim", fa: "تلخ (مرگبار)" },
  { id: 200685, level: "B2", pos: "noun", en: "grave digger", fa: "قبرکن" },
  { id: 200686, level: "B2", pos: "noun", en: "undertaker", fa: "تدارک‌کننده مراسم خاکسپاری" },
  { id: 200687, level: "C1", pos: "noun", en: "mortician", fa: "متخصص کفن و دفن" },
  { id: 200688, level: "B2", pos: "verb", en: "inter", fa: "دفن کردن (رسمی)" },
  { id: 200689, level: "B2", pos: "noun", en: "interment", fa: "خاکسپاری" },
  { id: 200690, level: "B1", pos: "noun", en: "memorial", fa: "یادبود" },
  { id: 200691, level: "C1", pos: "noun", en: "necropolis", fa: "شهر مردگان" },
  { id: 200692, level: "C1", pos: "noun", en: "catacomb", fa: "سردابه" },
  { id: 200693, level: "C1", pos: "noun", en: "crypt", fa: "طاق (زیرزمینی)" },
  { id: 200694, level: "C1", pos: "noun", en: "sarcophagus", fa: "تابوت سنگی" },
  { id: 200695, level: "B2", pos: "noun", en: "pyre", fa: "هیزم (برای سوزاندن)" },
  { id: 200696, level: "C1", pos: "noun", en: "requiem", fa: "مرثیه (مذهبی)" },
  { id: 200697, level: "C1", pos: "noun", en: "dirge", fa: "نوحه" },
  { id: 200698, level: "C1", pos: "noun", en: "threnody", fa: "سرود سوگ" },
  { id: 200699, level: "C1", pos: "verb", en: "lament", fa: "ناله سر دادن" },
  { id: 200700, level: "B2", pos: "noun", en: "weeping", fa: "گریه (سوزناک)" },
  { id: 200701, level: "C1", pos: "adjective", en: "funereal", fa: "مرگ‌بار (سوگوارانه)" },
  { id: 200702, level: "C1", pos: "noun", en: "sepulcher", fa: "آرامگاه" },
  { id: 200703, level: "C1", pos: "noun", en: "cenotaph", fa: "یادبود (بدون جسد)" },
  { id: 200704, level: "B2", pos: "noun", en: "procession", fa: "دسته‌روی (مراسم)" },
  { id: 200705, level: "B2", pos: "noun", en: "pall", fa: "پارچه روی تابوت" },
  { id: 200706, level: "C1", pos: "noun", en: "obsequies", fa: "مراسم خاکسپاری (رسمی)" },
  { id: 200707, level: "B2", pos: "noun", en: "wreath-laying", fa: "گل‌گذاری" },
  { id: 200708, level: "B1", pos: "noun", en: "memorial stone", fa: "سنگ یادبود" },
  { id: 200709, level: "B2", pos: "adjective", en: "mournful", fa: "سوگوار" },
  { id: 200710, level: "B2", pos: "adjective", en: "somber", fa: "غمگین (رنگ تیره)" },
];
