export const NEWS_WORDS = [
  { id: 100062, level: "C1", pos: "noun", en: "activist", fa: "فعال" },
  { id: 100128, level: "B1", pos: "noun", en: "agreement", fa: "توافق" },
  { id: 100133, level: "B2", pos: "noun", en: "aid", fa: "کمک" },
  { id: 100157, level: "C1", pos: "noun", en: "alliance", fa: "اتحاد" },
  { id: 100178, level: "C1", pos: "noun", en: "ambassador", fa: "سفیر" },
  { id: 100183, level: "C1", pos: "noun", en: "amendment", fa: "اصلاحیه" },
  { id: 100204, level: "B1", pos: "verb", en: "announce", fa: "اعلام کردن" },
  { id: 100205, level: "B1", pos: "noun", en: "announcement", fa: "اعلامیه" },
  { id: 100268, level: "A2", pos: "noun", en: "army", fa: "ارتش" },
  { id: 100273, level: "B1", pos: "noun", en: "arrest", fa: "دستگیری" },
  { id: 100322, level: "A2", pos: "noun", en: "attack", fa: "حمله" },
  { id: 100342, level: "B1", pos: "noun", en: "authority", fa: "مرجع" },
  { id: 100383, level: "A1", pos: "noun", en: "bank", fa: "بانک" },
  { id: 100405, level: "B1", pos: "noun", en: "battle", fa: "نبرد" },
  { id: 100461, level: "A1", pos: "noun", en: "bill", fa: "صورتحساب" },
  { id: 100500, level: "B1", pos: "noun", en: "bomb", fa: "بمب" },
  { id: 100510, level: "B1", pos: "noun", en: "border", fa: "مرز" },
  { id: 100565, level: "B2", pos: "noun", en: "budget", fa: "بودجه" },
  { id: 100581, level: "A1", pos: "noun", en: "business", fa: "کسب و کار" },
  { id: 100601, level: "B1", pos: "noun", en: "campaign", fa: "کارزار" },
  { id: 100608, level: "B1", pos: "noun", en: "candidate", fa: "نامزد" },
  { id: 100616, level: "A1", pos: "adjective", en: "capital", fa: "سرمایه" },
  { id: 100622, level: "B2", pos: "noun", en: "carbon", fa: "کربن" },
  { id: 100642, level: "C1", pos: "noun", en: "casualty", fa: "تلفات" },
  { id: 100687, level: "A2", pos: "noun", en: "charity", fa: "خیریه" },
  { id: 100717, level: "A2", pos: "noun", en: "church", fa: "کلیسا" },
  { id: 100728, level: "A1", pos: "noun", en: "city", fa: "شهر" },
  { id: 100752, level: "A2", pos: "noun", en: "climate", fa: "آب و هوا" },
  { id: 100772, level: "C1", pos: "noun", en: "coalition", fa: "ائتلاف" },
  { id: 100821, level: "B2", pos: "noun", en: "committee", fa: "کمیته" },
  { id: 100828, level: "A2", pos: "noun", en: "community", fa: "جامعه" },
  { id: 100830, level: "A1", pos: "noun", en: "company", fa: "شرکت" },
  { id: 100897, level: "B2", pos: "noun", en: "conflict", fa: "درگیری" },
  { id: 100919, level: "B2", pos: "noun", en: "conservation", fa: "حفاظت" },
  { id: 100936, level: "C1", pos: "noun", en: "constitution", fa: "قانون اساسی" },
  { id: 100945, level: "B1", pos: "noun", en: "consumer", fa: "مصرف کننده" },
  { id: 101004, level: "B2", pos: "noun", en: "corporation", fa: "شرکت" },
  { id: 101016, level: "C1", pos: "noun", en: "corruption", fa: "فساد" },
  { id: 101017, level: "A1", pos: "noun", en: "cost", fa: "هزینه" },
  { id: 101023, level: "B2", pos: "noun", en: "council", fa: "شورا" },
  { id: 101031, level: "A1", pos: "noun", en: "country", fa: "کشور" },
  { id: 101034, level: "C1", pos: "noun", en: "coup", fa: "کودتا" },
  { id: 101038, level: "B1", pos: "noun", en: "court", fa: "دادگاه" },
  { id: 101062, level: "A2", pos: "noun", en: "crime", fa: "جرم" },
  { id: 101063, level: "A2", pos: "noun", en: "criminal", fa: "مجرم" },
  { id: 101064, level: "B2", pos: "noun", en: "crisis", fa: "بحران" },
  { id: 101088, level: "A1", pos: "noun", en: "culture", fa: "فرهنگ" },
  { id: 101095, level: "B1", pos: "noun", en: "currency", fa: "واحد پول" },
  { id: 101119, level: "A2", pos: "noun", en: "danger", fa: "خطر" },
  { id: 101124, level: "A2", pos: "noun", en: "data", fa: "داده" },
  { id: 101139, level: "B2", pos: "noun", en: "debt", fa: "بدهی" },
  { id: 101149, level: "C1", pos: "noun", en: "declaration", fa: "اعلامیه" },
  { id: 101150, level: "B2", pos: "verb", en: "declare", fa: "اعلام کردن" },
  { id: 101164, level: "B2", pos: "noun", en: "defence", fa: "دفاع" },
  { id: 101188, level: "B2", pos: "noun", en: "demand", fa: "تقاضا" },
  { id: 101189, level: "B2", pos: "noun", en: "democracy", fa: "دموکراسی" },
  { id: 101190, level: "B2", pos: "adjective", en: "democratic", fa: "دموکراتیک" },
  { id: 101193, level: "B2", pos: "noun", en: "demonstration", fa: "تظاهرات" },
  { id: 101250, level: "B1", pos: "noun", en: "development", fa: "توسعه" },
  { id: 101262, level: "C1", pos: "noun", en: "dictator", fa: "دیکتاتور" },
  { id: 101281, level: "C1", pos: "noun", en: "diplomat", fa: "دیپلمات" },
  { id: 101282, level: "C1", pos: "adjective", en: "diplomatic", fa: "دیپلماتیک" },
  { id: 101300, level: "A2", pos: "noun", en: "disaster", fa: "فاجعه" },
  { id: 101314, level: "C1", pos: "noun", en: "discrimination", fa: "تبعیض" },
  { id: 101317, level: "A2", pos: "noun", en: "disease", fa: "بیماری" },
  { id: 101357, level: "A1", pos: "noun", en: "doctor", fa: "دکتر" },
  { id: 101370, level: "B2", pos: "noun", en: "donation", fa: "کمک مالی" },
  { id: 101400, level: "B2", pos: "noun", en: "drought", fa: "خشکسالی" },
  { id: 101426, level: "B1", pos: "noun", en: "earthquake", fa: "زلزله" },
  { id: 101435, level: "B1", pos: "adjective", en: "economic", fa: "اقتصادی" },
  { id: 101437, level: "B2", pos: "noun", en: "economist", fa: "اقتصاددان" },
  { id: 101438, level: "B1", pos: "noun", en: "economy", fa: "اقتصاد" },
  { id: 101446, level: "A2", pos: "noun", en: "education", fa: "آموزش" },
  { id: 101466, level: "B2", pos: "verb", en: "elect", fa: "انتخاب کردن" },
  { id: 101467, level: "B1", pos: "noun", en: "election", fa: "انتخابات" },
  { id: 101490, level: "C1", pos: "noun", en: "embassy", fa: "سفارت" },
  { id: 101496, level: "B1", pos: "noun", en: "emergency", fa: "اضطراری" },
  { id: 101497, level: "B2", pos: "noun", en: "emission", fa: "انتشار" },
  { id: 101508, level: "B1", pos: "noun", en: "employment", fa: "اشتغال" },
  { id: 101526, level: "A2", pos: "noun", en: "energy", fa: "انرژی" },
  { id: 101563, level: "A2", pos: "noun", en: "environment", fa: "محیط زیست" },
  { id: 101564, level: "B1", pos: "adjective", en: "environmental", fa: "محیط زیستی" },
  { id: 101565, level: "C1", pos: "noun", en: "epidemic", fa: "همه گیری" },
  { id: 101568, level: "C1", pos: "noun", en: "equality", fa: "برابری" },
  { id: 101594, level: "C1", pos: "verb", en: "evacuate", fa: "تخلیه کردن" },
  { id: 101678, level: "B1", pos: "noun", en: "export", fa: "صادرات" },
  { id: 101704, level: "A2", pos: "noun", en: "factory", fa: "کارخانه" },
  { id: 101778, level: "B2", pos: "noun", en: "finance", fa: "مالی" },
  { id: 101779, level: "B1", pos: "adjective", en: "financial", fa: "مالی" },
  { id: 101785, level: "A1", pos: "noun", en: "fire", fa: "آتش" },
  { id: 101815, level: "B1", pos: "noun", en: "flood", fa: "سیل" },
  { id: 101832, level: "A1", pos: "noun", en: "food", fa: "غذا" },
  { id: 101882, level: "B2", pos: "noun", en: "freedom", fa: "آزادی" },
  { id: 101937, level: "A2", pos: "noun", en: "gas", fa: "گاز" },
  { id: 101944, level: "B2", pos: "noun", en: "gender", fa: "جنسیت" },
  { id: 101974, level: "B1", pos: "adjective", en: "global", fa: "جهانی" },
  { id: 101993, level: "A2", pos: "noun", en: "government", fa: "دولت" },
  { id: 101994, level: "B2", pos: "noun", en: "governor", fa: "فرماندار" },
  { id: 102029, level: "B1", pos: "noun", en: "growth", fa: "رشد" },
  { id: 102041, level: "A2", pos: "noun", en: "gun", fa: "تفنگ" },
  { id: 102086, level: "A1", pos: "noun", en: "health", fa: "سلامت" },
  { id: 102147, level: "B2", pos: "adjective", en: "homeless", fa: "بی خانمان" },
  { id: 102161, level: "A1", pos: "noun", en: "hospital", fa: "بیمارستان" },
  { id: 102171, level: "B2", pos: "noun", en: "housing", fa: "مسکن" },
  { id: 102176, level: "C1", pos: "adjective", en: "humanitarian", fa: "بشردوستانه" },
  { id: 102182, level: "B2", pos: "noun", en: "hunger", fa: "گرسنگی" },
  { id: 102186, level: "B1", pos: "noun", en: "hurricane", fa: "طوفان" },
  { id: 102210, level: "B1", pos: "adjective", en: "illegal", fa: "غیرقانونی" },
  { id: 102223, level: "B1", pos: "noun", en: "immigrant", fa: "مهاجر" },
  { id: 102224, level: "B2", pos: "noun", en: "immigration", fa: "مهاجرت" },
  { id: 102233, level: "B1", pos: "noun", en: "import", fa: "واردات" },
  { id: 102268, level: "B2", pos: "noun", en: "independence", fa: "استقلال" },
  { id: 102283, level: "A2", pos: "noun", en: "industry", fa: "صنعت" },
  { id: 102284, level: "C1", pos: "noun", en: "inequality", fa: "نابرابری" },
  { id: 102292, level: "B2", pos: "noun", en: "inflation", fa: "تورم" },
  { id: 102313, level: "B1", pos: "adjective", en: "injured", fa: "مجروح" },
  { id: 102385, level: "A2", pos: "adjective", en: "international", fa: "بین المللی" },
  { id: 102386, level: "A1", pos: "noun", en: "internet", fa: "اینترنت" },
  { id: 102393, level: "A1", pos: "noun", en: "interview", fa: "مصاحبه" },
  { id: 102405, level: "B2", pos: "noun", en: "investigation", fa: "تحقیق" },
  { id: 102407, level: "B2", pos: "noun", en: "investment", fa: "سرمایه گذاری" },
  { id: 102408, level: "B2", pos: "noun", en: "investor", fa: "سرمایه گذار" },
  { id: 102444, level: "A2", pos: "noun", en: "journalist", fa: "روزنامه نگار" },
  { id: 102447, level: "B1", pos: "noun", en: "judge", fa: "قاضی" },
  { id: 102459, level: "B2", pos: "noun", en: "justice", fa: "عدالت" },
  { id: 102487, level: "B2", pos: "noun", en: "labour", fa: "کار" },
  { id: 102516, level: "A2", pos: "noun", en: "law", fa: "قانون" },
  { id: 102525, level: "A2", pos: "noun", en: "leader", fa: "رهبر" },
  { id: 102526, level: "B2", pos: "noun", en: "leadership", fa: "رهبری" },
  { id: 102543, level: "B1", pos: "adjective", en: "legal", fa: "قانونی" },
  { id: 102546, level: "C1", pos: "noun", en: "legislation", fa: "قانون گذاری" },
  { id: 102687, level: "B2", pos: "noun", en: "manufacturing", fa: "تولید" },
  { id: 102698, level: "A1", pos: "noun", en: "market", fa: "بازار" },
  { id: 102723, level: "B2", pos: "noun", en: "mayor", fa: "شهردار" },
  { id: 102739, level: "A2", pos: "noun", en: "media", fa: "رسانه" },
  { id: 102740, level: "A2", pos: "adjective", en: "medical", fa: "پزشکی" },
  { id: 102742, level: "A2", pos: "noun", en: "medicine", fa: "پزشکی" },
  { id: 102766, level: "C1", pos: "noun", en: "merger", fa: "ادغام" },
  { id: 102779, level: "C1", pos: "noun", en: "migration", fa: "مهاجرت" },
  { id: 102783, level: "B2", pos: "adjective", en: "military", fa: "نظامی" },
  { id: 102796, level: "B2", pos: "noun", en: "minister", fa: "وزیر" },
  { id: 102799, level: "B2", pos: "noun", en: "minority", fa: "اقلیت" },
  { id: 102861, level: "A2", pos: "noun", en: "movement", fa: "حرکت" },
  { id: 102890, level: "B1", pos: "noun", en: "nation", fa: "ملت" },
  { id: 102891, level: "A2", pos: "adjective", en: "national", fa: "ملی" },
  { id: 102911, level: "B2", pos: "verb", en: "negotiate", fa: "مذاکره کردن" },
  { id: 102912, level: "B2", pos: "noun", en: "negotiation", fa: "مذاکره" },
  { id: 102927, level: "A1", pos: "noun", en: "news", fa: "اخبار" },
  { id: 102929, level: "A1", pos: "noun", en: "newspaper", fa: "روزنامه" },
  { id: 102977, level: "B1", pos: "adjective", en: "nuclear", fa: "هسته ای" },
  { id: 103023, level: "B1", pos: "adjective", en: "official", fa: "رسمی" },
  { id: 103027, level: "A2", pos: "noun", en: "oil", fa: "نفت" },
  { id: 103053, level: "B2", pos: "noun", en: "opposition", fa: "مخالفت" },
  { id: 103145, level: "B2", pos: "noun", en: "parliament", fa: "مجلس" },
  { id: 103176, level: "A2", pos: "noun", en: "patient", fa: "بیمار" },
  { id: 103183, level: "A2", pos: "noun", en: "peace", fa: "صلح" },
  { id: 103288, level: "A1", pos: "noun", en: "police", fa: "پلیس" },
  { id: 103290, level: "B1", pos: "noun", en: "policy", fa: "سیاست" },
  { id: 103292, level: "B1", pos: "adjective", en: "political", fa: "سیاسی" },
  { id: 103293, level: "B1", pos: "noun", en: "politician", fa: "سیاستمدار" },
  { id: 103294, level: "B1", pos: "noun", en: "politics", fa: "سیاست" },
  { id: 103296, level: "A2", pos: "noun", en: "pollution", fa: "آلودگی" },
  { id: 103303, level: "A2", pos: "noun", en: "population", fa: "جمعیت" },
  { id: 103327, level: "B1", pos: "noun", en: "poverty", fa: "فقر" },
  { id: 103373, level: "A2", pos: "noun", en: "president", fa: "رئیس جمهور" },
  { id: 103375, level: "B1", pos: "noun", en: "press", fa: "مطبوعات" },
  { id: 103389, level: "A1", pos: "noun", en: "price", fa: "قیمت" },
  { id: 103404, level: "A2", pos: "noun", en: "prison", fa: "زندان" },
  { id: 103455, level: "C1", pos: "noun", en: "propaganda", fa: "تبلیغات" },
  { id: 103473, level: "B1", pos: "noun", en: "protest", fa: "اعتراض" },
  { id: 103535, level: "B2", pos: "noun", en: "racism", fa: "نژادپرستی" },
  { id: 103596, level: "B2", pos: "noun", en: "recession", fa: "رکود" },
  { id: 103622, level: "C1", pos: "noun", en: "reform", fa: "اصلاحات" },
  { id: 103624, level: "B2", pos: "noun", en: "refugee", fa: "پناهنده" },
  { id: 103630, level: "C1", pos: "noun", en: "regime", fa: "رژیم" },
  { id: 103631, level: "A2", pos: "noun", en: "region", fa: "منطقه" },
  { id: 103632, level: "B2", pos: "adjective", en: "regional", fa: "منطقه ای" },
  { id: 103639, level: "B2", pos: "noun", en: "regulation", fa: "مقررات" },
  { id: 103664, level: "B1", pos: "noun", en: "religion", fa: "مذهب" },
  { id: 103665, level: "B1", pos: "adjective", en: "religious", fa: "مذهبی" },
  { id: 103692, level: "A1", pos: "noun", en: "report", fa: "گزارش" },
  { id: 103694, level: "A2", pos: "noun", en: "reporter", fa: "گزارشگر" },
  { id: 103706, level: "B2", pos: "noun", en: "rescue", fa: "نجات" },
  { id: 103707, level: "A2", pos: "noun", en: "research", fa: "تحقیق" },
  { id: 103724, level: "B1", pos: "noun", en: "resource", fa: "منبع" },
  { id: 103759, level: "B2", pos: "noun", en: "revolution", fa: "انقلاب" },
  { id: 103775, level: "B1", pos: "noun", en: "risk", fa: "خطر" },
  { id: 103833, level: "A2", pos: "noun", en: "salary", fa: "حقوق" },
  { id: 103852, level: "B2", pos: "noun", en: "scandal", fa: "رسوایی" },
  { id: 103864, level: "A1", pos: "noun", en: "school", fa: "مدرسه" },
  { id: 103865, level: "A1", pos: "noun", en: "science", fa: "علم" },
  { id: 103867, level: "A1", pos: "noun", en: "scientist", fa: "دانشمند" },
  { id: 103892, level: "B1", pos: "noun", en: "security", fa: "امنیت" },
  { id: 103908, level: "C1", pos: "noun", en: "senator", fa: "سناتور" },
  { id: 103983, level: "B2", pos: "noun", en: "shortage", fa: "کمبود" },
  { id: 104081, level: "A2", pos: "adjective", en: "social", fa: "اجتماعی" },
  { id: 104083, level: "A2", pos: "noun", en: "society", fa: "جامعه" },
  { id: 104089, level: "A2", pos: "noun", en: "soldier", fa: "سرباز" },
  { id: 104119, level: "C1", pos: "noun", en: "sovereignty", fa: "حاکمیت" },
  { id: 104131, level: "B2", pos: "noun", en: "species", fa: "گونه" },
  { id: 104163, level: "B2", pos: "noun", en: "spokesperson", fa: "سخنگو" },
  { id: 104200, level: "A1", pos: "noun", en: "statement", fa: "بیانیه" },
  { id: 104224, level: "B2", pos: "noun", en: "stock", fa: "سهام" },
  { id: 104230, level: "A2", pos: "noun", en: "storm", fa: "طوفان" },
  { id: 104248, level: "B2", pos: "noun", en: "strike", fa: "اعتصاب" },
  { id: 104259, level: "A1", pos: "noun", en: "student", fa: "دانشجو" },
  { id: 104311, level: "C1", pos: "noun", en: "summit", fa: "قله" },
  { id: 104322, level: "B1", pos: "noun", en: "supply", fa: "تأمین" },
  { id: 104395, level: "B1", pos: "noun", en: "tax", fa: "مالیات" },
  { id: 104400, level: "A1", pos: "noun", en: "teacher", fa: "معلم" },
  { id: 104407, level: "A2", pos: "noun", en: "technology", fa: "فناوری" },
  { id: 104412, level: "A1", pos: "noun", en: "television", fa: "تلویزیون" },
  { id: 104437, level: "B2", pos: "noun", en: "territory", fa: "قلمرو" },
  { id: 104439, level: "B2", pos: "noun", en: "terrorism", fa: "تروریسم" },
  { id: 104440, level: "B2", pos: "noun", en: "terrorist", fa: "تروریست" },
  { id: 104493, level: "B2", pos: "noun", en: "threat", fa: "تهدید" },
  { id: 104562, level: "B1", pos: "noun", en: "trade", fa: "تجارت" },
  { id: 104597, level: "B1", pos: "noun", en: "treatment", fa: "درمان" },
  { id: 104598, level: "C1", pos: "noun", en: "treaty", fa: "معاهده" },
  { id: 104602, level: "B2", pos: "noun", en: "trial", fa: "محاکمه" },
  { id: 104668, level: "B1", pos: "noun", en: "unemployment", fa: "بیکاری" },
  { id: 104677, level: "B1", pos: "noun", en: "union", fa: "اتحادیه" },
  { id: 104685, level: "A1", pos: "noun", en: "university", fa: "دانشگاه" },
  { id: 104759, level: "B1", pos: "noun", en: "victim", fa: "قربانی" },
  { id: 104769, level: "B2", pos: "noun", en: "violence", fa: "خشونت" },
  { id: 104773, level: "A2", pos: "noun", en: "virus", fa: "ویروس" },
  { id: 104787, level: "B1", pos: "noun", en: "vote", fa: "رأی" },
  { id: 104792, level: "B2", pos: "noun", en: "wage", fa: "دستمزد" },
  { id: 104800, level: "A2", pos: "noun", en: "war", fa: "جنگ" },
  { id: 104805, level: "B2", pos: "noun", en: "warming", fa: "گرمایش" },
  { id: 104814, level: "A1", pos: "noun", en: "water", fa: "آب" },
  { id: 104821, level: "B2", pos: "noun", en: "wealth", fa: "ثروت" },
  { id: 104823, level: "B1", pos: "noun", en: "weapon", fa: "سلاح" },
  { id: 104878, level: "B2", pos: "noun", en: "wildlife", fa: "حیات وحش" },
  { id: 104909, level: "A1", pos: "noun", en: "worker", fa: "کارگر" },
  { id: 104915, level: "A1", pos: "noun", en: "world", fa: "جهان" },
];
