export const SLANG_WORDS = [
  { id: 500001, level: "A2", pos: "slang", en: "ah", fa: "آه" },
  { id: 500002, level: "A2", pos: "slang", en: "asap", fa: "هرچه زودتر" },
  { id: 500003, level: "A2", pos: "slang", en: "bestie", fa: "بهترین دوست" },
  { id: 500004, level: "A2", pos: "slang", en: "bet", fa: "قبوله، باشه" },
  { id: 500005, level: "A2", pos: "slang", en: "brb", fa: "برمی‌گردم (be right back)" },
  { id: 500006, level: "A2", pos: "slang", en: "bro", fa: "داداش" },
  { id: 500007, level: "A2", pos: "slang", en: "btw", fa: "راستی" },
  { id: 500008, level: "A2", pos: "slang", en: "buddy", fa: "رفیق" },
  { id: 500009, level: "A2", pos: "slang", en: "bye", fa: "خداحافظ" },
  { id: 500010, level: "A2", pos: "slang", en: "chill", fa: "آروم، ریلکس" },
  { id: 500011, level: "A2", pos: "slang", en: "cmon", fa: "بیا دیگه" },
  { id: 500012, level: "A2", pos: "slang", en: "cool", fa: "خوبه، عالیه" },
  { id: 500013, level: "A2", pos: "slang", en: "cuz", fa: "چون (because)" },
  { id: 500014, level: "A2", pos: "slang", en: "dude", fa: "مرد حسابی" },
  { id: 500015, level: "A2", pos: "slang", en: "dunno", fa: "نمی‌دونم (don't know)" },
  { id: 500016, level: "A2", pos: "slang", en: "folks", fa: "رفقا" },
  { id: 500017, level: "A2", pos: "slang", en: "fyi", fa: "برای اطلاع‌تون" },
  { id: 500018, level: "A2", pos: "slang", en: "gimme", fa: "به من بده (give me)" },
  { id: 500019, level: "A2", pos: "slang", en: "gonna", fa: "می‌خوام (going to)" },
  { id: 500020, level: "A2", pos: "slang", en: "gotta", fa: "باید (have got to)" },
  { id: 500021, level: "A2", pos: "slang", en: "guys", fa: "بچه‌ها" },
  { id: 500022, level: "A2", pos: "slang", en: "hard pass", fa: "قاطعانه نه" },
  { id: 500023, level: "A2", pos: "slang", en: "hey", fa: "هی" },
  { id: 500024, level: "A2", pos: "slang", en: "highkey", fa: "کاملاً و آشکارا" },
  { id: 500025, level: "A2", pos: "slang", en: "hiya", fa: "سلام" },
  { id: 500026, level: "A2", pos: "slang", en: "hmm", fa: "هوم" },
  { id: 500027, level: "A2", pos: "slang", en: "idk", fa: "نمی‌دونم (I don't know)" },
  { id: 500028, level: "A2", pos: "slang", en: "imo", fa: "به نظر من" },
  { id: 500029, level: "A2", pos: "slang", en: "kinda", fa: "یه جورایی (kind of)" },
  { id: 500030, level: "A2", pos: "slang", en: "lemme", fa: "بذار من (let me)" },
  { id: 500031, level: "A2", pos: "slang", en: "lol", fa: "باحال، خنده‌دار" },
  { id: 500032, level: "A2", pos: "slang", en: "lowkey", fa: "تا حدی، بدون سروصدا" },
  { id: 500033, level: "A2", pos: "slang", en: "nah", fa: "نه بابا" },
  { id: 500034, level: "A2", pos: "slang", en: "no cap", fa: "جدی میگم، دروغ نیست" },
  { id: 500035, level: "A2", pos: "slang", en: "nope", fa: "نه" },
  { id: 500036, level: "A2", pos: "slang", en: "np", fa: "خواهش می‌کنم (no problem)" },
  { id: 500037, level: "A2", pos: "slang", en: "oh", fa: "اوه" },
  { id: 500038, level: "A2", pos: "slang", en: "ok", fa: "باشه" },
  { id: 500039, level: "A2", pos: "slang", en: "okay", fa: "خوب" },
  { id: 500040, level: "A2", pos: "slang", en: "omg", fa: "یا خدا (oh my god)" },
  { id: 500041, level: "A2", pos: "slang", en: "outta", fa: "از (out of)" },
  { id: 500042, level: "A2", pos: "slang", en: "pal", fa: "دوست" },
  { id: 500043, level: "A2", pos: "slang", en: "pls", fa: "لطفاً" },
  { id: 500044, level: "A2", pos: "slang", en: "prolly", fa: "احتمالاً (probably)" },
  { id: 500045, level: "A2", pos: "slang", en: "say less", fa: "قبوله، بیشتر توضیح نده" },
  { id: 500046, level: "A2", pos: "slang", en: "slay", fa: "عالی انجام دادن" },
  { id: 500047, level: "A2", pos: "slang", en: "sorta", fa: "تقریباً (sort of)" },
  { id: 500048, level: "A2", pos: "slang", en: "srsly", fa: "جدی (seriously)" },
  { id: 500049, level: "A2", pos: "slang", en: "ttyl", fa: "بعداً حرف می‌زنیم (talk to you later)" },
  { id: 500050, level: "A2", pos: "slang", en: "ty", fa: "ممنون (thank you)" },
  { id: 500051, level: "A2", pos: "slang", en: "uh-huh", fa: "آها" },
  { id: 500052, level: "A2", pos: "slang", en: "uh-uh", fa: "اوم" },
  { id: 500053, level: "A2", pos: "slang", en: "vibe", fa: "حس و حال کلی" },
  { id: 500054, level: "A2", pos: "slang", en: "wanna", fa: "می‌خوام (want to)" },
  { id: 500055, level: "A2", pos: "slang", en: "wow", fa: "واو" },
  { id: 500056, level: "A2", pos: "slang", en: "yeah", fa: "آره" },
  { id: 500057, level: "A2", pos: "slang", en: "yep", fa: "آره" },
  { id: 500058, level: "A2", pos: "slang", en: "yw", fa: "خواهش می‌کنم (you're welcome)" },
  { id: 500059, level: "B1", pos: "slang", en: "awesome", fa: "فوق‌العاده" },
  { id: 500060, level: "B1", pos: "slang", en: "awk", fa: "خجالت‌آور" },
  { id: 500061, level: "B1", pos: "slang", en: "bail", fa: "جا زدن، پیچوندن" },
  { id: 500062, level: "B1", pos: "slang", en: "bank", fa: "به پول اعتماد کردن" },
  { id: 500063, level: "B1", pos: "slang", en: "bargain", fa: "معامله خوب" },
  { id: 500064, level: "B1", pos: "slang", en: "basic", fa: "معمولی و بدون خلاقیت" },
  { id: 500065, level: "B1", pos: "slang", en: "beige flag", fa: "علامت خنثی" },
  { id: 500066, level: "B1", pos: "slang", en: "bff", fa: "بهترین دوست" },
  { id: 500067, level: "B1", pos: "slang", en: "bird", fa: "دختر (بریتانیایی)" },
  { id: 500068, level: "B1", pos: "slang", en: "block", fa: "بلاک کردن" },
  { id: 500069, level: "B1", pos: "slang", en: "blog", fa: "بلاگ" },
  { id: 500070, level: "B1", pos: "slang", en: "bloke", fa: "مرد" },
  { id: 500071, level: "B1", pos: "slang", en: "boss", fa: "استاد، عالی" },
  { id: 500072, level: "B1", pos: "slang", en: "brain fart", fa: "یکهو گیج شدن" },
  { id: 500073, level: "B1", pos: "slang", en: "brainiac", fa: "نابغه" },
  { id: 500074, level: "B1", pos: "slang", en: "bread", fa: "پول" },
  { id: 500075, level: "B1", pos: "slang", en: "breadcrumb", fa: "توجه کم" },
  { id: 500076, level: "B1", pos: "slang", en: "breadcrumbing", fa: "تکه‌تکه توجه دادن" },
  { id: 500077, level: "B1", pos: "slang", en: "break a leg", fa: "موفق باشی" },
  { id: 500078, level: "B1", pos: "slang", en: "bucket list", fa: "لیست کارهای آرزویی" },
  { id: 500079, level: "B1", pos: "slang", en: "bucks", fa: "دلار" },
  { id: 500080, level: "B1", pos: "slang", en: "bummed", fa: "ناراحت، افسرده" },
  { id: 500081, level: "B1", pos: "slang", en: "bummer", fa: "چه حیف" },
  { id: 500082, level: "B1", pos: "slang", en: "burn", fa: "سوزوندن (با کلام)" },
  { id: 500083, level: "B1", pos: "slang", en: "buzz", fa: "هیجان" },
  { id: 500084, level: "B1", pos: "slang", en: "cancel", fa: "طرد کردن" },
  { id: 500085, level: "B1", pos: "slang", en: "cap", fa: "دروغ" },
  { id: 500086, level: "B1", pos: "slang", en: "cash", fa: "پول نقد" },
  { id: 500087, level: "B1", pos: "slang", en: "catch feelings", fa: "ناخواسته احساسات عاشقانه پیدا کردن" },
  { id: 500088, level: "B1", pos: "slang", en: "catch up", fa: "به‌روز شدن" },
  { id: 500089, level: "B1", pos: "slang", en: "champ", fa: "قهرمان" },
  { id: 500090, level: "B1", pos: "slang", en: "chap", fa: "آقا" },
  { id: 500091, level: "B1", pos: "slang", en: "chatterbox", fa: "پرحرف" },
  { id: 500092, level: "B1", pos: "slang", en: "cheesy", fa: "تخمی، کلیشه‌ای" },
  { id: 500093, level: "B1", pos: "slang", en: "chick", fa: "دختر" },
  { id: 500094, level: "B1", pos: "slang", en: "chill out", fa: "آروم باش" },
  { id: 500095, level: "B1", pos: "slang", en: "chillax", fa: "آروم باش" },
  { id: 500096, level: "B1", pos: "slang", en: "clapback", fa: "پاسخ تند دادن" },
  { id: 500097, level: "B1", pos: "slang", en: "clique", fa: "دسته" },
  { id: 500098, level: "B1", pos: "slang", en: "corny", fa: "تخمی" },
  { id: 500099, level: "B1", pos: "slang", en: "couch potato", fa: "آدم تنبل" },
  { id: 500100, level: "B1", pos: "slang", en: "crap", fa: "چرندیات، مزخرف" },
  { id: 500101, level: "B1", pos: "slang", en: "crash", fa: "خوابیدن (جای کسی)" },
  { id: 500102, level: "B1", pos: "slang", en: "credit", fa: "اعتبار" },
  { id: 500103, level: "B1", pos: "slang", en: "crew", fa: "گروه" },
  { id: 500104, level: "B1", pos: "slang", en: "cringe", fa: "خجالت‌آور" },
  { id: 500105, level: "B1", pos: "slang", en: "cut it out", fa: "بس کن" },
  { id: 500106, level: "B1", pos: "slang", en: "d'oh", fa: "ای خدا" },
  { id: 500107, level: "B1", pos: "slang", en: "darn", fa: "ای وای" },
  { id: 500108, level: "B1", pos: "slang", en: "deadass", fa: "جدی جدی، بدون شوخی" },
  { id: 500109, level: "B1", pos: "slang", en: "deal", fa: "معامله" },
  { id: 500110, level: "B1", pos: "slang", en: "delusional", fa: "توهمی" },
  { id: 500111, level: "B1", pos: "slang", en: "diss", fa: "بی‌احترامی کردن" },
  { id: 500112, level: "B1", pos: "slang", en: "dms", fa: "پیام‌های مستقیم" },
  { id: 500113, level: "B1", pos: "slang", en: "dope", fa: "خیلی خوب" },
  { id: 500114, level: "B1", pos: "slang", en: "dough", fa: "پول" },
  { id: 500115, level: "B1", pos: "slang", en: "duh", fa: "معلومه" },
  { id: 500116, level: "B1", pos: "slang", en: "early bird", fa: "سحرخیز" },
  { id: 500117, level: "B1", pos: "slang", en: "emoji", fa: "شکلک" },
  { id: 500118, level: "B1", pos: "slang", en: "epic", fa: "حماسی" },
  { id: 500119, level: "B1", pos: "slang", en: "ew", fa: "ایو" },
  { id: 500120, level: "B1", pos: "slang", en: "extra", fa: "اغراق‌آمیز و پرسروصدا" },
  { id: 500121, level: "B1", pos: "slang", en: "fab", fa: "عالی" },
  { id: 500122, level: "B1", pos: "slang", en: "fabulous", fa: "فوقالعاده" },
  { id: 500123, level: "B1", pos: "slang", en: "facepalm", fa: "زدن کف دست به پیشانی" },
  { id: 500124, level: "B1", pos: "slang", en: "facts", fa: "دقیقاً" },
  { id: 500125, level: "B1", pos: "slang", en: "fail", fa: "شکست" },
  { id: 500126, level: "B1", pos: "slang", en: "fam", fa: "خانواده، رفقا" },
  { id: 500127, level: "B1", pos: "slang", en: "fella", fa: "پسر" },
  { id: 500128, level: "B1", pos: "slang", en: "flex", fa: "به رخ کشیدن، فخرفروشی" },
  { id: 500129, level: "B1", pos: "slang", en: "follow", fa: "دنبال کردن" },
  { id: 500130, level: "B1", pos: "slang", en: "freak out", fa: "وحشت زده شدن" },
  { id: 500131, level: "B1", pos: "slang", en: "fresh", fa: "جدید و جذاب" },
  { id: 500132, level: "B1", pos: "slang", en: "gang", fa: "باند" },
  { id: 500133, level: "B1", pos: "slang", en: "garbage", fa: "افتضاح" },
  { id: 500134, level: "B1", pos: "slang", en: "gee", fa: "عجب" },
  { id: 500135, level: "B1", pos: "slang", en: "geek", fa: "آدم اینترنتی یا علمی" },
  { id: 500136, level: "B1", pos: "slang", en: "geezer", fa: "پیرمرد" },
  { id: 500137, level: "B1", pos: "slang", en: "get a W", fa: "برنده شدن" },
  { id: 500138, level: "B1", pos: "slang", en: "get lost", fa: "گم شو" },
  { id: 500139, level: "B1", pos: "slang", en: "get together", fa: "دور هم جمع شدن" },
  { id: 500140, level: "B1", pos: "slang", en: "ghost", fa: "ناپدید شدن" },
  { id: 500141, level: "B1", pos: "slang", en: "ghost someone", fa: "بدون خداحافظی ارتباط را قطع کردن" },
  { id: 500142, level: "B1", pos: "slang", en: "ghosted", fa: "کسی که بی‌خبر رهایش کرده‌اند" },
  { id: 500143, level: "B1", pos: "slang", en: "ghosting", fa: "قطع ارتباط ناگهانی" },
  { id: 500144, level: "B1", pos: "slang", en: "gig", fa: "کار، کنسرت" },
  { id: 500145, level: "B1", pos: "slang", en: "give it a shot", fa: "امتحانش کن" },
  { id: 500146, level: "B1", pos: "slang", en: "glow up", fa: "تغییر ظاهری مثبت و چشمگیر" },
  { id: 500147, level: "B1", pos: "slang", en: "go outside", fa: "برو بیرون" },
  { id: 500148, level: "B1", pos: "slang", en: "go viral", fa: "به‌سرعت در فضای مجازی پخش شدن" },
  { id: 500149, level: "B1", pos: "slang", en: "go-getter", fa: "آدم پویا" },
  { id: 500150, level: "B1", pos: "slang", en: "good sport", fa: "آدم روراست" },
  { id: 500151, level: "B1", pos: "slang", en: "goodies", fa: "چیزهای خوب" },
  { id: 500152, level: "B1", pos: "slang", en: "gosh", fa: "خدای من" },
  { id: 500153, level: "B1", pos: "slang", en: "green flag", fa: "علامت خوب" },
  { id: 500154, level: "B1", pos: "slang", en: "grind", fa: "کار سخت و مداوم" },
  { id: 500155, level: "B1", pos: "slang", en: "hang out", fa: "وقت گذروندن" },
  { id: 500156, level: "B1", pos: "slang", en: "hangry", fa: "گرسنه و عصبی" },
  { id: 500157, level: "B1", pos: "slang", en: "hard launch", fa: "معرفی رسمی" },
  { id: 500158, level: "B1", pos: "slang", en: "hashtag", fa: "هشتگ" },
  { id: 500159, level: "B1", pos: "slang", en: "hit the sack", fa: "برم بخوابم" },
  { id: 500160, level: "B1", pos: "slang", en: "hit up", fa: "پیام دادن" },
  { id: 500161, level: "B1", pos: "slang", en: "homie", fa: "رفیق" },
  { id: 500162, level: "B1", pos: "slang", en: "howdy", fa: "سلام" },
  { id: 500163, level: "B1", pos: "slang", en: "hubby", fa: "شوهر" },
  { id: 500164, level: "B1", pos: "slang", en: "humblebrag", fa: "فخر فروشی پنهان" },
  { id: 500165, level: "B1", pos: "slang", en: "hustle", fa: "تلاش زیاد" },
  { id: 500166, level: "B1", pos: "slang", en: "hype", fa: "هیاهو، تبلیغات" },
  { id: 500167, level: "B1", pos: "slang", en: "iconic", fa: "فراموش‌نشدنی و خاص" },
  { id: 500168, level: "B1", pos: "slang", en: "jackpot", fa: "شانس بزرگ" },
  { id: 500169, level: "B1", pos: "slang", en: "junk", fa: "چرت و پرت" },
  { id: 500170, level: "B1", pos: "slang", en: "kick back", fa: "آرام گرفتن" },
  { id: 500171, level: "B1", pos: "slang", en: "kiddo", fa: "بچه" },
  { id: 500172, level: "B1", pos: "slang", en: "knock it off", fa: "دست بردار" },
  { id: 500173, level: "B1", pos: "slang", en: "know-it-all", fa: "همه‌چیزدان" },
  { id: 500174, level: "B1", pos: "slang", en: "lad", fa: "پسر" },
  { id: 500175, level: "B1", pos: "slang", en: "lame", fa: "بی‌مزه، افتضاح" },
  { id: 500176, level: "B1", pos: "slang", en: "lass", fa: "دختر" },
  { id: 500177, level: "B1", pos: "slang", en: "left on read", fa: "پیامی که خوانده شده ولی بی‌جواب مانده" },
  { id: 500178, level: "B1", pos: "slang", en: "like", fa: "لایک" },
  { id: 500179, level: "B1", pos: "slang", en: "lit", fa: "داغ، عالی" },
  { id: 500180, level: "B1", pos: "slang", en: "loser", fa: "بازنده" },
  { id: 500181, level: "B1", pos: "slang", en: "love bombing", fa: "ابراز عشق بیش‌ازحد" },
  { id: 500182, level: "B1", pos: "slang", en: "main character", fa: "شخصیت اصلی" },
  { id: 500183, level: "B1", pos: "slang", en: "man", fa: "مرد" },
  { id: 500184, level: "B1", pos: "slang", en: "mate", fa: "رفیق (بریتانیایی)" },
  { id: 500185, level: "B1", pos: "slang", en: "meme", fa: "میم" },
  { id: 500186, level: "B1", pos: "slang", en: "mess up", fa: "به هم ریختن" },
  { id: 500187, level: "B1", pos: "slang", en: "missus", fa: "همسر" },
  { id: 500188, level: "B1", pos: "slang", en: "mute", fa: "بی‌صدا کردن" },
  { id: 500189, level: "B1", pos: "slang", en: "my bad", fa: "تقصیر خودم بود" },
  { id: 500190, level: "B1", pos: "slang", en: "nerd", fa: "درس‌خوان، کتابی" },
  { id: 500191, level: "B1", pos: "slang", en: "night owl", fa: "شب‌زنده‌دار" },
  { id: 500192, level: "B1", pos: "slang", en: "no biggie", fa: "چیز مهمی نیست" },
  { id: 500193, level: "B1", pos: "slang", en: "no sweat", fa: "راحت، اشکال نداره" },
  { id: 500194, level: "B1", pos: "slang", en: "nosy", fa: "فضول" },
  { id: 500195, level: "B1", pos: "slang", en: "orbiting", fa: "نگاه از دور" },
  { id: 500196, level: "B1", pos: "slang", en: "party animal", fa: "مهمونی‌رو" },
  { id: 500197, level: "B1", pos: "slang", en: "peeps", fa: "آدم‌ها، رفقا" },
  { id: 500198, level: "B1", pos: "slang", en: "period", fa: "نقطه، تمام" },
  { id: 500199, level: "B1", pos: "slang", en: "periodt", fa: "کاملاً تمام" },
  { id: 500200, level: "B1", pos: "slang", en: "phew", fa: "آه" },
  { id: 500201, level: "B1", pos: "slang", en: "piece of cake", fa: "مثل آب خوردن" },
  { id: 500202, level: "B1", pos: "slang", en: "pitch in", fa: "سهیم شدن" },
  { id: 500203, level: "B1", pos: "slang", en: "posse", fa: "دسته" },
  { id: 500204, level: "B1", pos: "slang", en: "post", fa: "پست" },
  { id: 500205, level: "B1", pos: "slang", en: "preach", fa: "دقیقاً" },
  { id: 500206, level: "B1", pos: "slang", en: "psst", fa: "هیس" },
  { id: 500207, level: "B1", pos: "slang", en: "rad", fa: "عالی" },
  { id: 500208, level: "B1", pos: "slang", en: "red flag", fa: "علامت خطر" },
  { id: 500209, level: "B1", pos: "slang", en: "ride or die", fa: "رفیق جان" },
  { id: 500210, level: "B1", pos: "slang", en: "rip-off", fa: "کلاهبرداری، گرون‌فروشی" },
  { id: 500211, level: "B1", pos: "slang", en: "roast", fa: "سر به سر گذاشتن" },
  { id: 500212, level: "B1", pos: "slang", en: "rock", fa: "عالی انجام دادن" },
  { id: 500213, level: "B1", pos: "slang", en: "salty", fa: "از دست کسی دلخور و کینه‌ای" },
  { id: 500214, level: "B1", pos: "slang", en: "savage", fa: "بی‌رحم، تند" },
  { id: 500215, level: "B1", pos: "slang", en: "score", fa: "به دست آوردن" },
  { id: 500216, level: "B1", pos: "slang", en: "screw up", fa: "خراب کردن" },
  { id: 500217, level: "B1", pos: "slang", en: "selfie", fa: "سلفی" },
  { id: 500218, level: "B1", pos: "slang", en: "shade", fa: "تحقیر غیرمستقیم" },
  { id: 500219, level: "B1", pos: "slang", en: "shake", fa: "تکان دادن" },
  { id: 500220, level: "B1", pos: "slang", en: "share", fa: "به اشتراک گذاشتن" },
  { id: 500221, level: "B1", pos: "slang", en: "shoot", fa: "بگو، بپرس" },
  { id: 500222, level: "B1", pos: "slang", en: "show-off", fa: "خودنمایی" },
  { id: 500223, level: "B1", pos: "slang", en: "shut up", fa: "خفه شو" },
  { id: 500224, level: "B1", pos: "slang", en: "sick", fa: "فوق‌العاده (عامیانه)" },
  { id: 500225, level: "B1", pos: "slang", en: "sigh", fa: "آه کشیدن" },
  { id: 500226, level: "B1", pos: "slang", en: "sip the tea", fa: "به خبر گوش دادن" },
  { id: 500227, level: "B1", pos: "slang", en: "situationship", fa: "رابطه مبهم" },
  { id: 500228, level: "B1", pos: "slang", en: "slacker", fa: "آدم تنبل" },
  { id: 500229, level: "B1", pos: "slang", en: "slam", fa: "محکوم کردن" },
  { id: 500230, level: "B1", pos: "slang", en: "slide into DMs", fa: "پیام خصوصی دادن" },
  { id: 500231, level: "B1", pos: "slang", en: "smart alec", fa: "اهل فضل فروش" },
  { id: 500232, level: "B1", pos: "slang", en: "smh", fa: "سر تکان دادن از ناامیدی" },
  { id: 500233, level: "B1", pos: "slang", en: "soft launch", fa: "معرفی آهسته" },
  { id: 500234, level: "B1", pos: "slang", en: "sore loser", fa: "بازنده بد" },
  { id: 500235, level: "B1", pos: "slang", en: "spill", fa: "لو دادن" },
  { id: 500236, level: "B1", pos: "slang", en: "spill the tea", fa: "آخرین خبرها یا شایعات را گفتن" },
  { id: 500237, level: "B1", pos: "slang", en: "split", fa: "تقسم کردن، رفتن" },
  { id: 500238, level: "B1", pos: "slang", en: "squad", fa: "تیم" },
  { id: 500239, level: "B1", pos: "slang", en: "steal", fa: "خرید عالی" },
  { id: 500240, level: "B1", pos: "slang", en: "straight", fa: "رک و صریح" },
  { id: 500241, level: "B1", pos: "slang", en: "stuff", fa: "چیزها" },
  { id: 500242, level: "B1", pos: "slang", en: "sucks", fa: "افتضاحه" },
  { id: 500243, level: "B1", pos: "slang", en: "sup", fa: "چه خبر" },
  { id: 500244, level: "B1", pos: "slang", en: "sus", fa: "مشکوک" },
  { id: 500245, level: "B1", pos: "slang", en: "sweet", fa: "عالیه" },
  { id: 500246, level: "B1", pos: "slang", en: "take an L", fa: "شکست خوردن" },
  { id: 500247, level: "B1", pos: "slang", en: "take it easy", fa: "سخت نگیر" },
  { id: 500248, level: "B1", pos: "slang", en: "tea", fa: "خبر، شایعه" },
  { id: 500249, level: "B1", pos: "slang", en: "terrific", fa: "خارق‌العاده" },
  { id: 500250, level: "B1", pos: "slang", en: "the ick", fa: "بیزاری ناگهانی" },
  { id: 500251, level: "B1", pos: "slang", en: "thing", fa: "چیز" },
  { id: 500252, level: "B1", pos: "slang", en: "throw shade", fa: "پشت سر کسی حرف زدن، تحقیر ظریف" },
  { id: 500253, level: "B1", pos: "slang", en: "trash", fa: "آشغال، افتضاح" },
  { id: 500254, level: "B1", pos: "slang", en: "trend", fa: "روند" },
  { id: 500255, level: "B1", pos: "slang", en: "troll", fa: "ترول" },
  { id: 500256, level: "B1", pos: "slang", en: "troublemaker", fa: "آدم دردسرساز" },
  { id: 500257, level: "B1", pos: "slang", en: "ugh", fa: "اوغ" },
  { id: 500258, level: "B1", pos: "slang", en: "unfollow", fa: "آنفالو کردن" },
  { id: 500259, level: "B1", pos: "slang", en: "veg out", fa: "هیچی نکردن، استراحت" },
  { id: 500260, level: "B1", pos: "slang", en: "vibe check", fa: "بررسی حس‌وحال یا انرژی یک موقعیت" },
  { id: 500261, level: "B1", pos: "slang", en: "viral", fa: "ویژگی" },
  { id: 500262, level: "B1", pos: "slang", en: "vlog", fa: "ولگ" },
  { id: 500263, level: "B1", pos: "slang", en: "what's up", fa: "چه خبر" },
  { id: 500264, level: "B1", pos: "slang", en: "whew", fa: "آه" },
  { id: 500265, level: "B1", pos: "slang", en: "whiz", fa: "استاد" },
  { id: 500266, level: "B1", pos: "slang", en: "whoa", fa: "وای" },
  { id: 500267, level: "B1", pos: "slang", en: "wicked", fa: "خیلی خوب (عامیانه)" },
  { id: 500268, level: "B1", pos: "slang", en: "win", fa: "برنده شدن" },
  { id: 500269, level: "B1", pos: "slang", en: "winner", fa: "برنده" },
  { id: 500270, level: "B1", pos: "slang", en: "wired", fa: "پر انرژی" },
  { id: 500271, level: "B1", pos: "slang", en: "word", fa: "باشه، درسته" },
  { id: 500272, level: "B1", pos: "slang", en: "yikes", fa: "وای" },
  { id: 500273, level: "B1", pos: "slang", en: "yo", fa: "یو" },
  { id: 500274, level: "B1", pos: "slang", en: "yolo", fa: "فقط یک بار زندگی می‌کنیم" },
  { id: 500275, level: "B1", pos: "slang", en: "zombie", fa: "آدم خسته و خواب‌آلود" },
  { id: 500276, level: "B1", pos: "slang", en: "zonk out", fa: "از حال رفتن" },
  { id: 500277, level: "B2", pos: "slang", en: "above and beyond", fa: "فراتر از" },
  { id: 500278, level: "B2", pos: "slang", en: "acoustic", fa: "آکوستیک" },
  { id: 500279, level: "B2", pos: "slang", en: "acting your wage", fa: "کار برابر حقوق" },
  { id: 500280, level: "B2", pos: "slang", en: "aesthetic", fa: "زیباشناختی" },
  { id: 500281, level: "B2", pos: "slang", en: "air guitar", fa: "گیتار هوایی" },
  { id: 500282, level: "B2", pos: "slang", en: "album", fa: "آلبوم" },
  { id: 500283, level: "B2", pos: "slang", en: "align", fa: "همسو شدن" },
  { id: 500284, level: "B2", pos: "slang", en: "amateur", fa: "آماتور" },
  { id: 500285, level: "B2", pos: "slang", en: "anthem", fa: "سرود" },
  { id: 500286, level: "B2", pos: "slang", en: "aura", fa: "هاله" },
  { id: 500287, level: "B2", pos: "slang", en: "bad vibes", fa: "حس بد" },
  { id: 500288, level: "B2", pos: "slang", en: "baddie", fa: "خوش‌استایل" },
  { id: 500289, level: "B2", pos: "slang", en: "ballin'", fa: "پولدار" },
  { id: 500290, level: "B2", pos: "slang", en: "bandwagon", fa: "مد" },
  { id: 500291, level: "B2", pos: "slang", en: "banger", fa: "آهنگ عالی" },
  { id: 500292, level: "B2", pos: "slang", en: "bare minimum", fa: "حداقل" },
  { id: 500293, level: "B2", pos: "slang", en: "benchmark", fa: "معیار" },
  { id: 500294, level: "B2", pos: "slang", en: "benefits", fa: "مزایا" },
  { id: 500295, level: "B2", pos: "slang", en: "best practices", fa: "بهترین روش" },
  { id: 500296, level: "B2", pos: "slang", en: "big yikes", fa: "وای چه ضایع" },
  { id: 500297, level: "B2", pos: "slang", en: "billboard", fa: "تابلو" },
  { id: 500298, level: "B2", pos: "slang", en: "bootleg", fa: "غیرمجاز" },
  { id: 500299, level: "B2", pos: "slang", en: "bop", fa: "آهنگ جذاب" },
  { id: 500300, level: "B2", pos: "slang", en: "boss babe", fa: "زن کارآفرین" },
  { id: 500301, level: "B2", pos: "slang", en: "boutique", fa: "بوتیک" },
  { id: 500302, level: "B2", pos: "slang", en: "broke", fa: "بی‌پول" },
  { id: 500303, level: "B2", pos: "slang", en: "budget", fa: "بودجه" },
  { id: 500304, level: "B2", pos: "slang", en: "cameo", fa: "ظاهر کوتاه" },
  { id: 500305, level: "B2", pos: "slang", en: "cancel culture", fa: "فرهنگ طرد عمومی افراد به‌خاطر اشتباهاتشان" },
  { id: 500306, level: "B2", pos: "slang", en: "canceled", fa: "طردشده به‌خاطر یک جنجال" },
  { id: 500307, level: "B2", pos: "slang", en: "check-in", fa: "بررسی" },
  { id: 500308, level: "B2", pos: "slang", en: "cinematic universe", fa: "جهان سینمایی" },
  { id: 500309, level: "B2", pos: "slang", en: "circle back", fa: "برگشت به موضوع" },
  { id: 500310, level: "B2", pos: "slang", en: "circle pit", fa: "دایره رقص" },
  { id: 500311, level: "B2", pos: "slang", en: "clean girl", fa: "استایل ساده" },
  { id: 500312, level: "B2", pos: "slang", en: "clickbait", fa: "عنوان فریبنده برای جذب کلیک" },
  { id: 500313, level: "B2", pos: "slang", en: "cliffhanger", fa: "تعلیق" },
  { id: 500314, level: "B2", pos: "slang", en: "clout", fa: "محبوبیت و نفوذ اجتماعی" },
  { id: 500315, level: "B2", pos: "slang", en: "clout chasing", fa: "دنبال محبوبیت و توجه بودن" },
  { id: 500316, level: "B2", pos: "slang", en: "cold call", fa: "تماس سرد" },
  { id: 500317, level: "B2", pos: "slang", en: "cold email", fa: "ایمیل سرد" },
  { id: 500318, level: "B2", pos: "slang", en: "cold take", fa: "نظر بدیهی" },
  { id: 500319, level: "B2", pos: "slang", en: "coquette", fa: "استایل دخترانه" },
  { id: 500320, level: "B2", pos: "slang", en: "cover", fa: "کاور" },
  { id: 500321, level: "B2", pos: "slang", en: "coworking", fa: "هم‌کاری" },
  { id: 500322, level: "B2", pos: "slang", en: "crowd", fa: "جمعیت" },
  { id: 500323, level: "B2", pos: "slang", en: "crowd surfing", fa: "روی جمعیت شناور" },
  { id: 500324, level: "B2", pos: "slang", en: "curated", fa: "انتخابی" },
  { id: 500325, level: "B2", pos: "slang", en: "demo", fa: "دمو" },
  { id: 500326, level: "B2", pos: "slang", en: "dish", fa: "بگو، خبر بده" },
  { id: 500327, level: "B2", pos: "slang", en: "drop", fa: "انتشار" },
  { id: 500328, level: "B2", pos: "slang", en: "easter egg", fa: "تخم‌مرغ پنهان" },
  { id: 500329, level: "B2", pos: "slang", en: "elevator pitch", fa: "معرفی کوتاه" },
  { id: 500330, level: "B2", pos: "slang", en: "encore", fa: "تکرار" },
  { id: 500331, level: "B2", pos: "slang", en: "energy", fa: "انرژی" },
  { id: 500332, level: "B2", pos: "slang", en: "financial freedom", fa: "آزادی مالی" },
  { id: 500333, level: "B2", pos: "slang", en: "fired", fa: "اخراج شده" },
  { id: 500334, level: "B2", pos: "slang", en: "fit", fa: "استایل" },
  { id: 500335, level: "B2", pos: "slang", en: "follow-up", fa: "پیگیری" },
  { id: 500336, level: "B2", pos: "slang", en: "franchise", fa: "فرنچایز" },
  { id: 500337, level: "B2", pos: "slang", en: "freelance", fa: "آزاد" },
  { id: 500338, level: "B2", pos: "slang", en: "game-changer", fa: "تغییر دهنده بازی" },
  { id: 500339, level: "B2", pos: "slang", en: "gaslight", fa: "با دروغ، کسی را نسبت به واقعیت خودش دچار شک کردن" },
  { id: 500340, level: "B2", pos: "slang", en: "gatekeep", fa: "مانع دسترسی" },
  { id: 500341, level: "B2", pos: "slang", en: "gatekeeping", fa: "انحصار" },
  { id: 500342, level: "B2", pos: "slang", en: "gig economy", fa: "اقتصاد آزاد" },
  { id: 500343, level: "B2", pos: "slang", en: "girlboss", fa: "زن موفق" },
  { id: 500344, level: "B2", pos: "slang", en: "glow down", fa: "دگرگونی منفی" },
  { id: 500345, level: "B2", pos: "slang", en: "go off", fa: "بگو، ادامه بده" },
  { id: 500346, level: "B2", pos: "slang", en: "go the extra mile", fa: "تلاش بیشتر" },
  { id: 500347, level: "B2", pos: "slang", en: "goat", fa: "بزرگترین" },
  { id: 500348, level: "B2", pos: "slang", en: "good vibes", fa: "حس خوب" },
  { id: 500349, level: "B2", pos: "slang", en: "gossip", fa: "شایعه" },
  { id: 500350, level: "B2", pos: "slang", en: "grind culture", fa: "فرهنگ کار سخت" },
  { id: 500351, level: "B2", pos: "slang", en: "gyatt", fa: "جذابیت ظاهری" },
  { id: 500352, level: "B2", pos: "slang", en: "headbang", fa: "تکان سر" },
  { id: 500353, level: "B2", pos: "slang", en: "headliner", fa: "سرگروه" },
  { id: 500354, level: "B2", pos: "slang", en: "high-end", fa: "لوکس" },
  { id: 500355, level: "B2", pos: "slang", en: "hits different", fa: "حس متفاوت و خاصی دارد" },
  { id: 500356, level: "B2", pos: "slang", en: "hot take", fa: "نظر جنجالی" },
  { id: 500357, level: "B2", pos: "slang", en: "hustle culture", fa: "فرهنگ تلاش" },
  { id: 500358, level: "B2", pos: "slang", en: "hybrid", fa: "ترکیبی" },
  { id: 500359, level: "B2", pos: "slang", en: "hype train", fa: "هیاهو" },
  { id: 500360, level: "B2", pos: "slang", en: "hyped", fa: "تبلیغ شده" },
  { id: 500361, level: "B2", pos: "slang", en: "icon", fa: "نماد" },
  { id: 500362, level: "B2", pos: "slang", en: "inbox", fa: "صندوق ورودی" },
  { id: 500363, level: "B2", pos: "slang", en: "indie", fa: "مستقل" },
  { id: 500364, level: "B2", pos: "slang", en: "it's giving", fa: "حس یا فضای ... را دارد" },
  { id: 500365, level: "B2", pos: "slang", en: "jam", fa: "بداهه‌نوازی" },
  { id: 500366, level: "B2", pos: "slang", en: "jump on the bandwagon", fa: "همراه جمع شدن" },
  { id: 500367, level: "B2", pos: "slang", en: "layoff", fa: "اخراج" },
  { id: 500368, level: "B2", pos: "slang", en: "leak", fa: "لو رفتن" },
  { id: 500369, level: "B2", pos: "slang", en: "legend", fa: "افسانه" },
  { id: 500370, level: "B2", pos: "slang", en: "lewk", fa: "نگاه، استایل" },
  { id: 500371, level: "B2", pos: "slang", en: "life-changing", fa: "تغییر دهنده زندگی" },
  { id: 500372, level: "B2", pos: "slang", en: "live", fa: "زنده" },
  { id: 500373, level: "B2", pos: "slang", en: "live stream", fa: "پخش زنده" },
  { id: 500374, level: "B2", pos: "slang", en: "living rent free", fa: "فکر کردن مداوم و ناخواسته به یک چیز" },
  { id: 500375, level: "B2", pos: "slang", en: "loaded", fa: "پولدار" },
  { id: 500376, level: "B2", pos: "slang", en: "lose-lose", fa: "باخت-باخت" },
  { id: 500377, level: "B2", pos: "slang", en: "low-end", fa: "ارزان" },
  { id: 500378, level: "B2", pos: "slang", en: "low-hanging fruit", fa: "اهداف آسان" },
  { id: 500379, level: "B2", pos: "slang", en: "main character energy", fa: "رفتار مثل شخصیت اصلی داستان زندگی خود" },
  { id: 500380, level: "B2", pos: "slang", en: "mainstream", fa: "جریان اصلی" },
  { id: 500381, level: "B2", pos: "slang", en: "max effort", fa: "حداکثر تلاش" },
  { id: 500382, level: "B2", pos: "slang", en: "micromanage", fa: "مدیریت دقیق" },
  { id: 500383, level: "B2", pos: "slang", en: "micromanager", fa: "مدیر موشکاف" },
  { id: 500384, level: "B2", pos: "slang", en: "mind-blowing", fa: "ذهن‌زده" },
  { id: 500385, level: "B2", pos: "slang", en: "minimum effort", fa: "کمترین تلاش" },
  { id: 500386, level: "B2", pos: "slang", en: "mixtape", fa: "میکس‌تاپ" },
  { id: 500387, level: "B2", pos: "slang", en: "mood", fa: "حالت" },
  { id: 500388, level: "B2", pos: "slang", en: "mood booster", fa: "بالا برنده خلق" },
  { id: 500389, level: "B2", pos: "slang", en: "mood killer", fa: "کشنده خلق" },
  { id: 500390, level: "B2", pos: "slang", en: "mosh pit", fa: "محل رقص" },
  { id: 500391, level: "B2", pos: "slang", en: "networking", fa: "شبکه‌سازی" },
  { id: 500392, level: "B2", pos: "slang", en: "newbie", fa: "تازه‌کار" },
  { id: 500393, level: "B2", pos: "slang", en: "next level", fa: "سطح بعدی" },
  { id: 500394, level: "B2", pos: "slang", en: "no-brainer", fa: "تصمیم آسان" },
  { id: 500395, level: "B2", pos: "slang", en: "noob", fa: "تازه‌کار" },
  { id: 500396, level: "B2", pos: "slang", en: "notice", fa: "اعلام" },
  { id: 500397, level: "B2", pos: "slang", en: "notif", fa: "اعلان" },
  { id: 500398, level: "B2", pos: "slang", en: "offboard", fa: "خروج" },
  { id: 500399, level: "B2", pos: "slang", en: "OG", fa: "قدیمی اصلی" },
  { id: 500400, level: "B2", pos: "slang", en: "old money", fa: "استایل کلاسیک" },
  { id: 500401, level: "B2", pos: "slang", en: "onboard", fa: "معارفه" },
  { id: 500402, level: "B2", pos: "slang", en: "opener", fa: "آغازگر" },
  { id: 500403, level: "B2", pos: "slang", en: "outfit", fa: "لباس" },
  { id: 500404, level: "B2", pos: "slang", en: "overdeliver", fa: "بیش از حد تحویل دادن" },
  { id: 500405, level: "B2", pos: "slang", en: "overrated", fa: "بیش‌دیده" },
  { id: 500406, level: "B2", pos: "slang", en: "pain point", fa: "مشکل" },
  { id: 500407, level: "B2", pos: "slang", en: "passive income", fa: "درآمد غیرفعال" },
  { id: 500408, level: "B2", pos: "slang", en: "paycheck", fa: "حقوق" },
  { id: 500409, level: "B2", pos: "slang", en: "payday", fa: "روز حقوق" },
  { id: 500410, level: "B2", pos: "slang", en: "penniless", fa: "بی‌پول" },
  { id: 500411, level: "B2", pos: "slang", en: "perks", fa: "مزایا" },
  { id: 500412, level: "B2", pos: "slang", en: "pick me", fa: "توجه‌طلب" },
  { id: 500413, level: "B2", pos: "slang", en: "pick me girl", fa: "دختر توجه‌طلب" },
  { id: 500414, level: "B2", pos: "slang", en: "pit", fa: "محل" },
  { id: 500415, level: "B2", pos: "slang", en: "pitch", fa: "معرفی" },
  { id: 500416, level: "B2", pos: "slang", en: "playlist", fa: "پلی‌لیست" },
  { id: 500417, level: "B2", pos: "slang", en: "plot twist", fa: "پیچش داستان" },
  { id: 500418, level: "B2", pos: "slang", en: "podcast", fa: "پادکست" },
  { id: 500419, level: "B2", pos: "slang", en: "popular opinion", fa: "نظر محبوب" },
  { id: 500420, level: "B2", pos: "slang", en: "post-credits", fa: "پس از تیتراژ" },
  { id: 500421, level: "B2", pos: "slang", en: "poster", fa: "پوستر" },
  { id: 500422, level: "B2", pos: "slang", en: "premiere", fa: "اولین نمایش" },
  { id: 500423, level: "B2", pos: "slang", en: "prequel", fa: "پیش‌درآمد" },
  { id: 500424, level: "B2", pos: "slang", en: "pro", fa: "حرفه‌ای" },
  { id: 500425, level: "B2", pos: "slang", en: "proof", fa: "اثبات" },
  { id: 500426, level: "B2", pos: "slang", en: "push notif", fa: "اعلان فوری" },
  { id: 500427, level: "B2", pos: "slang", en: "quiet luxury", fa: "لوکس بی‌سروصدا" },
  { id: 500428, level: "B2", pos: "slang", en: "quiet quitting", fa: "کار حداقلی" },
  { id: 500429, level: "B2", pos: "slang", en: "quit", fa: "استعفا" },
  { id: 500430, level: "B2", pos: "slang", en: "quote tweet", fa: "نقل قول توییت" },
  { id: 500431, level: "B2", pos: "slang", en: "ratio", fa: "وقتی واکنش به یک پست بیشتر از خود پست توجه می‌گیرد" },
  { id: 500432, level: "B2", pos: "slang", en: "reality check", fa: "بررسی واقعیت" },
  { id: 500433, level: "B2", pos: "slang", en: "reboot", fa: "بازراه‌اندازی" },
  { id: 500434, level: "B2", pos: "slang", en: "rebrand", fa: "تغییر تصویر" },
  { id: 500435, level: "B2", pos: "slang", en: "receipts", fa: "مدرک یا سند برای اثبات حرف" },
  { id: 500436, level: "B2", pos: "slang", en: "release", fa: "انتشار" },
  { id: 500437, level: "B2", pos: "slang", en: "remake", fa: "بازسازی" },
  { id: 500438, level: "B2", pos: "slang", en: "remix", fa: "ریمیکس" },
  { id: 500439, level: "B2", pos: "slang", en: "remote", fa: "دورکاری" },
  { id: 500440, level: "B2", pos: "slang", en: "repost", fa: "بازنشر" },
  { id: 500441, level: "B2", pos: "slang", en: "resign", fa: "استعفا" },
  { id: 500442, level: "B2", pos: "slang", en: "retweet", fa: "بازتوییت" },
  { id: 500443, level: "B2", pos: "slang", en: "rizz", fa: "جذابیت و مهارت در فلرت کردن" },
  { id: 500444, level: "B2", pos: "slang", en: "rizzler", fa: "فرد جذاب" },
  { id: 500445, level: "B2", pos: "slang", en: "rookie", fa: "تازه‌کار" },
  { id: 500446, level: "B2", pos: "slang", en: "rumor", fa: "شایعه" },
  { id: 500447, level: "B2", pos: "slang", en: "salary", fa: "حقوق" },
  { id: 500448, level: "B2", pos: "slang", en: "screenshot", fa: "اسکرین‌شات" },
  { id: 500449, level: "B2", pos: "slang", en: "sequel", fa: "دنباله" },
  { id: 500450, level: "B2", pos: "slang", en: "session", fa: "جلسه" },
  { id: 500451, level: "B2", pos: "slang", en: "severance", fa: "حقوق پایان کار" },
  { id: 500452, level: "B2", pos: "slang", en: "side hustle", fa: "کار جانبی" },
  { id: 500453, level: "B2", pos: "slang", en: "simp", fa: "کسی که بیش‌ازحد برای جلب توجه کسی تلاش می‌کند" },
  { id: 500454, level: "B2", pos: "slang", en: "simping", fa: "توجیه کردن" },
  { id: 500455, level: "B2", pos: "slang", en: "single", fa: "تک آهنگ" },
  { id: 500456, level: "B2", pos: "slang", en: "slap", fa: "آهنگ خوب" },
  { id: 500457, level: "B2", pos: "slang", en: "sneak", fa: "پیش‌نمایش" },
  { id: 500458, level: "B2", pos: "slang", en: "sneak peek", fa: "پیش‌نمایش" },
  { id: 500459, level: "B2", pos: "slang", en: "source", fa: "منبع" },
  { id: 500460, level: "B2", pos: "slang", en: "speculation", fa: "گمان" },
  { id: 500461, level: "B2", pos: "slang", en: "spicy tea", fa: "خبر داغ" },
  { id: 500462, level: "B2", pos: "slang", en: "spin-off", fa: "اسپین‌آف" },
  { id: 500463, level: "B2", pos: "slang", en: "spoiler", fa: "اسپویل" },
  { id: 500464, level: "B2", pos: "slang", en: "spoiler alert", fa: "اخطار اسپویل" },
  { id: 500465, level: "B2", pos: "slang", en: "stage dive", fa: "شیرجه روی صحنه" },
  { id: 500466, level: "B2", pos: "slang", en: "stream", fa: "استریم" },
  { id: 500467, level: "B2", pos: "slang", en: "studio", fa: "استودیو" },
  { id: 500468, level: "B2", pos: "slang", en: "sub", fa: "زیرنویس، اشتراک" },
  { id: 500469, level: "B2", pos: "slang", en: "sync up", fa: "هماهنگی" },
  { id: 500470, level: "B2", pos: "slang", en: "teaser", fa: "تیزر" },
  { id: 500471, level: "B2", pos: "slang", en: "thread", fa: "رشته" },
  { id: 500472, level: "B2", pos: "slang", en: "tight budget", fa: "بودجه محدود" },
  { id: 500473, level: "B2", pos: "slang", en: "touch base", fa: "هماهنگی" },
  { id: 500474, level: "B2", pos: "slang", en: "touch grass", fa: "از دنیای مجازی بیرون آمدن، به واقعیت برگشتن" },
  { id: 500475, level: "B2", pos: "slang", en: "track", fa: "آهنگ" },
  { id: 500476, level: "B2", pos: "slang", en: "trailer", fa: "تریلر" },
  { id: 500477, level: "B2", pos: "slang", en: "truth bomb", fa: "حقیقت تلخ" },
  { id: 500478, level: "B2", pos: "slang", en: "two weeks' notice", fa: "اعلام دو هفته" },
  { id: 500479, level: "B2", pos: "slang", en: "unbothered", fa: "بی‌توجه" },
  { id: 500480, level: "B2", pos: "slang", en: "unbothered queen", fa: "ملکه بی‌توجه" },
  { id: 500481, level: "B2", pos: "slang", en: "unconfirmed", fa: "تأیید نشده" },
  { id: 500482, level: "B2", pos: "slang", en: "underdeliver", fa: "کم تحویل دادن" },
  { id: 500483, level: "B2", pos: "slang", en: "underground", fa: "زیرزمینی" },
  { id: 500484, level: "B2", pos: "slang", en: "underhyped", fa: "کم‌تبلیغ" },
  { id: 500485, level: "B2", pos: "slang", en: "underrated", fa: "کم‌دیده" },
  { id: 500486, level: "B2", pos: "slang", en: "unpopular opinion", fa: "نظر نامحبوب" },
  { id: 500487, level: "B2", pos: "slang", en: "veteran", fa: "کهنه‌کار" },
  { id: 500488, level: "B2", pos: "slang", en: "vibes", fa: "حس و حال" },
  { id: 500489, level: "B2", pos: "slang", en: "wake-up call", fa: "هشدار" },
  { id: 500490, level: "B2", pos: "slang", en: "wall of death", fa: "دیوار مرگ" },
  { id: 500491, level: "B2", pos: "slang", en: "well-off", fa: "متمول" },
  { id: 500492, level: "B2", pos: "slang", en: "win-win", fa: "برد-برد" },
  { id: 500493, level: "C1", pos: "slang", en: "content", fa: "محتو" },
  { id: 500494, level: "C1", pos: "slang", en: "creator", fa: "سازنده" },
  { id: 500495, level: "C1", pos: "slang", en: "delulu", fa: "خیالاتی، در توهم به سر بردن" },
  { id: 500496, level: "C1", pos: "slang", en: "delulu land", fa: "سرزمین خیال" },
  { id: 500497, level: "C1", pos: "slang", en: "doomscrolling", fa: "بی‌وقفه اسکرول‌کردن اخبار بد" },
  { id: 500498, level: "C1", pos: "slang", en: "extra af", fa: "بیش از حد اغراق‌آمیز" },
  { id: 500499, level: "C1", pos: "slang", en: "flex on someone", fa: "به کسی فخر فروختن" },
  { id: 500500, level: "C1", pos: "slang", en: "gaslighter", fa: "آدم دروغ‌پراکن" },
  { id: 500501, level: "C1", pos: "slang", en: "go touch grass", fa: "برو بیرون" },
  { id: 500502, level: "C1", pos: "slang", en: "ick", fa: "حس ناگهانی بی‌میلی نسبت به کسی" },
  { id: 500503, level: "C1", pos: "slang", en: "influencer", fa: "اینفلوئنسر" },
  { id: 500504, level: "C1", pos: "slang", en: "JOMO", fa: "لذت بردن از جاماندن، برخلاف FOMO" },
  { id: 500505, level: "C1", pos: "slang", en: "main character syndrome", fa: "سندرم شخصیت اصلی" },
  { id: 500506, level: "C2", pos: "slang", en: "doomscroll", fa: "اسکرول منفی" },
  { id: 500507, level: "C2", pos: "slang", en: "fomo", fa: "ترس از جا موندن" },
  { id: 500508, level: "C2", pos: "slang", en: "talking stage", fa: "مرحله مکالمه" },
  { id: 500509, level: "C2", pos: "slang", en: "that boy", fa: "پسر ایده‌آل" },
  { id: 500510, level: "C2", pos: "slang", en: "that girl", fa: "دختر ایده‌آل" },
];
