export const VOCAB = [
  {
    id: 1,
    level: "B1",
    pos: "noun",
    meaningFa: "نظام تولید، توزیع و مصرف کالاها و خدمات در یک کشور",
    t: { fa: "اقتصاد", en: "economy", de: "Wirtschaft", es: "economía", fr: "économie", ar: "اقتصاد", tr: "ekonomi", zh: "经济" },
  },
  {
    id: 2,
    level: "A2",
    pos: "noun",
    meaningFa: "نهاد یا افرادی که یک کشور یا منطقه را اداره می‌کنند",
    t: { fa: "دولت", en: "government", de: "Regierung", es: "gobierno", fr: "gouvernement", ar: "حكومة", tr: "hükümet", zh: "政府" },
  },
  {
    id: 3,
    level: "B1",
    pos: "verb",
    meaningFa: "رسماً و علناً چیزی را اعلام کردن",
    t: { fa: "اعلام کردن", en: "to announce", de: "ankündigen", es: "anunciar", fr: "annoncer", ar: "الإعلان", tr: "duyurmak", zh: "宣布" },
  },
  {
    id: 4,
    level: "B2",
    pos: "adjective",
    meaningFa: "دارای اهمیت یا تاثیر قابل توجه",
    t: { fa: "قابل توجه", en: "significant", de: "bedeutend", es: "significativo", fr: "significatif", ar: "مهم", tr: "önemli", zh: "重大的" },
  },
  {
    id: 5,
    level: "B2",
    pos: "verb",
    meaningFa: "برای رسیدن به توافق با طرف مقابل گفتگو کردن",
    t: { fa: "مذاکره کردن", en: "to negotiate", de: "verhandeln", es: "negociar", fr: "négocier", ar: "التفاوض", tr: "müzakere etmek", zh: "谈判" },
  },
  {
    id: 6,
    level: "B1",
    pos: "noun",
    meaningFa: "وضعیت بحرانی و ناپایدار که نیازمند تصمیم فوری است",
    t: { fa: "بحران", en: "crisis", de: "Krise", es: "crisis", fr: "crise", ar: "أزمة", tr: "kriz", zh: "危机" },
  },
  {
    id: 7,
    level: "C1",
    pos: "adjective",
    meaningFa: "قابل ادامه در درازمدت بدون آسیب به منابع",
    t: { fa: "پایدار", en: "sustainable", de: "nachhaltig", es: "sostenible", fr: "durable", ar: "مستدام", tr: "sürdürülebilir", zh: "可持续的" },
  },
  {
    id: 8,
    level: "B1",
    pos: "noun",
    meaningFa: "کسی که به‌خاطر جنگ یا خطر، کشورش را ترک کرده",
    t: { fa: "پناهنده", en: "refugee", de: "Flüchtling", es: "refugiado", fr: "réfugié", ar: "لاجئ", tr: "mülteci", zh: "难民" },
  },
  {
    id: 9,
    level: "B2",
    pos: "noun",
    meaningFa: "نداشتن شغل با وجود توانایی و تمایل به کار کردن",
    t: { fa: "بیکاری", en: "unemployment", de: "Arbeitslosigkeit", es: "desempleo", fr: "chômage", ar: "بطالة", tr: "işsizlik", zh: "失业" },
  },
  {
    id: 10,
    level: "B1",
    pos: "noun",
    meaningFa: "خط‌مشی یا برنامه‌ی رسمی برای تصمیم‌گیری",
    t: { fa: "سیاست", en: "policy", de: "Politik", es: "política", fr: "politique", ar: "سياسة", tr: "politika", zh: "政策" },
  },
];
